### ISSUE TITLE
Argo oxygen sensor labels

### ISSUE THREAD

**Issue by pblain** [aodn/content#1]
To reproduce select argo on portal step 1.

The label "Float With Oxygen Sensor" is incorrect.  It should read "Floats with oxygen sensors".  Even this is slightly misleading.  The portal displays individual profiles, not floats.  It would be better written as "Profiles with oxygen measurements".

The checkbox label is also incorrect.  It reads "Select only data with float with oxygen sensor(s)".  It would be better written as "Select data from floats with oxygen sensors.".

**Comment by smancini** [comment]
Not relevant anymore
