### ISSUE TITLE
Download list URL doesn't work for collection without WFS attached to WMS

### ISSUE THREAD

**Issue by kereid** [aodn/content#10]
[Portal Build Info]
    Base URL:      http://portal-rc.aodn.org.au/imos123
    Build date:    18/03/2014 14:13
    Version:       3.19.0-rc2
    Instance name: IMOS
    Environment:   prerelease
-->
Steps to reproduce can be found at https://github.com/aodn/aodn-portal/issues/838 

I spoke to PO who approved logging in content repo as it is a config issue rather than a bug - as it is ok in production.

**Comment by smancini** [comment]
Works fine now
