### ISSUE TITLE
talend component iupdateSpatialExtent for geonetwork - possible issue

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#104]
After deploying the new harvester ANMN WAVE, I stumbled across this in the log file 

```
* iUpdateSpatialExtent - files changed: false
* iUpdateSpatialExtent - updating spatial extent: false
```

ad the end of its first run. This makes me think something is maybe incorrect with this component, as on the first run of a harvester, the files have kind of changed, and the metadata record should be updated.

**Comment by pblain** [comment]
@lbesnard , does this issue belong in the harvester repo?

**Comment by lbesnard** [comment]
@pblain I don't know where it should belong to. Either component,content or harvester

**Comment by lbesnard** [comment]
@pblain , FYI @bpasquer experienced the same issue with another harvester,
https://github.com/aodn/harvesters/pull/291/files

**Comment by pblain** [comment]
@lbesnard Thanks.  If the development team needs to look at this could you please ask @smancini (or Rog in his absence) to add to the backlog.  I'm assuming it's not a VIT because it's been like this since May.

**Comment by smancini** [comment]
Closing this issue for now as the metadata seems to be up-to-date.
@mhidas We will check that the harvester run successfully when wave data from a new mooring is added.
