### ISSUE TITLE
aodn_aims_ctd - harvester failing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#106]
Unparseable date: "11/12/2002 "

```
Exception while processing /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/DHBmet01-2.csv
Exception while processing /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/TRAmet02-2.csv
```

@bpasquer , is this your harvester or Xaviers ?

**Comment by lbesnard** [comment]
reasons seems to be because second part of time field 'local_start_time' is empty for those two files, hence the harvester fails because the time value is computed such as 
```java
row1.Start_date +" "+ row1.Local_start_time  
```
and there is no check on Local_start_time being a NaN, or being null

**Comment by danfruehauf** [comment]
He wants his beers.

**Comment by lbesnard** [comment]
@danfruehauf YEAP

@bpasquer , I did the mod but didn't push it cause a file is really really bizarre, not the proper encoding or something similar. 

do a cat or less on 
/mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AODN/AIMS_CTD/TRAmet01-2.csv
and TRAmet02-2.csv

**Comment by bpasquer** [comment]
As per our quick chat, i'd rather make correction to the file than modifiy the harvester to assume that the missing local_start_time is 00:00:00. It is valid in most of the case i have come across but in the case of DHBmet01 it is probably not as this file is missing all the local_start_time  field . So what i did here is:
-TRAmet02-2.csv: I corrected the missing field ( here it was one oxygen value) 
-DHBmet01-2: i removed it from the data set

**Comment by bpasquer** [comment]
Fixed both of them. Should be good to go now.
