### ISSUE TITLE
NOAA Drifters style name is wrong

### ISSUE THREAD

**Issue by dnahodil** [aodn/content#107]
The style for this layer is named 'Green Line' however the line is actually blue.

![screenshot from 2015-06-09 16 58 59](https://cloud.githubusercontent.com/assets/2774917/8052267/f96be344-0ec8-11e5-8171-1a03547e4ba7.png)

**Comment by mhidas** [comment]
@dnahodil Good point, but I think this is a more general issue. If it said "blue line" it wouldn't be any more helpful. Similarly, for most of the mooring layers we have:
![portal_redsquare](https://cloud.githubusercontent.com/assets/3579859/8072215/4edf7d76-0f56-11e5-9753-64181c683c1d.png)

**Comment by dnahodil** [comment]
@mhidas agreed
