### ISSUE TITLE
ANMN Wave time-series - TIME filtering issue (see on RC)

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#109]
The new __IMOS - AUSTRALIAN NATIONAL MOORING NETWORK (ANMN) - WAVE TIME-SERIES__ layer (found by selecting __Wave__ as a Physical parameter), the TIME selector doesn't work although it seems well configured.

Also, the download size estimate is really far from the reality. The reason why is because the harvested files are gridded netcdf, but only the timeseries data is being harvested (which is much smaller).

**Comment by dnahodil** [comment]
In response to your second comment:
The download size for every collection is never going to be completely accurate as all the download options vary in size. As you point out it's going to be worse on collections like this where only a small portion of the data is harvested from the source files. But keep in mind that people can download the un-subsetted NetCDF files in which case the download estimate will be correct.

**Comment by mhidas** [comment]
The time filter still doesn't work for this layer. Has anyone looked at this?

**Comment by lbesnard** [comment]
It's probably an easy thing, but still need the help of a dev to see whats wrong. so, nope, no one has looked into this afaik

**Comment by dnahodil** [comment]
You can grab me this afternoon @lbesnard if you want to have a look at this together.

**Comment by lbesnard** [comment]
fixed, works on 123
