### ISSUE TITLE
talend failing - aatams sattag dm

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#110]
Harvester failing becuase missing MDB driver to process microsoft access database files
```
Exception in component tJDBCInput_4
java.lang.ClassNotFoundException: jstels.jdbc.mdb.MDBDriver2
```

likely due to the rebuild yesterdaY ? @danfruehauf

**Comment by jonescc** [comment]
Needs mdbdriver.jar installed in talend open studio java/lib directory on jenkins so it gets packaged with the job.

Refer http://www.csv-jdbc.com/stels_mdb/doc.htm

**Comment by danfruehauf** [comment]
I'm working on that.

**Comment by danfruehauf** [comment]
That already working on RC

**Comment by danfruehauf** [comment]
Harvester is now also on prod, will run over the weekend.
