### ISSUE TITLE
talend failing - anmn realtime

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#111]
the harvester is failing mainly due to this :

```
Caused by: java.lang.Error: java.lang.Error: Unresolved compilation problems: 
        The method getName() is undefined for the type Attribute
        The method getName() is undefined for the type Attribute
```

What seems bizarre to me is why this harvester iterates over the THREDDS catalog at https://thredds.aodn.org.au/thredds/catalog/IMOS/ANMN/catalog.xml  and not directly from the data storage ?

**Comment by lbesnard** [comment]
> What seems bizarre to me is why this harvester iterates over the THREDDS catalog

because this is an old harvester used for the AODN portal

**Comment by danfruehauf** [comment]
Same as #112. Continue looking at #112 for more news.
