### ISSUE TITLE
Empty CSV when time filter set for SOOP TRV

### ISSUE THREAD

**Issue by kereid** [aodn/content#113]
App version: 4.6.1
            Build date: Fri Jun 12 18:42:47 AEST 2015
            Build number: 1
            Git ref: 1d2478cc16914fdfc8b7ade8abc245331f0e96fe
        -->
Steps to reproduce:

Add SOOP TRV to the map, Draw a small BB so that not too much data is downloaded, then proceed to step 3 and download.

go back to step 2 and select a from time (couple of years back) checking that there is still data visible on the map in the bb. Proceed to step 3 and download.

What should happen:

Get a CSV file with data inside

What does happen:

Get empty CSV file

**Comment by lbesnard** [comment]
@smancini , i had a look at this and can't find anything wrong in the layer configuration. Maybe something for the dev team to have a look at ?

geoserver filter
```
  <filter>
    <name>time</name>
    <type>datetime</type>
    <label>Time</label>
    <visualised>true</visualised>
    <excludedFromDownload>false</excludedFromDownload>
    <wmsStartDateName>time_start</wmsStartDateName>
    <wmsEndDateName>time_end</wmsEndDateName>
  </filter>
```

Tables definition
```sql
CREATE OR REPLACE VIEW soop_trv.soop_trv_trajectory_map AS 
SELECT
    timezone('UTC'::text, a.time_start) AS time_start,
    timezone('UTC'::text, a.time_end) AS time_end,
....

CREATE OR REPLACE VIEW soop_trv.soop_trv_trajectory_data AS 
 SELECT 
 timezone('UTC'::text, measurements_merged_data."TIME") AS "TIME",
```

**Comment by dnahodil** [comment]
Are the column names case-sensitive? The filters.xml says 'time' but the column name is 'TIME'?

**Comment by lbesnard** [comment]
Column names are case-sensitive. 

As this filter was done as part of the bulk change, I assume that the geoserver plugin was not case sensitive, but maybe this is wrong

**Comment by dnahodil** [comment]
Ok yeah, so maybe that bulk update got it wrong. So either the database column name should be updated, or the filter.xml should be updated so that they have the same case for both.

**Comment by lbesnard** [comment]
PR : https://github.com/aodn/geoserver-config/pull/270 ( not tested on my pobox yet)

**Comment by lbesnard** [comment]
@kereid can you test this in the next few days ? should be good soon

**Comment by lbesnard** [comment]
@kereid works fine for me now. closing it

**Comment by kereid** [comment]
@lbesnard Sorry hadn't got a chance to check this. It still fails on systest for me does it need to be pushed onto there still?

**Comment by lbesnard** [comment]
I dunno. I imagine it should have been on systest already. Can you ask a dev please ?

**Comment by dnahodil** [comment]
I would have thought it would be on systest now. I don't have time to look into it at the moment, though. Another bored developer, might :)

**Comment by smancini** [comment]
It seems to work properly now.
