### ISSUE TITLE
talend aatams sattag dm issue on prod

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#117]
@xhoenner  asked me to check something for the AATAMS SATTAG DM harvester because of data not being processed.

There is no difference in the databags between the RC and PROD version. The data download and process points to :
```
 "archived_folder": "#{node['talend']['data2_rw']}/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_dm/zipped"
```

But, looking at the actual data folder on both env:

NSP14
ll /mnt/ebs/data/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_dm/zipped
all files have a __talend group:user__

NSP10
ll /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_dm/zipped
all files have a __po group:user__

I'm a bit puzzled why it doesn't point to the same location (even though I understand that if both RC and prod would run at the same time on the same folder, it would be conflictual).

Anyway, the __PROD__ harvester is failing ( and this is not picked up by nagios) because of permission issue. The RC one is not.

The group and user for all the zip files were  1019  2306 ( so I guess unknown) before I changed them
```
projectofficer@10-nsp-mel:/mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_dm/zipped$ ll
total 271648
drwxrwsr-x 2 1019  2306     2048 May  6 21:49 ./
drwxrwsr-x 4 1025 users     2048 Feb 24 13:05 ../
-rw-rw-r-- 1 1019  2306  4279851 Jan 24 17:42 ct100.zip
-rw-rw-r-- 1 1019  2306  4968637 Apr  3 15:51 ct101.zip
...
```
​
I changed everything to po:po but the PROD harvester is still failing 

```

talend_log aatams_sattag_dm-aatams_sattag_dm​
...
mirror: /mnt/imos-t4/IMOS/archive/eMII/TALEND_harvester/AATAMS/aatams_sattag_dm/zipped/ct115.zip: Permission denied
```

@danfruehauf do you have any idea about this permission and user issue

**Comment by xhoenner** [comment]
@danfruehauf looks like this is still an outstanding issue, did you have a look at that?

**Comment by danfruehauf** [comment]
I haven't looked into that at all. However before even looking into that, bear in mind that on 14-nsp-mel the `data2_rw` directory is `/mnt/ebs/data`.

On 9-nsp-mel `data2_rw` is `/mnt/imos-t4`. So not sure what we are trying to achieve here, but it's looking at some different sets of files.

**Comment by xhoenner** [comment]
Yes I saw that and to me that's not an issue, it was more @lbesnard who was surprised about that.

Here's a copy of the log for the aatams_sattag_dm harvester on 9-nsp, looks like it's a permission issue. For some reason the harvester doesn't have that permission issue on 14-nsp.

![screen shot 2015-08-04 at 4 51 02 pm](https://cloud.githubusercontent.com/assets/3443821/9054916/2915bc7e-3ac9-11e5-8a80-ae7aae107316.jpg)

Also on a side note: would it be possible to flag 'Permission denied' as errors in Nagios so that this kind of errors can be noticed more easily?

**Comment by danfruehauf** [comment]
@xhoenner can do. However it's a bit on the "ugly" side. I'd personally like to see harvesters report errors in a consistent way.

Regarding this, does the harvester needs write access to those files? If so, it's up to you to maintain correct permissions on those directories and/or files. It seems that the harvester does have read access though.

**Comment by xhoenner** [comment]
> I'd personally like to see harvesters report errors in a consistent way.

Happy to deal with that in the harvester but not sure how to get Talend to flag that as an error, any idea?

> does the harvester needs write access to those files? If so, it's up to you to maintain correct permissions on those directories and/or files. It seems that the harvester does have read access though.

can you show me how to change that so that I can do that myself in the future?

**Comment by xhoenner** [comment]
This was due to a privilege issue, it's been fixed now.
