### ISSUE TITLE
portal - catami layer  empty

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#119]
What is the use of this layer ?
Collaborative and Automated Tools for the Analysis of Marine Imagery (CATAMI) Project 

found under the auv platform ,

@smancini  @atkinsn

**Comment by kereid** [comment]
@lbesnard I have been liaising with Luke on this one and currently there is an issue with the catami geoserver. Once they have fixed this issue they need to implement a new mount point for data, this is low in their list of priorities although they do aim to support Catami in the foreseeable future. At this time they cannot give a resolution date. Luke is ok if we take it off and re-add it back later I just hadn't had the chance to speak with anyone about it yet as it wasn't urgent on my list as it has been like this for over 2 months and hadn't been picked up except by me.

**Comment by lbesnard** [comment]
Thanks @kereid. I hope to be wrong, but I'm not too surprised and I'm pretty sure this will never be added back to 123. Will see

@atkinsn do you want to remove it from the backharvest and unpublish the record so it stays somewhere in your spreadsheet ? I can do it otherwise

**Comment by atkinsn** [comment]
I have unpublished the record from 123, so it won't show up anymore @lbesnard

**Comment by kereid** [comment]
Thanks, I've informed Luke.

**Comment by dnahodil** [comment]
Thanks, all
