### ISSUE TITLE
IMOS - SRS Bio-optical database of Australian Waters (SRS-OC-BODBAW) Sub-Facility has Data on Land

### ISSUE THREAD

**Issue by kereid** [aodn/content#121]
In Production, RC and systest.

Steps to reproduce:

Add IMOS - SRS Bio-optical database of Australian Waters (SRS-OC-BODBAW) Sub-Facility to the map

Select Cruise identifier KS022008 and zoom in to where data is - look to the left (inland) of the data that appears in the water.

What should happen:

Just see white land and no data

What does happen:

See a data point on the land.

**Comment by lbesnard** [comment]
@kereid fixed the data ! took some time
