### ISSUE TITLE
Java heap space error for Argo harvester on 9 and 14-nsp

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#123]
Here's below the copy of the log.

![screen shot 2015-08-06 at 10 31 06 am](https://cloud.githubusercontent.com/assets/3443821/9101139/4e769106-3c26-11e5-9445-d8e0f28f87a5.jpg)

Not sure whether it's related or not but the `argo_float` view is empty. When digging in a bit more, I found that this view is empty due to the `platform_metadata_current` view, which also has 0 record. In the latter view it seems to me that the problem lies in the join between the `indexed_file` and `index_job` table. Any idea what needs to be done @jonescc? I might need to raise that issue as a VIT as it impacts the data reporting.

**Comment by jonescc** [comment]
Well we could increase the heap space limit (its on the job options tab in talend), but would be good to check the indexing component to see why it's using so much.

**Comment by danfruehauf** [comment]
Alternatively, we can start using a per-file approach for indexing things :)

**Comment by jonescc** [comment]
Yes, this problem would go away at least.  Not quite there yet though are we?

**Comment by danfruehauf** [comment]
I think you'll be surprised if I showed you what bits of infrastructure are already in place...

**Comment by xhoenner** [comment]
@jonescc what about the empty views? Would you mind having a quick look at these and advise what needs to be done?

**Comment by jonescc** [comment]
Its related to the heap space error.  One of the supporting views joins using the job run number which has been incremented but no files indexed for it because of the error.

**Comment by xhoenner** [comment]
Thanks @jonescc for looking into that, I'll modify the harvester by increasing the heap space limit and see if that makes a difference.

**Comment by xhoenner** [comment]
I increased the heap space limit from 2048 to 4096 in the Argo harvester (see https://github.com/aodn/harvesters/pull/262) and now got a new error on 14-nsp: java.lang.OutOfMemoryError: GC overhead limit exceeded. @danfruehauf , @jonescc shall I increase the Xmx to 8192?

![screen shot 2015-08-07 at 2 36 20 pm](https://cloud.githubusercontent.com/assets/3443821/9128949/28427542-3d14-11e5-8bc6-5b34a2f0446e.jpg)

**Comment by danfruehauf** [comment]
@jonescc might be able so shed more light on that, practically we don't have that much memory on 9-nsp-mel I think :)

And another thing - if you post code snippets, better if you copy/paste them as text rather than use a screenshot. That way if we need to, we can copy/paste from it.

**Comment by jonescc** [comment]
@xhoenner, can you get @pblain to add a VIT for this.  We need to get to work out what underlying problem is here. Doesn't make sense that all of a sudden twice as much memory isn't enough.

**Comment by danfruehauf** [comment]
@xhoenner @jonescc Looks like this stems from argo trying to copy a `.snapshot` directory with A LOT of files from ifremer. In other words, ifremer made their snapshot directory available (suddenly) and we now try to pull many more files. Not to mention the *actual* rsync failed in the last couple of weeks twice.

So I'm going to see how big this directory actually is, then delete it and rerun the harvester.

**Comment by danfruehauf** [comment]
I think that's the problem. Harvester is running now and it not complaining about lack of memory.

Files in `dac` - 1581541
Files in `.snapshot` - 10559738

**Comment by danfruehauf** [comment]
@xhoenner If you want we can revert the memory increase for argo, but up to you.
