### ISSUE TITLE
Can't filter on project name for Argo layer on production portal

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#126]
It says 'No options available', see screenshot below.

![screen shot 2015-08-13 at 12 00 01 pm](https://cloud.githubusercontent.com/assets/3443821/9241174/3f58e40c-41b3-11e5-8f7e-ce44fd619eab.jpg)

**Comment by danfruehauf** [comment]
Related to:
https://github.com/aodn/aodn-portal/issues/1849

It's a pure portal bug, not content :)

**Comment by danfruehauf** [comment]
I'll close that since there is a portal issue for that already.
