### ISSUE TITLE
Ocean Colour gridded products from Rob Johnson are not working from CSIRO ncWMS server

### ISSUE THREAD

**Issue by smancini** [aodn/content#127]
4 layers are unavailable from the CSIRO ncWMS server maintained by Edward King.
I have unpublished these 4 datasets collection so that portal user cannot access them.
I have contacted Edward but he is on leave until Tuesday the 18th of August.

**Comment by danfruehauf** [comment]
Just removed the MOTD.

**Comment by smancini** [comment]
Edward King fixed the issue on Friday.
I have re-published these 4 datasets collection and they seem to work fine on production.
