### ISSUE TITLE
Argo - filters empty

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#130]
See: https://github.com/aodn/aodn-portal/issues/1849
The issue is using virtual views in Geoserver is not reliable and they should not be used. 
See the issue description and the last few comments on aodn-portal/issues/1849 for more information

**Comment by kereid** [comment]
@smancini could you please get someone to take a look at resolving this - it is occurring more and more frequently

**Comment by kereid** [comment]
Not sure why but I can see platform and project filter dropdowns in systest now but not platform in production - can see project though. If they both point to the same geosever.

**Comment by smancini** [comment]
Laurent is going to look at it next week when he is back from holiday.
