### ISSUE TITLE
Mini-map not representative of what is shown on step 2

### ISSUE THREAD

**Issue by kereid** [aodn/content#131]
Seeing in Prod and Sys-test

Steps to reproduce:

Narrow down results by selecting Moorings and Buoy. Proceed to last page of results and look at mini-map of collection IMOS - Australian National Mooring Network (ANMN) - Wave time-series

![minimap](https://cloud.githubusercontent.com/assets/2906602/9647813/2e5a036c-5224-11e5-87b1-017d4a40b402.jpg)

Add collection to map when taken to step 2 look at bigmap

![bigmap](https://cloud.githubusercontent.com/assets/2906602/9647815/3a890494-5224-11e5-971e-e374efcc1b18.jpg)

What does happen:

They are different

What should happen:

They should be the same

**Comment by kereid** [comment]
@bpasquer has confirmed with me that the mini-map is reflective of Manly Hydraulics schema - also the same issue is occurring with Royal Australian Navy (RAN) - CTD profiles in RC

**Comment by mhidas** [comment]
@kereid I would guess this is a harvester issue - one or more of the harvesters involved are updating the spatial extent in the wrong metadata record!

**Comment by bpasquer** [comment]
@mhidas I checked ran_ctd, the  default context is ok, but not the deployment context. The issue can be solved by correcting the deployment context parameter  .

**Comment by mhidas** [comment]
@bpasquer When harvesters run in production, the values of the context parameters come from the data bags, not from within the Talend project, so that's the place to check. To avoid confusion, however, I think it is a good idea to set the values correctly in both places.

**Comment by mhidas** [comment]
Here's the problem: https://github.com/aodn/harvesters/issues/283
Probably similar for ANMN Wave as well.

**Comment by smancini** [comment]
Works fine now
