### ISSUE TITLE
Misconfigured metadata - MCP 2.0: HARVESTING TEMPLATE - THREDDS - UNIDATA DISCOVERY

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#135]
In the record
https://catalogue-123.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=77492beb-5a34-4e1a-90b6-2116d770a07d

There is a bad reference:
```
    <gmd:MD_DigitalTransferOptions>
        <gmd:onLine xmlns:srv="http://www.isotc211.org/2005/srv" id="thredds.online.resources">
            <gmd:CI_OnlineResource>
                <gmd:linkage>
                    <gmd:URL>http://localhost:8123/geonetwork/srv/en/metadata.show?uuid=4294e6ae-9c7c-462f-a7c5-6cbe0a7c8b90</gmd:URL>
                </gmd:linkage>
                <gmd:protocol>
                    <gco:CharacterString>WWW:LINK-1.0-http--metadata-URL</gco:CharacterString>
                </gmd:protocol>
                <gmd:description>
                    <gco:CharacterString>Point of truth URL of this metadata record</gco:CharacterString>
                </gmd:description>
            </gmd:CI_OnlineResource>
        </gmd:onLine>
    </gmd:MD_DigitalTransferOptions>
```

Notice the link:
```
http://localhost:8123/geonetwork/srv/en/metadata.show?uuid=4294e6ae-9c7c-462f-a7c5-6cbe0a7c8b90
```

**Comment by atkinsn** [comment]
This is a template, not a metadata record, so not a big deal - I think @jonescc would be best to comment on it.

**Comment by jonescc** [comment]
As @atkinsn says, this is a template record which can be used as a template for creating real metadata records.  Perhaps we should ignore template records, they probably shouldn't be forced to point to real services.  Not sure how you're searching for records Dan, but in the database these records are marked with istemplate='y'.

Having said that, we don't use the MCP2.0: HARVESTING TEMPLATE THREDDS - its for creating metadata for thredds datasets when harvesting thredds catalogs.   We can also just delete it.

**Comment by danfruehauf** [comment]
I still need to tweak this function, here it is:
https://github.com/aodn/core-geonetwork/pull/41/files#diff-83a38cf7ac5b5fe2c9418d810042c3feR60
