### ISSUE TITLE
report_test schema cannot be backed up

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#137]
What is the `report_test` schema? Why is it part of our production DB? Is it a test schema?

The DB backup fails because of permissions on this **test** schema and I don't even know who did what and when on it.

**Comment by danfruehauf** [comment]
It is fixed with:
```
harvest=# GRANT select on all tables in schema report_test to "backup";
harvest=# GRANT select on all sequences in schema report_test to "backup";
```

But I still want to understand why I need to chase my tail regarding those things.

**Comment by xhoenner** [comment]
This schema is for me to test out the SQL queries used to generate the data reports. I wasn't aware that permission had to be added for the backup to succeed, I'll modify my scripts accordingly, sorry about that.

**Comment by danfruehauf** [comment]
@xhoenner Please resolve that ASAP.

This is an operational problem with obvious and severe consequences - no backups. I don't want it reoccurring again in production.

**Comment by xhoenner** [comment]
You'll have to fix that up for me @danfruehauf as I've got tomorrow off. I thought I had added grant privileges to 'backup' in all my report_test queries but I must have omitted that somewhere. Sorry about the inconvenience.

**Comment by xhoenner** [comment]
I fixed that up Dan, it was due to the old reporting queries that didn't have these grant privileges, should be all good now.

**Comment by danfruehauf** [comment]
Thanks!
