### ISSUE TITLE
ANMN layers misleading legend

### ISSUE THREAD

**Issue by dnahodil** [aodn/content#143]
_Migrated from https://github.com/aodn/aodn-portal/issues/2033_

**Steps to reproduce:**
Add any of the following collections

IMOS - Australian National Mooring Network (ANMN) Facility - Current velocity time-series
IMOS - Australian National Mooring Network (ANMN) Facility - WQM and CTD burst averaged data products
IMOS - SRS Satellite Altimetry Calibration and Validation Sub-Facility
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time meteorology and sea surface temperature
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time water quality
IMOS - ABOS Southern Ocean Flux Station (SOFS) - Surface properties (delayed mode)
IMOS - ANMN National Reference Stations - Maria and North Stradbroke Islands - Near real-time wave height

On step 2 look at the layer tab

**What should happen:**
Symbol has a label indicating location of mooring or that it is a mooring?

**What does happen:**
They all say Phytoplankton location

@mhidas perhaps you can comment on this one too?

**Comment by mhidas** [comment]
In the prod portal those layers all use the "red square" symbol, labelled "RedSquare". This is of course not very informative, and should be fixed, but that's another issue.

I guess this issue was seen on portal-rc? I tried to look there but currently it shows zero collections...

Sorry I can't say anything more helpful. If the labels for those symbols changed to phytoplankton, it had nothing to do with me.

**Comment by dnahodil** [comment]
It is visible on portal-systest (http://portal-systest.aodn.org.au/imos123/home?uuid=8964658c-6ee1-4015-9bae-2937dfcc6ab9). The GeoServer on systest should have the same configuration as prod so we might need to have a look into that.

On prod they are still RedSquare which, as we've said, is not great but isn't really a *problem*.

**Comment by pmbohm** [comment]
There are **WAY** too many layers using the point styling. The following is the point.xml
```
<style>
  <id>StyleInfoImpl--3a52b6b4:1428ce0125d:-8000</id>
  <name>point</name>
  <sldVersion>
    <version>1.0.0</version>
  </sldVersion>
  <filename>default_point.sld</filename>
</style>
```
The **131 layers** using the point ID here:
https://github.com/aodn/geoserver-config/search?utf8=%E2%9C%93&q=StyleInfoImpl--3a52b6b4%3A1428ce0125d%3A-8000

**Comment by pmbohm** [comment]
There are two styles using the same id, which for Geoserver is a big nono.
Maybe this happened by directly copying the default_point.sld ? @lbesnard 
![screen shot 2015-11-24 at 3 52 30 pm](https://cloud.githubusercontent.com/assets/1066981/11358123/792302e2-92c3-11e5-817c-4e0a165da605.png)
![screen shot 2015-11-24 at 3 55 31 pm](https://cloud.githubusercontent.com/assets/1066981/11358173/0a5d97f4-92c4-11e5-9250-16bfc930d7ba.png)

**Comment by smancini** [comment]
Fixed by recent work done by Xavier
