### ISSUE TITLE
Time filtering doesn't work on RLS layer

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#144]
<h3> Steps to reproduce <h3>

Go to https://imos.aodn.org.au/imos123/home?uuid=9c766140-9e72-4bfb-8f04-d51038355c59
Subset by temporal extent, *e.g.* To 2012/10/15

<h3> What happens <h3>

Yellow warning sign next to layer name, no features on the map anymore.

<h3> What should happen <h3>

Layer should get filtered.

**Comment by danfruehauf** [comment]
It's coming from http://.geoserver-rls.imas.utas.edu.au - their geoserver might be misconfigured. But I haven't looked deep into that.

**Comment by xhoenner** [comment]
This is now working
