### ISSUE TITLE
Passive Acoustic data has no filter

### ISSUE THREAD

**Issue by pblain** [aodn/content#147]
![image](https://cloud.githubusercontent.com/assets/2802359/10872057/e9de34a2-814d-11e5-843e-c7d67de5168b.png)

**Comment by mhidas** [comment]
@pblain That's because there's no data to download. This is really just a layer showing where the passive acoustic observatories are. The data are accessed via the Acoustic Data Viewer.

**Comment by pblain** [comment]
Yes, I think we've discussed it before. But it still looks like an error in the system.  The messages says "not at this time" which implies that it may work at some other time.

**Comment by dnahodil** [comment]
Things have changed a bit since that message was written. It is also misleading in some cases because geographic filtering might work for a collection, but you will still see that message. So we might need to reconsider the wording for that.

**Comment by mhidas** [comment]
There is now a new Passive Acoustics layer which does have filters (though a bit pointless because there's still no data to download).

@pblain If the wording of the "no filtering available" message is still considered an issue, it should be reported elsewhere.

**Comment by pblain** [comment]
@mhidas If the data is accessed via the acoustic data viewer then there should at least be a link to it on Step 3.  It would be even better if users could download the data via the portal.  The reason we moved to the 123 portal was to eliminate the frustration caused by showing users data with no obvious means to download it.  So Step 3 must always provide access to the data - even if it's a link to something like the acoustic data viewer.  Either that or remove the data collection altogether.  It would be annoying to go through the rigmarole of searching for this on step 1, filtering on step 2 - only to find that you can't download anything.

**Comment by mhidas** [comment]
@pblain I agree there should be a link to the acoustic data viewer on step 3. The link is in the metadata record, so can be seen under the "Info" tab in Step 2. How can we make that appear on Step 3 as well?

As for your other points, I'm not sure it would be practical to download the passive acoustic data via the portal. A single data set is about 120Gb, and people usually want multiple sets, if not the entire collection (currently 5Tb). Even the data viewer only gives a preview and allows you to download individual recordings (~6Mb) as a sample. The best way to get the whole data set is to send us a drive.
So maybe we could also add a note to this effect in Step 3, along with a link to info@emii.org.au (as I have done in the GFI box).

**Comment by mhidas** [comment]
The other thing I've thought we could do with this collection is allow the download of the metadata in CSV form. It's already in the database, and some of it is needed for processing the raw data.

**Comment by pblain** [comment]
@mhidas - @atkinsn should be able to help you with the metadata so that the link shows in step 3.

The CSV/metadata download idea sounds like a possibility.  Would that include URL links to the data?

**Comment by atkinsn** [comment]
I was just having a look at this. It appears that less of the links are appearing in Step 3 - not sure when that changed...
And that link is currently in the metadata record in distribution, but as I just flagged, it is no longer showing in step 3. What are the rules in regards to protocols that show up in step 3 @pblain ??

**Comment by atkinsn** [comment]
This link was available in May of last year.
![scrollbar](https://cloud.githubusercontent.com/assets/4187605/12315160/27566536-bacc-11e5-8d4e-dce7fbda2fdf.jpg)

**Comment by pblain** [comment]
Don't know why it was changed.  I'll add it as a bug.
