### ISSUE TITLE
talend aatams_acoustic_reporting jams the DB

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#148]
This is the query that seems to take forever:
```
SELECT "pkid","detection_id","project_name","installation_name","station_name","bottom_depth","common_name","transmitter_id","relea
se_date","release_locality","detection_date","longitude","latitude","sex","scientific_name",encode(ST_AsEWKB("geom"),'base64') as "geom","detected","r
eceiver_name" FROM "dw_aatams_acoustic"."aatams_acoustic_detections_data" LIMIT 1
```

The harvester is running and this query is also ran in front of geoserver-rc, which uses the same DB the harvester probably does. Will need more investigation, but until then, I suggest to not run that harvester.

**This will affect users using the portal as it denies service**

**Comment by xhoenner** [comment]
Not sure this is where the issue lies @danfruehauf, running this query on both dbprod and rc returned data in less than 50ms. The issue might only appear when the harvester is truncating/populating this table, which takes a lot of time as it needs to insert over 60 million rows. 

We need that harvester to run for reporting purposes though.

**Comment by xhoenner** [comment]
I can't actually find any of the dw_aatams_acoustic layer on geoserver-rc. @ggalibert merged https://github.com/aodn/geoserver-config/pull/298 last week but that doesn't seem to have been deployed to geoserver-rc. Would you mind double checking that please @danfruehauf ?

**Comment by danfruehauf** [comment]
@xhoenner I won't have time to look at that today.

I understand that harvester has to run, I'm just saying that the implications of having this reporting is big downtime for users.

**Comment by xhoenner** [comment]
@danfruehauf I still can't see any of these layers on geoserver-rc, would you mind having a look at that please @danfruehauf?

**Comment by danfruehauf** [comment]
You mean this layer:
https://nagios.aodn.org.au/cgi-bin/nagios3/extinfo.cgi?type=2&host=3-nec-mel.emii.org.au&service=geoserver+wfs%3Aimos%3Aaatams_acoustic_detections_data

It is down for already almost 4 days...

**Comment by xhoenner** [comment]
Yes that's the one I'm talking about, it has been down for 4 days because it can't be find on geoserver-rc for some unknown reasons...

**Comment by danfruehauf** [comment]
I'm pretty sure it's in the data directory. Otherwise it wouldn't have been monitored... Can refresh GS config, but, still, it's not the core of the problem here.

**Comment by xhoenner** [comment]
well there's definitely data in the table used by the aatams_acoustic_detections_data layer so I'm really not sure how I can get anything done from my end. Yes, please reload Geoserver rc and let me know once that's done.

**Comment by danfruehauf** [comment]
Reloaded, still a problem...

**Comment by xhoenner** [comment]
Might have been because I misconfigured the store JNDI ref name (https://github.com/aodn/geoserver-config/pull/299), would you mind reloading Geoserver-rc again @danfruehauf?

**Comment by danfruehauf** [comment]
Need a chef run for that, in progress.

**Comment by xhoenner** [comment]
it's definitely going to work now!

**Comment by danfruehauf** [comment]
It does work.

But that doesn't quite solve the problem I raised just yet...

**Comment by xhoenner** [comment]
Okay, shall we then try to re-run this harvester on rc and see if the same problem occurs?

**Comment by danfruehauf** [comment]
I'd like to verify this query can also run quickly, as well. Maybe I'm still barking up the wrong tree, but I'm pretty sure this query got stuck for a while...

**Comment by xhoenner** [comment]
It's likely to have been stuck for a while when the harvester was running as it truncates and populates that table with more than 50 million entries. Please re-test and advise what needs to be done.

**Comment by danfruehauf** [comment]
I'll trigger it then.

**Comment by danfruehauf** [comment]
This is run by the harvester:
```
SELECT "pkid","detection_id","project_name","installation_name","station_name","bottom_depth","common_name","transmitter_id","release_date","release_locality","detection_date","longitude","latitude","sex","scientific_name",encode(ST_AsEWKB("geom"),'base64') as "geom","detected","receiver_name","embargo","registered","embargo_date" FROM "dw_aatams_acoustic"."aatams_acoustic_detections_data" LIMIT 1;
```

Takes very long to even get an `EXPLAIN` on that.

**Comment by danfruehauf** [comment]
Sorry, ran by geoserver, and it's pretty"jammed".

This is the query ran by the harvester:
```
SELECT DISTINCT vd.id AS detection_id,  p.name AS project_name,         i.name AS installation_name,    ist.name AS station_name,       vd.receiver_name,       rd.bottom_depthm AS bottom_depth,       CASE WHEN sp.common_name IS NULL THEN 'Unknown'                 WHEN date_part('day', ar.embargo_date - now()) > 0 THEN 'Embargoed'             WHEN date_part('day', ar.embargo_date - now()) < 0 OR ar.embargo_date IS NULL THEN sp.common_name END AS common_name,   vd.transmitter_id AS transmitter_id,    CASE WHEN ar.releasedatetime_timestamp AT TIME ZONE 'UTC' IS NULL THEN NULL             WHEN date_part('day', ar.embargo_date - now()) > 0 THEN NULL            WHEN date_part('day', ar.embargo_date - now()) < 0 OR ar.embargo_date IS NULL THEN ar.releasedatetime_timestamp AT TIME ZONE 'UTC' END AS release_date,         CASE WHEN ar.release_locality IS NULL THEN 'Unknown'            WHEN date_part('day', ar.embargo_date - now()) > 0 THEN 'Embargoed'             WHEN date_part('day', ar.embargo_date - now()) < 0 OR ar.embargo_date IS NULL THEN ar.release_locality END AS release_locality,         vd.timestamp AT TIME;
```

**Comment by xhoenner** [comment]
Very well, how about I deactivate the corresponding subjob and you try and re-run this harvester?

**Comment by danfruehauf** [comment]
Can do. Is that a change you've just recently introduced?

**Comment by xhoenner** [comment]
Yes it is but that's fine I can do without it for a while, the main thing is to be able to run the reporting queries. https://github.com/aodn/harvesters/pull/324 should solve this issue.

**Comment by danfruehauf** [comment]
geoserver-rc down again. I'm pretty sure it's because of the harvester...

**Comment by xhoenner** [comment]
Well I've deactivated the subjob responsible for updating the geoserver layers so now the harvester shouldn't interfere with Geoserver. Do you mind @danfruehauf if I try running it again?

**Comment by danfruehauf** [comment]
Go for it. I was about to ask if you want it pushed to prod. I think it ran fine last time (08/11/2015).

**Comment by xhoenner** [comment]
Worked on rc and prod (https://nagios.aodn.org.au/cgi-bin/nagios3/extinfo.cgi?type=2&host=10-nsp-mel.emii.org.au&service=talend+aatams_acoustic_reporting).

**Comment by danfruehauf** [comment]
:+1:
