### ISSUE TITLE
SRS SST L3S 01 day fails with GoGoDuck

### ISSUE THREAD

**Issue by dnahodil** [aodn/content#149]
There are some harvester changes that need to be made as the timestamps in the ` 	srs_sst_l3s_1d_day_gridded_url ` layer which are preventing GoGoDuck from behaving correctly. Other layers might be affected, too.

I got @lbesnard to check this out and his findings were:
* The harvester reads the `time_coverage_start` variable where it should really use `time`
* The database view *might* have a problem with whether the column is defined as UTC (the table is fine) we'll need to check this

This is the cause of the problem @rogerproctor mentions here: https://github.com/aodn/aodn-portal/issues/2052

**Comment by dnahodil** [comment]
This problem affects all the layers in that schema.

We will disable the data collections in the Portal until the problem is rectified.

**Comment by dnahodil** [comment]
@lbesnard were you planning on showing these layers at BoM or in your workshops/presentations this week?

**Comment by danfruehauf** [comment]
Solved?
