### ISSUE TITLE
Empty database views for Argo

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#151]
### To reproduce
Connect to dbprod, argo schema.

### What does happen:
`argo_float` and `platform_metadata_current` views are empty, which doesn't impact the WFS and WMS but does impact the data reports.

### What should Happen
Those views should have data in. @jonescc I believe we experienced the same issue a few months ago, this is likely due to a discrepancy between index_job.last_run_no and indexed_file.last_indexed_run.

**Comment by danfruehauf** [comment]
Mhhhm. That is... not the actual data that users get, right?

Argo is being incrementally updated now, every week. Only modified/deleted files are changed in DB. Must be related to that.

**Comment by xhoenner** [comment]
> Mhhhm. That is... not the actual data that users get, right?

Yes that's correct, AFAIK these views are only used for reporting. They basically provide a metadata summary for each Argo float. 

Hmm I see, so what you're saying is that those two views are now obsolete, right? Is there a plan to maintain/reconfigure these now that the harvester is event driven?

**Comment by danfruehauf** [comment]
I didn't say obsolete, was just mentioning the reason that this happened. If they need to work, we can probably make them work, I suppose.

Either way, I'm not the right person to to shed more light on that. Maybe @jonescc ?

**Comment by xhoenner** [comment]
@pblain this needs to be raised as a VIT as it will impact the data reports for Argo. Could you please add a ticket on the board?

**Comment by pblain** [comment]
This will be in the next iteration - so no need for a VIT.

**Comment by jonescc** [comment]
The views were broken when we migrated to pipeline processing.

Previously you used the following to identify all current files harvested by the harvester in sql

```
select file.id
   from indexed_file file
    join index_job job
      on file.job_id = job.id
    and file.last_indexed_run = job.last_run_no
```

As all 'current' files were indexed when running a harvester

After moving to pipeline processing, only files specified in the manifest are indexed when running the harvester and so the above won't work to identify all files

Instead, the following should be used:

```
select file.id
   from indexed_file file
    join index_job job
      on file.job_id = job.id
    and not file.deleted
```

The relevant views that need to be fixed in the argo harvester are:

**best_cycle_location**

Change

```
   FROM argo.profile_general profile
     JOIN argo.indexed_file file ON file.id = profile.file_id
     JOIN argo.index_job job ON job.last_run_no = file.last_indexed_run
```

To

```
   FROM argo.profile_general profile
     JOIN argo.indexed_file file ON file.id = profile.file_id AND not file.deleted
```

**platform_metadata_current**

Change

```
   FROM argo.platform_metadata
     JOIN argo.indexed_file file ON file.id = platform_metadata.file_id
     JOIN argo.index_job job ON job.last_run_no = file.last_indexed_run;
````

To

```
   FROM argo.platform_metadata
     JOIN argo.indexed_file file ON file.id = platform_metadata.file_id AND not file.deleted;
````

**Comment by xhoenner** [comment]
@jachope this hasn't been implemented yet so no need to produce the reports for Argo for now.

**Comment by danfruehauf** [comment]
@xhoenner @lbesnard Is @jonescc response enough information to implement the reporting?

**Comment by xhoenner** [comment]
@lbesnard needs to modify the Argo harvester for the reporting to work.

**Comment by lbesnard** [comment]
https://github.com/aodn/harvesters/pull/331
