### ISSUE TITLE
GetFeatureInfo miss hits

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#154]
https://github.com/aodn/aodn-portal/issues/2053 reports that the GetFeatureInfo request is very hard for the user to get back a response.
Specifically the bug reports that Argo and Soop collections are a problem. There may be more collections afftect by the same issue.
### The problems

1) The portal uses a buffer parameter to Geoserver of 10px which is far greater than the default 4px. Increasing this value cause a server slow down and mostly does not solve the problem. So that value will remain at 10px.
2) The layer styles are having an impact when the size of points are too small.
3) The **SLD's should always be validated** in case this also causes issues like the problem described here.
#### The proposed solution for Argo

Adding a new very opaque style rule for every point makes a big difference. (Full file attached)
[argoBufferedStyle.sld.txt](https://github.com/aodn/content/files/41319/argoBufferedStyle.sld.txt)

```
            <PointSymbolizer>
              <Graphic>
                <Mark>
                  <WellKnownName>circle</WellKnownName>
                  <Fill>
                    <CssParameter name="fill">#EFEFEF</CssParameter>
                    <CssParameter name="fill-opacity">
                        <ogc:Literal>0.05</ogc:Literal>
                    </CssParameter>
                  </Fill>

                </Mark>
              <Size>5</Size>
            </Graphic>
          </PointSymbolizer>
```
### What needs to happen

All layer styles should include opaque styling rules or larger sizes to ensure a hit for GFI requests for end users.

**Comment by danfruehauf** [comment]
@pmbohm Close?

**Comment by danfruehauf** [comment]
@pmbohm Ah sorry. Leave open, thought it's the depth service not returning info thing.

**Comment by mhidas** [comment]
> 1) The portal uses a buffer parameter to Geoserver of 10px which is far greater than the default 4px. 

@pmbohm Does that mean any feature falling within 10 screen pixels of the click point should be selected? That seems plenty enough to me, but at least in the NOAA drifters layer (#188) I'm clicking well within that buffer and still not getting any features found.

**Comment by pmbohm** [comment]
According to the docs we are doing all the right things.
http://docs.geoserver.org/stable/en/user/services/wms/vendor.html?highlight=getfeatureinfo#buffer
I agree there seems to be an issue after trying to help @lbesnard yesterday

**Comment by pmbohm** [comment]
@mhidas Loz was actually working on the same NOAA layer and now has the answer. Basically a rule for a wide opaque line stroke before a rule for the bold line itself works

**Comment by mhidas** [comment]
@pmbohm Thanks, if it does the trick, that's ok. It just looks to me like a work-around rather than a proper solution.

**Comment by lbesnard** [comment]
> It just looks to me like a work-around rather than a proper solution.

it's exactly it. not really happy with this either

**Comment by xhoenner** [comment]
More of a portal/Geoserver issue as it's applicable to every layer that doesn't have this workaround

**Comment by xhoenner** [comment]
@pblain feel free to open this as a new issue in whichever repo is the most appropriate.

**Comment by pblain** [comment]
Not sure what other repo to open this in until someone suggests an alternative solution. I'll look into it and see if it can be solved in another way, but I'd appreciate any suggestions. In the mean time I'll re-open it in this repo until @pmbohm returns from sick leave and has a chance to comment. I don't want to just close it and lose track of it.
