### ISSUE TITLE
ACORN reprocessed files

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#155]
ACORN sometimes upload new radials which should overwrite radials that were already uploaded. If the flow is undisturbed and the files are processed in order, it should all be good, as the newer file will overwrite the older file.

However in some situations where files are put in error directory and then processed (regardless of what reason caused it), potentially a "newer" file can be overwritten by an older version. For instance:
 * File version 1 is being uploaded and put in error directory (file is correct but maybe there was an error in the environment)
 * File version 2 is uploaded and processed successfully + served to users
 * File version 1 is looked at, moved back to incoming directory and gets processed
 * File version 2 is overwritten by file version 1

I suggest this can be fixed by applying more intelligent logic when processing radials. That is, check to see if a radial with the same name already exists, and if it does decide which is the newer one and act accordingly.

This is generally a low priority task, but it has to be documented so we are aware of it.

**Comment by mhidas** [comment]
This will need to be considered for ANMN too, and probably for other facilities where re-processing can happen.

**Comment by danfruehauf** [comment]
@mhidas I gonna have a crack at implementing that. It shouldn't be that difficult...

**Comment by danfruehauf** [comment]
Solved by https://github.com/aodn/data-services/issues/276 - implemented in production.
