### ISSUE TITLE
Sensors on Tropical Research vessels has data on land 

### ISSUE THREAD

**Issue by kereid** [aodn/content#156]
Steps to reproduce:

Add Sensors on Tropical Research Vessels: Enhanced Measurements from Ships of Opportunity (SOOP) to the map, taken to step 2

What should happen:

Data should only be over water

What does happen:

Long line of data across QLD and NT

**Comment by lbesnard** [comment]
@kereid  can you still see this ? I try to zoom in and don't see anything

**Comment by lbesnard** [comment]
http://geoserver-123.aodn.org.au/geoserver/imos/wms?service=WMS&version=1.1.0&request=GetMap&layers=imos:soop_trv_trajectory_map&styles=&bbox=113.55394,-28.89236,151.9239,-11.39618&width=768&height=350&srs=EPSG:4326&format=application/openlayers

**Comment by smancini** [comment]
Seems to work properly now.
