### ISSUE TITLE
Change AATAMS collection layer name to imply purposes of layer

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#157]
### The issue
*  The `IMOS - AATAMS Facility - Acoustic Tagging Data Repository` collection in the portal exists only to demonstrate locations of receivers and has no data to download
*  The user has no information to tell them that there wont be a download. This only becomes apparent on Step 3
*  Causes confusion

### Possible solution
Change the description of the collection to imply that the layer is for visualisation only and has no data to download

https://github.com/aodn/aodn-portal/issues/2080

**Comment by xhoenner** [comment]
I've now added a WFS service in the corresponding metadata record and tested the download on the portal. 

@atkinsn will chat to @smancini regarding the title and abstract of the metadata record.

**Comment by xhoenner** [comment]
@atkinsn, Seb's happy with the following title `IMOS - Animal tracking - Acoustic Receiver Locations`. Is that okay for you and @jachope?

**Comment by jachope** [comment]
Fine by me - should the 'T'racking' have a capital too?

**Comment by xhoenner** [comment]
Why not, while we’re at it! @atkinsn would you mind making this small change and closing this issue afterwards?

**Comment by atkinsn** [comment]
I will hold off @xhoenner  as we are having a whole metadata chat shortly, and this falls under this bracket too. I had initially only looked at this in regards to the last part of the metadata title: "Acoustic tagging Data repository".

**Comment by atkinsn** [comment]
I will change the name to reflect its purpose, but will retain "AATAMS" for now.

**Comment by xhoenner** [comment]
no worries, thanks for letting me know.
