### ISSUE TITLE
AODN - IMAS SeaMap Layer

### ISSUE THREAD

**Issue by kereid** [aodn/content#16]
There is an issue with one of the IMAS layers - SeaMap. Peter Walsh initially reported this back in December last year, where the portal is requesting authentication on the user side for the layer to be displayed on the map. 

PW is happy for the collection to be shared visibally but not the data.

It was worked in the past and PW thought that PB had initially set it up.

PW Will come to chat with PB sometime in week of 28/04/14

**Comment by smancini** [comment]
Not relevant anymore with the release of a single portal
