### ISSUE TITLE
imos:anmn_acoustics layer does not follow wms naming conventions

### ISSUE THREAD

**Issue by jonescc** [aodn/content#161]
wms layers normally have a _map suffix

**Comment by mhidas** [comment]
@jonescc This is an old layer and will soon be replaced with a new one which will be named correctly.

**Comment by mhidas** [comment]
New layer anmn_acoustics_map is now in place. The old one is still there but can be deleted.

**Comment by danfruehauf** [comment]
@mhidas Can you please submit a PR to delete it then?

**Comment by danfruehauf** [comment]
This should stay open until the layer that does not follow the conventions is deleted.

**Comment by mhidas** [comment]
@danfruehauf If we want to be strict about it, there are a fair few more layers in that category, e.g. all those using the `JNDI_anmn` datastore. None of these are used in the 123 portal. However, several of them are used in the old AODN portal, so we probably shouldn't delete them while that portal is still public.

**Comment by danfruehauf** [comment]
@mhidas This ticket refers to `imos:anmn_acoustics` which still exists - because it wasn't removed. As long as this layer is not removed, this ticket cannot be closed.

As for other layers, I'm not sure what should be the verdict. Hopefully old portal will be removed soon.

**Comment by smancini** [comment]
I agree with Marty. The new layer is following the 1-2-3 naming convention.
The old layer is still available because it is used by the AODN portal as many other layers (e.g.: soop_xbt or xbt_realtime).
I do not think we need to open an issue for each of this layer?
Maybe we can open a separate issue for all these layers used by the AODN portal which will become obsolete hopefully pretty soon.

**Comment by danfruehauf** [comment]
So to understand the flow here, and correct me if I'm wrong:
 * There was a layer with a non conforming name in portal-123
 * A new (and identical) layer was added with `_map` suffix
 * Old layer is still referenced in portal 2 so it cannot be deleted

Is that the case?

**Comment by mhidas** [comment]
@danfruehauf Almost correct, except that the new layer with correct name is **not** identical to the old one.

**Comment by danfruehauf** [comment]
> @danfruehauf Almost correct, except that the new layer with correct name is not identical to the old one.

Ah, gotcha. OK then. Lets close it.
