### ISSUE TITLE
Short Tailed Shearwater tracks over Tassie

### ISSUE THREAD

**Issue by kereid** [aodn/content#163]
Noticed this in systest - then checked prod and rc and they are the same also.

Steps to reproduce:

Add IMOS - AATAMS Facility - Tracking of Short-tailed shearwaters to the map.

Look at track range on step 2

What does happen:

Tracks appear to run right into the middle of Tassie

What should happen:

Don't think the birds would fly that far in...

**Comment by xhoenner** [comment]
Location estimates for shearwaters are calculated from light intensity recorded by archival tags. Computing animal geolocation based solely on sun elevation is quite a complicated statistical process (see the algorithm used here https://github.com/SWotherspoon/SGAT) and is therefore typically associated with accuracies of a few hundred kilometres. In short, using this technology there will always be points on land, even though these are coastal migratory birds.

That being said I did double check that the tracks on the portal were consistent with the original dataset
![shearwater_tracks](https://cloud.githubusercontent.com/assets/3443821/11923825/1b6e975c-a7fd-11e5-9194-da9bbe04a403.jpg)
