### ISSUE TITLE
Simple metadata view displayed by GeoNetwork

### ISSUE THREAD

**Issue by jonescc** [aodn/content#170]
Steps to reproduce:
1. On step one click "more" link for any collection 

2. Add any collection to the map.
On step 2 go to the info tab.
Scroll to Point of truth URL of this metadata record and click

3. Add any collection to the map.
Proceed to step 3 and click "view metadata record"

What should happen:

User taken to Geonetwork and see whole record (MCP All to test MCP is highlighted)

What does happen:

User taken to Geonetwork and only see default view in which record is abbreviated

**Comment by jonescc** [comment]
See https://github.com/aodn/aodn-portal/issues/2099

Can be fixed by @atkinsn as follows:

1. Go to GeoNetwork System Configuration
2. Under Metadata Views, change to Advanced or ISO view.
3. Save

**Comment by atkinsn** [comment]
Changed on all relevant GeoNetwork MESTs. MCP All is now the "default" metadata view.
