### ISSUE TITLE
soop_sst unrecognized ship

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#171]
The following file failed to process - `IMOS_SOOP-SST_ST_20160106T081000Z_VMQ9273_FV01_C-20160107T145044Z.nc`

Possibly a missing ship name (VMQ9273).

**Comment by danfruehauf** [comment]
It's probably this:
http://www.marinetraffic.com/ais/details/ships/shipid:695968/mmsi:503540000/imo:9423463/vessel:SOLANDER

**Comment by lbesnard** [comment]
yeap @danfruehauf , thats it. missing from the dictionnary https://github.com/aodn/data-services/blob/master/SOOP/SOOP_ASF_SST_XBT/soop_asf_sst_pipeline/destPath.py#L9

@smancini @atkinsn  could you please point to the name used by IMOS?

cheers

**Comment by smancini** [comment]
Yes, you can use the name "Solander" as in SOOP-TRV
