### ISSUE TITLE
Our MCP 2.0 metadata does not validate against the MCP 2.0 schema definition

### ISSUE THREAD

**Issue by jonescc** [aodn/content#173]
MCP 2.0 metadata for our 123 collections do not currently validate against the MCP 2.0 schema.

Refer 
[mcp2_validation_report.txt](https://github.com/aodn/content/files/93812/mcp2_validation_report.txt)

**Comment by jonescc** [comment]
Note that the polygon id's errors are the result of the iUpdateSpatialExtent component and will be fixed by https://github.com/aodn/harvest_sql_library/pull/7

**Comment by jonescc** [comment]
Note validation report provided by @julian1.  Thanks @julian1

**Comment by lbesnard** [comment]
@atkinsn can this be closed?

**Comment by atkinsn** [comment]
Sure, problem is mute now
