### ISSUE TITLE
Erroneous files in SOOP_SST error dir

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#177]
A couple of files have landed in the SOOP_SST dir and have some parts missing in their name, so they obviously don't pass the regex and marked as erroneous:
```
dfruehauf@10-aws-syd:/mnt/ebs/error/SOOP_SST$ ls -la
total 16
drwxrwxr-x  2 projectofficer projectofficer 4096 Feb  4 12:01 .
drwxrwxr-t 29 projectofficer projectofficer 4096 Feb  4 10:15 ..
-r--r--r--  1 projectofficer projectofficer 2612 Feb  1 12:02 IMOS_SOOP-SST_.nc.20160201-120200
-r--r--r--  1 projectofficer projectofficer 2612 Feb  4 12:01 IMOS_SOOP-SST_.nc.20160204-120139
```

**Comment by smancini** [comment]
Send an e-mail to Helen Beggs so she can remove this netCDF file from the BOM ftp site

**Comment by danfruehauf** [comment]
Thanks @smancini. Possibly when this is done, the files should also be cleaned up from the error directory.

**Comment by danfruehauf** [comment]
@smancini I'll let you close this when you think this is solved.

**Comment by smancini** [comment]
This problem did not happen for a while.
