### ISSUE TITLE
Catalogue.aodn and catalogue.imos not sending notification emails

### ISSUE THREAD

**Issue by anguss00** [aodn/content#181]
Notification emails fail to send on these two instances. **This is a requirement to be fixed before bluenet.aodn.org.au can be removed**.

I believe the issue is that firewall access on 12-nsp-mel and 1-aws-syd does not allow postoffice.utas.edu.au (131.217.9.77) access on port 25. This is why unmanaged instances can send emails but not the managed catalogues.

**Comment by anguss00** [comment]
Reference https://github.com/aodn/backlog/issues/248

**Comment by anguss00** [comment]
@kereid do you know by any chance if feedback emails have ever been sent from catalogue.aodn.org.au? Just wondering if this is a new issue or something that has been lurking for a while...

**Comment by danfruehauf** [comment]
Please note that for sending emails from AWS, you'll have to go via a SMTP provider. Cannot do YOLO style emails any more like we used to from uni machines.

**Comment by anguss00** [comment]
Indeed. I was keen to get your advice on this one @danfruehauf. Unfortunately GN 2.10 does not allow SMTP auth (which was added in 3), so I'm not sure how to utilise a SMTP provider here, unless we do GN dev work to get that functionality in.

**Comment by danfruehauf** [comment]
> unless we do GN dev work to get that functionality in.

We really don't want to do that...

**Comment by anguss00** [comment]
Yup, it would be ugly to say the least. However, we have to come up with some way of restoring that email functionality

**Comment by anguss00** [comment]
Pretty sure most SMTP providers don't allow unauthenticated email sending...

**Comment by danfruehauf** [comment]
> Yup, it would be ugly to say the least. However, we have to come up with some way of restoring that email functionality

If something was initially done in a broken way, it does not mean we must preserve the broken-ness of it.

> Pretty sure most SMTP providers don't allow unauthenticated email sending...

Nowadays yes.

**Comment by atkinsn** [comment]
Initial reasoning - https://github.com/aodn/internal-discussions/issues/198
Potential alternative solution - https://github.com/aodn/backlog/issues/290
