### ISSUE TITLE
Redirects from bluenet.aodn.org.au should update url to catalogue.aodn.org.au

### ISSUE THREAD

**Issue by anguss00** [aodn/content#182]
For example, navigate to https://researchdata.ands.org.au/radiolarian-abundance-counts-core-samples/428539/?refer_q=rows=15/sort=score%20desc/class=collection/p=1/q=radiolarian/ and click on go to data provider. 
The website redirected to is actually catalogue.aodn.org.au, but bluenet.aodn.org.au is shown in the address bar (despite the fact that the point of truth for the record is catalogue.aodn). Catalogue.aodn should be shown in the address bar.

**Comment by danfruehauf** [comment]
@anguss00 Close?

**Comment by anguss00** [comment]
Yes definitely @danfruehauf. Confirmed by @atkinsn
