### ISSUE TITLE
ANMN Beagle Gulf mooring has two site codes

### ISSUE THREAD

**Issue by mhidas** [aodn/content#184]
The ANMN mooring located in Beagle Gulf (near Darwin) has site_code 'DARBGF' in the delayed-mode data, but 'NRSBEA' in the real-time data (which comes via AIMS). This is not an NRS site, so 'DARBGF' is more appropriate.

@lbesnard At some point it would be nice to make these consistent. Not urgent.

**Comment by lbesnard** [comment]
see WIP https://github.com/aodn/data-services/pull/448

**Comment by lbesnard** [comment]
@mhidas now fixed. 
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/ANMN/NRS/REAL_TIME/DARBGF/
http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NRS/REAL_TIME/DARBGF/wind_speed_min_10min_channel_84890/2016/QAQC/IMOS_ANMN_M_20160501T000000Z_DARBGF_FV01.nc.info

**Comment by mhidas** [comment]
:+1: 

The title and abstract still refer to "Great Barrier Reef Ocean Observing System (GBROOS)", which is wrong. Same goes for NRSDAR actually.

**Comment by lbesnard** [comment]
Yeap, a lot of things are wrong with things coming from AIMS. pretty hard at times
