### ISSUE TITLE
 Erroneous files in SOOP_XBT_DM error dir

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#185]
Not sure who uploaded those files, but they are in the form of:
```
GTSPPmer2016MQNC/89/00/66/16raw.nc
```

@smancini @lbesnard FYI

**Comment by lbesnard** [comment]
@smancini is already aware, the data provider pushed back some data like this

**Comment by smancini** [comment]
Bec Cowley has uploaded these files. I am going to talk to her today and let her know that in the future she can upload to data.upload.aodn.org.au while we are working together on a pipeline solution.

I have already downloaded the data on my machine and process the data in IMOS netCDF format. I will upload the data to the pipeline soon.
So this folder and all the files can be deleted from the incoming directory

**Comment by danfruehauf** [comment]
> So this folder and all the files can be deleted from the incoming directory

It's up to project officer's responsibility to delete files from the error/incoming directories. I cannot do that.
