### ISSUE TITLE
Difficult to click on features in NOAA Drifters layer

### ISSUE THREAD

**Issue by mhidas** [aodn/content#188]
Feedback from Iain Suthers in Sydney after running the TAMS workshop. He said after the initial geoserver problem was resolved in the morning, it worked fine and they were mostly happy. However, part of the exercise involved clicking on individual drifter tracks to find out the id of a drifter from the GFI box, and they had a lot of difficulty getting the portal to find the feature.

#### How to reproduce:
 * Select the [NOAA Drifters](https://imos.aodn.org.au/imos123/home?uuid=e3cf7cfd-9034-4c03-82ca-5a40ce7f96d2) collection
 * Zoom in a bit so individual tracks can be seen.
 * Click on a track to get the feature info box

#### What happens
Most likely you will get a box that says "No more information found at this point". It can take many attempts before a feature is successfully selected.

#### What should happen
If the pointer is within a couple of screen pixels of a feature when clicking, it should be selected. It can be pretty hard to position the pointer with better accuracy.

**Comment by danfruehauf** [comment]
@anguss00 Somewhat same problem you're looking at - snap to feature/grid point

**Comment by anguss00** [comment]
Yes agreed 100%. I'm guessing this is relatable to quite a few collections in the portal @danfruehauf @mhidas

**Comment by kereid** [comment]
Sounds similar to https://github.com/aodn/aodn-portal/issues/2053 and https://github.com/aodn/content/issues/154

**Comment by lbesnard** [comment]
fix is here https://github.com/aodn/geoserver-config/pull/342
