### ISSUE TITLE
thredds SRS_SST records to point to IMOS infrastructure

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#189]
This is relevant to the following SRS_SST records:
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=35bf740e-792c-4e8f-b505-db40a166f27b
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=8bd3fe33-fd98-4307-ad23-424ad9a2907b
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=18a2dca4-2c18-4d45-8ae5-55b1c0bd38c8
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=aaad092c-c3af-42e6-87e0-bdaef945f522
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=34110d06-707b-4f73-970e-9b38e9fcb7da
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=e6782131-821c-4237-b2a9-27c6aaa8608c
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=46ebc1a9-c503-4435-b85c-11fe16176c8d
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=a136eee7-a990-4c06-a4f6-915657a2464e
 1. https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=671c53fa-b114-4a1c-af18-c131b11b8c85

The following prefix should be replaced as follows:
 * Current: `http://rs-data1-mel.csiro.au/thredds/catalog/imos-srs/sst/ghrsst/`
 * New: `http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/`

So for instance, the URL http://rs-data1-mel.csiro.au/thredds/catalog/imos-srs/sst/ghrsst/L3S-1d/day/catalog.html will now point to http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst//L3S-1d/day/catalog.html

**Comment by danfruehauf** [comment]
FYI @pblain @smancini @atkinsn

**Comment by danfruehauf** [comment]
Alright, all changed.

**Comment by lbesnard** [comment]
:+1
