### ISSUE TITLE
Weird looking organisation

### ISSUE THREAD

**Issue by pblain** [aodn/content#19]
This organisation doesn't look very tidy:
AU/AADC > Australian Antarctic Data Centre, Australia

![image](https://cloud.githubusercontent.com/assets/2802359/2859644/51c69376-d1ae-11e3-8dbc-e9d52f820efb.png)

**Comment by smancini** [comment]
This issue will be fixed when the organisation vocabulary will be available in Poolparty and then used to tag metadata in geonetwork.

**Comment by smancini** [comment]
Task currently blocked.
See corresponding issue in Backlog https://github.com/aodn/backlog/issues/6

**Comment by smancini** [comment]
See corresponding issue in backlog https://github.com/aodn/backlog/issues/537
