### ISSUE TITLE
Bad satellite (SRS) data

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#190]
Bogus data is apparent on year 1950 of collection `SRS_SST L3U NOAA-19`:
https://imos.aodn.org.au/imos123/home?uuid=35bf740e-792c-4e8f-b505-db40a166f27b

Display WMS from 01/01/1950. Data is clearly not a satellite grid, I also suspect that in 1950 there weren't any satellites - but I'm no satellite expert.

Thredds link shows non-standard global attributes as well:
http://thredds.aodn.org.au/thredds/dodsC/IMOS/SRS/SST/ghrsst/L3U/n19/1950/19500101000000-ABOM-L3U_GHRSST-SSTskin-AVHRR19_D-Des.nc.html

Data is CF compliant though!

**Comment by danfruehauf** [comment]
And this is also on RC:
http://portal-rc.aodn.org.au/imos123/home?uuid=35bf740e-792c-4e8f-b505-db40a166f27b

And the thredds link:
http://thredds-rc.aodn.org.au/thredds/dodsC/IMOS/SRS/SST/ghrsst/L3U/n19/1950/19500101000000-ABOM-L3U_GHRSST-SSTskin-AVHRR19_D-Des.nc.html

**Comment by pblain** [comment]
HaHa.. Must have been Sputnik!  Ce ya

**Comment by danfruehauf** [comment]
> HaHa.. Must have been Sputnik! Ce ya

Sputnik 1 was launched in 1957 - https://en.wikipedia.org/wiki/Sputnik_1 - so can't be that.

**Comment by lbesnard** [comment]
Is it a bug related to S3 ? Shall we contact AWS, TPAC, NSP, AODAAC ?

**Comment by danfruehauf** [comment]
:disappointed:

**Comment by lbesnard** [comment]
i was forced to. and it appeared in reporting
