### ISSUE TITLE
Links broken in info tab and GFI

### ISSUE THREAD

**Issue by kereid** [aodn/content#191]
Noted in Systest and production

Steps to reproduce:

Add Srs bio-optical database and proceed to the info tab, 

Click the Data in csv link

What should happen:

Taken to correct URL 

What does happen:

See error

404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: IMOS/public/SRS/SRS-OC-BODBAW/index.html
    RequestId: 353CE3E8B3FD0DD0
    HostId: rwwbdr1ng1cR8twxVtETaBmHqdRap+kpjRhWAcEGmXrkiO2elNTW+Ez1ISZzDvnjaTStCEV6EiE=

This also occurs for the csv link in the GFI

@atkinsn can fix the info link now - however needs a report of some sort to identify any other broken links not sure who can produce this for us @pblain? @danfruehauf while you are still here can you?

I also noticed that the "data access through FTP" link in the info tab of Argo times out don't know if it's related or not.

**Comment by danfruehauf** [comment]
> however needs a report of some sort to identify any other broken links not sure who can produce this for us

There will be quite a few, especially because the hierarchy changed a bit. And also the listing of files is not done with `index.html` any more.

I've raised @smancini's awareness about it.

> I also noticed that the "data access through FTP" link in the info tab of Argo times out don't know if it's related or not.

That's true too, there'll probably be no more FTP as we can facilitate direct S3 access. Not sure how the docu should look - but it should point the user to the right S3 URI which will *hopefully* open up in his/her favourite browser.

**Comment by kereid** [comment]
Thanks @danfruehauf

**Comment by danfruehauf** [comment]
For the sake of completeness, there's also this:
https://github.com/aodn/geoserver-config/pull/333

It'll fix some of the problems, but definitely not all.

**Comment by kereid** [comment]
@atkinsn has now fixed the info tab link, however the GFI link still does not work.

**Comment by danfruehauf** [comment]
> however the GFI link still does not work.

That's in the geoserver PR that I've linked.

**Comment by kereid** [comment]
Rightio thanks

**Comment by atkinsn** [comment]
I have removed the couple of instances where I had added FTP links to records.

**Comment by kereid** [comment]
Re-opening as still require a report to be run who can do this @pblain see initial issue post above

**Comment by pblain** [comment]
@kereid - I'll add it to the backlog

**Comment by atkinsn** [comment]
So I was reminded of this issue when I came across a broken link in the info tab on the portal

**Comment by atkinsn** [comment]
See initial post above - there is also an issue with links in the info tab (distribution element in metadata record), so the backlog item that was created only referred to the links in the gfi.

This issue relates to the move of thredds to Amazon, so most metadata records now (too many to check manually) have broken links (some are being fixed on an ad hoc basis as they are noticed)

 I will add a separate item to the backlog.
