### ISSUE TITLE
SRS changed server - Broken collection in portal

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#192]
IMOS - SRS SATELLITE - OC MODIS - 01 day - Chlorophyll  a concentration algorithm  (OC3)
http://portal-systest.aodn.org.au/imos123/home?uuid=d7a14921-8f3f-4522-9a54-e7d1df969c8a

## Problem
The portal dosent know about rs-data1-mel.csiro.au
Host 'http://rs-data1-mel.csiro.au/ncWMS/wms' not allowed

Dan had a Chef commit that removed this server
https://github.com/aodn/chef-private/commit/ceaff8e4286df693e654506e3f33a1280e156d85

## Fix 
The data (Thredds) is now on S3

@lbesnard

**Comment by smancini** [comment]
This dataset is correctly configured on production (all links pointing to S3).
Why is the metadata different on systest?

**Comment by pmbohm** [comment]
@atkinsn The metadata harvest from prod to systest is currently a manual process. After Easter we will have a look at running this automatically every evening.
