### ISSUE TITLE
Argo Symbol key is wrong

### ISSUE THREAD

**Issue by kereid** [aodn/content#193]
App version: 4.22.1
            Build date: Thu Mar 17 11:32:41 AEDT 2016
            Build number: 45
            Git ref: e4226d3eb99a6ea6ed28cb92c95bca91afaa37a5

Steps to reproduce:

Add Argo collection, when taken to step 2 look at the layer tab in particular the key to the symbols:

What should happen:

Read Argo Float

What does happen:

See padding, highZoom, mediumZoom, lowZoom

**Comment by lbesnard** [comment]
@kereid 
Well, I can change the `padding` one to Argo float. But I unfortunately can't remove the other ones, They can be renamed of course, but they will still be shown on the left pannel. Is that what you want ?

**Comment by lbesnard** [comment]
https://github.com/aodn/geoserver-config/pull/341

**Comment by kereid** [comment]
@lbesnard that sounds fine
