### ISSUE TITLE
Update contact email in GFI for ANMN Passive Acoustic

### ISSUE THREAD

**Issue by smancini** [aodn/content#194]
The e-mail address used in the Get Feature Info for the dataset collection "IMOS - ANMN Passive AcousticObservatories Sub-Facility" is currently info@emii.org.au
It will need to be updated to info@aodn.org.au when moving to a single portal.

**Comment by mhidas** [comment]
@smancini Is that new email address locked in now? Is it active yet? There are a few other places that will need to be updated.

**Comment by smancini** [comment]
The new e-mail address is already available.
We will probably do the changes to the different places at the same time.
i just wanted to keep track of that one while I was testing the GFI for something else.

**Comment by smancini** [comment]
Done !!!
