### ISSUE TITLE
srs_oc_bodbaw_trajectory_profile_map link to CSIRO Cruise metadata incorrect

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#198]
## Whats happening

See: https://github.com/aodn/geoserver-config/search?utf8=%E2%9C%93&q=CSIRO+Cruise+metadata

The GFI popup for this layer contains a link to the CSIRO Cruise metadata that is not a complete URL. The portal then treats it as a local link eg: `http://[phils dev box]/aodn-portal/www.marine.csiro.au/marq/edd_search.Browse_Citation?txtSession=14228`
## What should happen 

CSIRO Cruise metadata should be a full url.
eg: http://www.marine.csiro.au/marq/edd_search.Browse_Citation?txtSession=14228

**Comment by lbesnard** [comment]
fixed here https://github.com/aodn/harvesters/pull/397
