### ISSUE TITLE
AUV VIEWER - all links broken

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#200]
The https://auv.aodn.org.au/auv/ has links to data.aodn.org.au.

ALL links are configured in the content FTL such as
```xml
<a  rel="external" href="${my.baseurlDataServer}/IMOS/AUV/${feature.campaign_code.value}/${feature.site_code.value}" target="_blank" class="h3">Link to data folder</a> <BR>
```
with baseurlDataServe defined in 
https://github.com/aodn/geoserver-config/blob/master/workspaces/config.ftl#L3

and the value is overwritten by chef here
https://github.com/aodn/chef-private/blob/master/data_bags/imos_webapps_geoserver_config_ftl/default.json#L5

However the links in the AUV viewer still have the ```public``` part 
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/IMOS/public/AUV/Batemans201011/all_reports/r20101117_224623_batemans_06_site6guz_report.pdf

instead of 

http://imos-data.s3-website-ap-southeast-2.amazonaws.com/IMOS/AUV/Batemans201011/all_reports/r20101117_224623_batemans_06_site6guz_report.pdf

@pblain should be an easy fix for dev's

**Comment by lbesnard** [comment]
actually the content ftl doesnt seem to be used by the auv viewer. Values are overwritten by 
https://github.com/aodn/auv/blob/master/grails-app/views/finder/_auv_functions_js.gsp#L434

This is an issue for dev.

@smancini @pblain

**Comment by lbesnard** [comment]
@pmbohm I always assumed the AUV viewer was based on the content ftl as you told me many times, but looking at the auv viewer code, it doesn't seem like the content ftl is used much

**Comment by pmbohm** [comment]
@lbesnard The app makes getFeatureInfo requests that are used when user click on the map,  but there is also a 'faking' of a GFI a request on page load that i will see if i can bypass

**Comment by pmbohm** [comment]
There is currently a new problem introduced by Chef not deploying the correct config.ftl https://github.com/aodn/chef/issues/301

**Comment by lbesnard** [comment]
@smancini @pblain Is this part of this next iteration ? Links are still broken on the viewer

**Comment by smancini** [comment]
Can it be closed now @lbesnard ?
