### ISSUE TITLE
AUV viewer code should not 'fake' getFeatureInfo requests

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#201]
### What happens
The code fakes GFI responses generated from a WFS query to get all of the campaigns into a drop down select box. The faked GFI response is out of step with Geoserver changes and should not be created this way
### What should happen 
Hard coded creation of fake GFI responses should be replaced by real requests when a users picks from the drop down

**Comment by smancini** [comment]
Can it be closed now @lbesnard ?
