### ISSUE TITLE
 Sensors on Tropical Research Vessels: Enhanced Measurements from Ships of Opportunity (SOOP) over land

### ISSUE THREAD

**Issue by kereid** [aodn/content#203]
Steps to reproduce:

Add sensors on Tropical Research Vessels: Enhanced Measurements from Ships of Opportunity (SOOP) collection to the map.

View collection display on map 

What should happen:

Shouldn't be data over land from a ship?

What does happen:

Data goes inland from coast of Queensland.

**Comment by lbesnard** [comment]
@kereid contacted Greg Coleman from AIMS. Hope this will be fixed soon

**Comment by lbesnard** [comment]
@smancini I have re contacted AIMS

**Comment by xhoenner** [comment]
Still current @smancini, surprised to see this has been going on for two months now.

**Comment by kereid** [comment]
Still current 13/09/2016!

**Comment by lbesnard** [comment]
this is now cleaned.
