### ISSUE TITLE
all Harvesters have a new build version - not pushed to -> 14nsp -> 10aws

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#205]
Looking at Jenkins, pretty much all harvesters have a new build version since the 27th of May. They didn't get pushed nor to 14nsp nor to 10aws. And we can't display all builds and see which one were being tested on 14nsp or not. 

@anguss00 @lwgordonimos @jonescc do you know anything about this ?

**Comment by lwgordonimos** [comment]
Yes. We had to do a rebuild all as they had all been deleted at some point earlier in May. This was what was causing the PO box to fail, because it points at "talend_build" for it's artifacts.

There were 5 or 6 harvesters sitting there before the rebuild, so I'm assuming those would have been the ones being tested? Maybe we can find a record of which ones these were somehow if that is the case...

**Comment by lbesnard** [comment]
@xhoenner 's fluorometry harvester is affected by this one for example.  We can't deploy it anymore as it's not displayed

**Comment by lwgordonimos** [comment]
@lbesnard could you clarify where it's not displayed? It is present in the build artifacts, and also looks fine when I build the PO box locally...

==> po: * talend_job[aodn_imas_fluorometry-aodn_imas_fluorometry] action deploy
==> po:  (up to date)
==> po:   
==> po: * imos_artifacts_deploy[aodn_imas_fluorometry-aodn_imas_fluorometry] action deploy
==> po: [2016-06-02T12:27:46+10:00] ERROR: Error loading data bag (passwords, jenkins-api).
==> po: [2016-06-02T12:27:46+10:00] WARN: Not using authentication for jenkins download from 'https://ci.aodn.org.au/job/talend_build/lastSuccessfulBuild'
==> po: [2016-06-02T12:27:47+10:00] INFO: Downloading artifact version ''
==> po: [2016-06-02T12:27:47+10:00] INFO: Cached 'https://ci.aodn.org.au/job/talend_build/lastSuccessfulBuild/artifact/target/AODN_IMAS_FLUOROMETRY_harvester_Latest.zip.md5' at '/tmp/jenkins-artifact-md520160602-3310-1ifp0yl'
==> po: [2016-06-02T12:27:47+10:00] INFO: Checksums do not match will download artifact https://ci.aodn.org.au/job/talend_build/lastSuccessfulBuild/artifact/target/AODN_IMAS_FLUOROMETRY_harvester_Latest.zip
==> po: [2016-06-02T12:28:06+10:00] INFO: Cached 'https://ci.aodn.org.au/job/talend_build/lastSuccessfulBuild/artifact/target/AODN_IMAS_FLUOROMETRY_harvester_Latest.zip' at '/var/chef/cache/talend_build_AODN_IMAS_FLUOROMETRY_harvester_Latest.zip'
==> po: [2016-06-02T12:28:06+10:00] INFO: Attempting to deploy artifact 'aodn_imas_fluorometry-aodn_imas_fluorometry' -> '/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/java'
==> po: [2016-06-02T12:28:07+10:00] INFO: No need to deploy artifact '/var/chef/cache/talend_build_AODN_IMAS_FLUOROMETRY_harvester_Latest.zip' -> '/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/aodn_imas_fluorometry.zip' -> '/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/java'
==> po:  (up to date)
==> po:   
==> po: * directory[/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/java] action create
==> po:  (up to date)
==> po:   
==> po: * talend_job[aodn_imas_fluorometry-aodn_imas_fluorometry] action configure
==> po:  (up to date)
==> po:   
==> po: * template[/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/etc/aodn_imas_fluorometry-aodn_imas_fluorometry.conf] action create
==> po:  (up to date)
==> po:   
==> po: * talend_job[aodn_imas_fluorometry-aodn_imas_fluorometry] action schedule
==> po:  (up to date)
==> po:   
==> po: * file[/usr/local/talend/jobs/aodn_imas_fluorometry-aodn_imas_fluorometry/bin/aodn_imas_fluorometry-aodn_imas_fluorometry.sh] action create
==> po:  (up to date)
==> po:   
==> po: * cron[aodn_imas_fluorometry-aodn_imas_fluorometry] action create
==> po: [2016-06-02T12:28:07+10:00] INFO: cron[aodn_imas_fluorometry-aodn_imas_fluorometry] added crontab entry
==> po:     
==> po: - add crontab entry for cron[aodn_imas_fluorometry-aodn_imas_fluorometry]

**Comment by xhoenner** [comment]
@lwgordonimos it is not visible through the talend tab in jenkins anymore so we can't promote it to prod anymore.

**Comment by anguss00** [comment]
@xhoenner the fluro harvester has been pushed to 14-nsp and 10-aws

**Comment by lbesnard** [comment]
Similar thing since last week happened.
FYI @smancini 

The history of 40 harvesters (out of 70) only displayed on jenkins is also an issue

**Comment by smancini** [comment]
To be fixed by corresponding backlog item https://github.com/aodn/backlog/issues/526
