### ISSUE TITLE
ANMN CTD profiles harvests only CHLF variable, but some data has CPHL instead

### ISSUE THREAD

**Issue by mhidas** [aodn/content#209]
E.g. [this WFS request](http://geoserver-123.aodn.org.au/geoserver/ows?typeName=anmn_ctd_profiles_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=site_code%20LIKE%20'NRSMAI') has nothing in the **CHLF** (chlorophyll) column, but the netcdf [files](http://thredds.aodn.org.au/thredds/dodsC/IMOS/ANMN/NRS/NRSMAI/Biogeochem_profiles/IMOS_ANMN-NRS_CDEKSTUZ_20111026T002616Z_NRSMAI_FV01_Profile-SBE-19plus_C-20160526T025056Z.nc.html) have chlorophyll data in the **CPHL** variable.

**Comment by mhidas** [comment]
https://github.com/aodn/harvesters/pull/674 should fix this. I'll close the issue once the update has been deployed to prod.

Ideally we should also update the CSV metadata header, so that users know what the different columns mean.

**Comment by ggalibert** [comment]
Before closing this please identify the files that need re-harvesting and run Talend on them.

**Comment by ggalibert** [comment]
Ideally we'd like to update the CSV header in order to include CPHL and CHLF. Looks like the workflow description includes some info about this process: https://github.com/aodn/internal-discussions/issues/428

**Comment by mhidas** [comment]
The harvester update has been deployed, and all CTD files have been re-harvested. Just waiting for Geoserver to pick up the change in the view.

**Comment by mhidas** [comment]
The CSV header update is here: https://github.com/aodn/data-services/pull/905

**Comment by mhidas** [comment]
This was fixed, just forgot to close it.
