### ISSUE TITLE
FRRF - link to netcdf files corrupted

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#210]
Layer ```Fast Repetition Rate Fluorometry (FRRF) data collected on the RV L'Astrolabe```

On step 3, when one select 
* un subsetted list of urls
* list of netcdf url

this fails.

Reason
Url is :
http://data.aodn.org.au/http://thredds.imas.utas.edu.au/thredds/fileServer/IMAS/AMcMinn_FRRF_l_Astrolabe/2006/FRRF_TSB_20061022T000044Z_FHZI_FV01_fluorometry-R02006s_END-20061025T060459Z.nc

**Comment by smancini** [comment]
Describe as a portal bug here
https://github.com/aodn/aodn-portal/issues/2228
