### ISSUE TITLE
Geoserver Capabilities Request fails in geoserver-123

### ISSUE THREAD

**Issue by jonescc** [aodn/content#212]
## How to reproduce:

click http://geoserver-123.aodn.org.au/geoserver/ows?service=wms&version=1.1.1&request=GetCapabilities

## What happens 

Get an incomplete invalid GetCapabilities statement

## What I expect 

To get a valid Getcapabilities statement

**Comment by jonescc** [comment]
Refer https://github.com/aodn/internal-discussions/issues/247

Layers  srs_oc_ljco_wws_daily_wqm_fv02_timeseries_data and srs_oc_ljco_wws_hourly_wqm_fv01_timeseries_data reference a non existant style in there definition.

https://github.com/aodn/geoserver-config/search?utf8=%E2%9C%93&q=StyleInfoImpl-9b0d687%3A1521054cdbd%3A-7ffc

**Comment by lbesnard** [comment]
fixed here https://github.com/aodn/geoserver-config/pull/363

**Comment by lbesnard** [comment]
@lwgordonimos FYI, this is now fixed
