### ISSUE TITLE
Acidification Moorings DM collection CSV metadata header inconsistent with file

### ISSUE THREAD

**Issue by mhidas** [aodn/content#214]
The netCDF file has:`TEMP:standard_name = "sea_surface_temperature"`.
The CSV metadata header says: `# TEMP | sea_water_temperature`

**Comment by leonardolaiolo** [comment]
@mhidas can you confirm that the NetCDF standard name for ```TEMP``` is correct? Then I can update the CSV header.

**Comment by mhidas** [comment]
Yes, the standard_name for TEMP is "sea_surface_temperature"
