### ISSUE TITLE
Seabed Habitat Solitary Islands Marine Park and Commonwealth Marine Reserve (South) - No WMS/WFS

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#219]
When the following record is selected 
`Seabed Habitat Solitary Islands Marine Park and Commonwealth Marine Reserve (South)`

There is nothing displayed on Step 2. And nothing to download on Step 3

My understanding was that when a layer was not working, it was removed from the search @pblain  ? but maybe this layer is working but empty ?

**Comment by lbesnard** [comment]
Actually, @atkinsn pointed out that the WMS exists, but is extremely small. I had to go to the ```Layer``` tab to find the ``` Zoom to collection``` button which I wasn't aware off. I think it points out that this is maybe not intuitive as a user experience. I'm wondering if the zoom to collection could be done automatically ?

**Comment by atkinsn** [comment]
As just discussed with @lbesnard , @smancini and I are aware that there is no WFS, we asked them to remove it before we set up the harvest, as the data is only available as a shapefile, and we are not in a position yet to offer this as a download option. So for now, the shapefile is available to download online, and this link shows up in step 3.

**Comment by pblain** [comment]
@lbesnard - we tried autozoom in the past and it was even more confusing.  Better if WMS layers are visible from all zoom levels.

**Comment by smancini** [comment]
Users can now download the data in shapefile format.
