### ISSUE TITLE
GogoDuck can't access URL lists for satellite composite collections

### ISSUE THREAD

**Issue by kereid** [aodn/content#221]
Opening (https://github.com/aodn/aodn-portal/issues/2212) here as it was logged in aodn-portal but got closed and listed as content but not moved.

Seeing on portal.aodn and imos.aodn

Steps to reproduce:

Add any of the following:
IMOS - SRS SATELLITE - SST L3S - 03 day composite - night time
IMOS - SRS Satellite - SST L3S - 03 day composite - day and night time composite
IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time
IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite

What should happen:

See a size estimate.

What does happen:

No size estimate which indicates it cannot access the URL lists

**Comment by smancini** [comment]
@kereid and @pblain Is this issue still relevant as the download size estimator feature is no longer working in the portal?

**Comment by kereid** [comment]
@smancini I guess it can be closed it as the estimator is turned off for now and when it is turned back on I can open a new one if it still fails as I have a test case for it and will keep that test case in they list.
