### ISSUE TITLE
Wakmatha data is accessible from general CO2 collection

### ISSUE THREAD

**Issue by atkinsn** [aodn/content#222]
If a user selects the collection:  	IMOS - SOOP Underway CO2 Measurements Research Group , they are able to filter the data coming from the RTM Wakmatha in step 2.

This data has been assigned to its own collection for a variety of reasons, with one of the main ones being the identification of citable parties (all external parties). With it included within the IMOS collection, this information is lost, and would lead to an incorrect citation.

The ability to view the Wakmatha data as part of this collection needs to be removed.

**Comment by bpasquer** [comment]
Data from the Wakmatha as been removed from the SOOP-CO2 collection
