### ISSUE TITLE
POBOX - geoserver string filters not working

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#223]
When configuring a new layer on the pobox and its associated filters on geoserver, if one filter is type string, the unique values wont be retrieved on step 2. This needs to be tested via the RC environment instead

**Comment by smancini** [comment]
Blocked by following backlog item https://github.com/aodn/backlog/issues/446

**Comment by mhidas** [comment]
String filters are working fine for me, and unique values are being filled in fine. (Running off chef branch https://github.com/aodn/chef/tree/pipeline_2_legacy)

@lbesnard Have you seen this issue recently?
