### ISSUE TITLE
POBOX - can't download thredds urls -> can't test geoserver ncWMS plugin

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#224]
It is not possible to do wget on any thredds.aodn.org.au urls on the pobox.
Which means ncWMS geoserver layers can't be tested such as new CARS and SST/OC layers

**Comment by smancini** [comment]
Blocked by following backlog item https://github.com/aodn/backlog/issues/446

**Comment by pblain** [comment]
See this: https://github.com/aodn/issues/issues/84#issuecomment-331757195

**Comment by pblain** [comment]
@jonescc to add a backlog item and close this

**Comment by jonescc** [comment]
The PO Box is setup to redirect any references to thredds.aodn.org.au to the thredds instance on the po box (http://po.aodn.org/thredds).  If metadata is imported/harvested from production this allows modifications/new data to be tested on the po box before publishing to the the real thredds.

To download data from production using wget, download from the s3 location instead e.g.

    wget 'https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/ANFOG/seaglider/Bicheno20091126/Bicheno20091126_CDOM.jpg'

po.aodn.org.au/thredds is currently setup to publish content in /s3/imos-data/IMOS so to test new or modified data add the data to the /s3/imos-data/IMOS directory

If this workflow isn't quite right then we can address in aodn/backlog#446 above or we can raise a specific backlog item to fix it.   I've been tasked to do that so let me know what it should be.

**Comment by mhidas** [comment]
Thanks @jonescc That makes sense to me. Does that mean we *should* be able to test the geoserver ncWMS plugin on files that are published in the po box?

**Comment by jonescc** [comment]
Yes you should be able to - the po box geoserver should be pointing at the local thredds server so it should work if there is data published there.

**Comment by mhidas** [comment]
@lbesnard Do you want to give it a go, to see if we can close this issue?

**Comment by lbesnard** [comment]
I'll give it a go. However it would not change anything regarding testing ncWMS layers against production data

**Comment by jonescc** [comment]
To test against production data you can change the thredds catalog config on the po box to point to s3 prod instead of the local /s3 location e.g. this is what I do for my testing:

```
  <datasetScan name="IMOS" ID="IMOS" path="IMOS" location="s3://imos-test-data.aodn.org.au">
    <metadata inherited="true">
      <serviceName>regGriddedServices</serviceName>
      <dataType>Grid</dataType>
    </metadata>
    <filter>
      <include wildcard="*.nc"/>
      <include wildcard="*.nc.gz"/>
      <include wildcard="*.ncml"/>
    </filter>
    <crawlableDatasetImpl className="thredds.crawlabledataset.s3.CrawlableDatasetAmazonS3"/>
  </datasetScan>
``

This is in the content/thredds/../imos.xml file in the tomcat directory

**Comment by jonescc** [comment]
Just noticed abovce is for a test s3 bucket - you will probably want to point to prod.

I've added an example to the thredds config file deployed to the po box.   See https://github.com/aodn/chef/pull/592

**Comment by pblain** [comment]
@jonescc says this can be closed. See https://github.com/aodn/content/issues/224#issuecomment-332366710
