### ISSUE TITLE
Indexed time does not match actual time recorded in the dataset for some SRS files

### ISSUE THREAD

**Issue by jonescc** [aodn/content#228]
For example for IMOS/SRS/SST/ghrsst/L3S-1mS/dn/1992/19920331111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc, in the database the time is listed as "1992-03-31 09:20:00" whereas the actual time recorded in the file is 1992-03-16 11:10:00 .   This results in mismatches between the actual data requested in the portal and the data returned.  It also causes issues with gogoduck and ncwms prototype which make use of the indexed time to select the correct file.

**Comment by jonescc** [comment]
Another example is http://data.aodn.org.au/IMOS/SRS/SST/ghrsst/L3S-1m/ngt/1995/19950630032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1m_night.nc

In the database the timestamp is recorded as "1995-06-30 03:20:00" but in the dataset I work out the actual timestamp to be 16/06/95 03:20 - thats out by around 14 days

**Comment by jonescc** [comment]
@lbesnard - not sure if you've seen this.

**Comment by lbesnard** [comment]
@jonescc thanks a lot. That's really bizarre. I'm going to contact the SRS people

**Comment by jonescc** [comment]
Its causing aggregations to fail - is it possible to reindex files for which we know this is occurring or should they be deleted until the problem is resolved?

**Comment by jonescc** [comment]
All problematic files reported in the logs

19920331092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc
19920331111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc
19920331152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1m_night.nc
19941031092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc
19950630032000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1m_night.nc
20000131111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc
20100331152000-ABOM-L3S_GHRSST-SSTskin-AVHRR_D-1m_night.nc
20140131111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc
20150131092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.nc
20150331111000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc
20150228231000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn_Southern.nc

**Comment by jonescc** [comment]
This won't include files no one has tried to download which aren't correct and files which have been indexed correctly but have the wrong timestamp in the filename.

**Comment by jonescc** [comment]
Perhaps some checks in the harvester if we can't add this to the compliance checker?

**Comment by jonescc** [comment]
And a bulk reconciliation of existing files

**Comment by lbesnard** [comment]
actually ALL monthly files, ie all files under
http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/L3S-1mS/catalog.html
http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/L3S-1m/catalog.html

are affected (except for 2016 files). The date was taken in the past from the filename, and now from the time variable. I'm redownloading and reprocessing all those files.

It is possible however that other files are affected

**Comment by lbesnard** [comment]
@kereid this should be fixed now I believe

**Comment by kereid** [comment]
Thanks @lbesnard Craig let me know earlier and I tested and all looks good.
