### ISSUE TITLE
Hard to see some layers

### ISSUE THREAD

**Issue by pblain** [aodn/content#237]
Layers like this (with a single red dot) are really hard to see ...

![image](https://cloud.githubusercontent.com/assets/2802359/18855261/bb2a7080-8494-11e6-9cdf-fe9d7e6aeb15.png)

**Comment by pmbohm** [comment]
### Layers using default red square
aodn/AODN_Bluenet/water_sampling_port_jackson      
aodn/AODN_Bluenet/sediment_data_wistari_reef      
aodn/AODN_Bluenet/herbert_river_study      
aodn/AODN_Bluenet/bluenet_datasets_indian_ocean      
aodn/AODN_Bluenet/bluenet_datasets_leeuwin_current      
aodn/AODN_Bluenet/bluenet_datasets_southern_indian_ocean      
aodn/AODN_Bluenet/sediment_data_broken_bay_to_abyssal_plain      
aodn/AODN_Bluenet/water_sampling_cockburn_sound      
aodn/AODN_Bluenet/water_levels_gippsland_lakes      
aodn/AODN_Bluenet/water_sampling_cockburn_sound_1982-2012      
aodn/AODN_Bluenet/peel_harvey_estuary_study      
aodn/AODN_Bluenet/bluenet_datasets_new_caledonian_basin      
aodn/AODN_Bluenet/phytoplankton_sydney_harbour      
aodn/AODN_Bluenet/bluenet_datasets_capricorn_channel      
aodn/JNDI_aodn_csiro_cmar/aodn_csiro_cmar_mooring_map    
imos/JNDI_anmn_velocity/anmn_velocity_timeseries_map    
imos/JNDI_gsla_dm00/gsla_dm00_timeseries_url    
imos/JNDI_anmn_burst_avg/anmn_burst_avg_timeseries_map    
imos/JNDI_abos_sots/abos_sots_map    
imos/JNDI_anmn_nrs_rt_bio/anmn_nrs_rt_bio_timeseries_map    
imos/JNDI_abos_ts/abos_ts_timeseries_map    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_cof_nonqc_timeseries_url    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_cbg_nonqc_timeseries_url    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_bonc_nonqc_timeseries_url    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_rot_nonqc_timeseries_url    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_sag_nonqc_timeseries_url    
imos/JNDI_acorn_hourly_avg_nonqc/acorn_hourly_avg_turq_nonqc_timeseries_url    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_plankton_phytoplankton_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_picoplankton_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_chemistry_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_phypig_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_tss_secchi_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_plankton_zooplankton_map    
imos/JNDI_anmn_nrs_bgc/anmn_nrs_bgc_plankton_biomass_map    
imos/JNDI_anmn_ctd_profiles/anmn_ctd_profiles_map    
imos/JNDI_anmn_am_nrt/anmn_am_nrt_map      
imos/JNDI_abos_sofs_fl/abos_sofs_surfaceflux_rt_map    
imos/JNDI_abos_sofs_fl/abos_sofs_surfaceflux_dm_map    
imos/JNDI_gsla_nrt00/gsla_nrt00_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_turq_qc_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_cof_qc_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_rot_qc_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_bonc_qc_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_sag_qc_timeseries_url    
imos/JNDI_acorn_hourly_avg_qc/acorn_hourly_avg_cbg_qc_timeseries_url    
imos/JNDI_srs_ljco_aeronet/srs_oc_ljco_aeronet_map    
imos/JNDI_abos_currents/abos_currents_map    
imos/JNDI_anmn_nrs_rt_meteo/anmn_nrs_rt_meteo_timeseries_map    
imos/JNDI_srs_altimetry/srs_altimetry_timeseries_map    
imos/JNDI_abos_sofs_sp/abos_sofs_surfaceprop_dm_map    
imos/JNDI_abos_sofs_sp/abos_sofs_surfaceprop_rt_map    
imos/JNDI_anmn_nrs_rt_wave/anmn_nrs_rt_wave_timeseries_map

**Comment by pmbohm** [comment]
### Layers all using bluenet.sld

aodn/AODN_Bluenet/water_sampling_port_jackson    
aodn/AODN_Bluenet/sediment_data_wistari_reef    
aodn/AODN_Bluenet/herbert_river_study    
aodn/AODN_Bluenet/bluenet_datasets_indian_ocean    
aodn/AODN_Bluenet/bluenet_datasets_leeuwin_current    
aodn/AODN_Bluenet/bluenet_datasets_southern_indian_ocean    
aodn/AODN_Bluenet/sediment_data_broken_bay_to_abyssal_plain    
aodn/AODN_Bluenet/water_sampling_cockburn_sound    
aodn/AODN_Bluenet/water_levels_gippsland_lakes    
aodn/AODN_Bluenet/water_sampling_cockburn_sound_1982-2012    
aodn/AODN_Bluenet/peel_harvey_estuary_study    
aodn/AODN_Bluenet/bluenet_datasets_new_caledonian_basin    
aodn/AODN_Bluenet/phytoplankton_sydney_harbour    
aodn/AODN_Bluenet/seagrass_sampling_cockburn_sound    
aodn/AODN_Bluenet/bluenet_datasets_capricorn_channel    
imos/JNDI_anmn_nrs_long_ts/anmn_nrs_long_ts_map    
imos/JNDI_anmn_nrs_long_ts/anmn_nrs_long_ts_map      
imos/JNDI_anmn_wave/anmn_wave_map

**Comment by akashisama** [comment]
Most of these could be fixed by applying the relevant facility style already used in the "Integrated Marine Observing System (IMOS) - Location of assets" layer ("imos:asset_map" in geoserver).

**Comment by akashisama** [comment]
I've categorized the redsquare layers into groups based on how they are distributed on the map. We'll have to decide on a way to deal with each group. 
[redsquare layer icon distribution.txt](https://github.com/aodn/content/files/746727/redsquare.layer.icon.distribution.txt)

**Comment by akashisama** [comment]
Difference in icon size between the redsquare icon and the ABOS icon can be seen below. ABOS style could potentially be changed to have a bigger icon.
![image](https://cloud.githubusercontent.com/assets/1926880/22631370/bcf8dfc2-ec5f-11e6-9ab6-e735a41cb57b.png)

**Comment by akashisama** [comment]
Some notes for future reference when we get around to fixing this stuff:
* We should make the icons bigger. There's been some talk of using ScaleDenominator to make them bigger just at zoomed out levels, but I don't see that this is a good idea. The further you zoom in the more distant the icons are from each other and therefore the bigger you can make them. If we want a bigger icon zoomed out then we should also have it bigger zoomed in.

* PointStacker can be used to group multiple close icons into one icon, with a number on the icon revealing the number of icons merged into it. We are not currently using PointStacker any where.

* PropertyIsEqualTo and PropertyIsLike could possibly be used to change icons depending on the properties of a specific layer, and therefore allow us to have one style for multiple layers with different icons. We are currently using these in 2 or 3 styles only and, only for simple tests.

**Comment by ggalibert** [comment]
Coming back from the TAMS workshop where students had to exercise themselves with the portal, we faced a couple of important difficulties: 

1. some icons (AusCPR, Argo, ...) are really small and difficult to spot, and it is almost impossible to retrieve the getFeatureInfo pop-up window. Hopefully the first point mentioned by @akashisama above should sort this. The click for getFeatureInfo might be a separate problem though.
![screenshot from 2017-03-06 12-48-37](https://cloud.githubusercontent.com/assets/3498686/23594111/4544dc20-026b-11e7-9713-812938ddf982.png)

2. the yellow color chosen for ARGO was often really hard to see depending on the quality of the screen and the light conditions. Below is the result of one of the questions during the TAMS workshop.
![screenshot from 2017-03-06 12-41-55](https://cloud.githubusercontent.com/assets/3498686/23594010/6fe444f8-026a-11e7-8f3b-d0b8d221cd10.png)

**Comment by mhidas** [comment]
Has there been any work done on this recently? Have any of the layer styles been changed? @pmbohm's post [above](https://github.com/aodn/content/issues/237#issuecomment-276566942) lists `abos_sots_map` as one of the layers with the "red square" style, but looking at the portal just now, it seems to have a different style.

No improvement in either visibility or labelling, however, as this layer has nothing to do with Phytoplankton.

![abos_sots_map_style](https://cloud.githubusercontent.com/assets/3579859/24742771/00e5e604-1aef-11e7-90be-c490f8fec9b4.png)

**Comment by akashisama** [comment]
Strange, there haven't been any changes made by developers as far as I know.

**Comment by akashisama** [comment]
Yeah the "point" style isn't matching with what's in chef-config (where it's defined as a red square). The chef-config files are on the server where they're supposed to be. All the geoservers are replicating this.  So it's a bug of some kind.
