### ISSUE TITLE
Problem displaying Acorn file

### ISSUE THREAD

**Issue by jonescc** [aodn/content#241]
IMOS - ACORN - Coffs Harbour HF ocean radar site (New South Wales, Australia) - Real-time sea water velocity

2012-03-13 23:30:00:000 UTC

Layer looks to be displayed scrambled in the portal for this date/time?

**Comment by smancini** [comment]
Can you please have a look at the netCDf files @ggalibert ?
It seems that all the netCDF files from 09/03/2012 to 25/03/2012 have the same issue

**Comment by ggalibert** [comment]
It looks like the grid was different during this first period of acquisition up to 26/03/2012 00:50:00 and 00:55:00 included. From 26/03/2012 01:00:00 the grid changed to what we know it as of today. See below (color is POSITION value and shows a change):

![screenshot from 2016-11-15 16-38-42](https://cloud.githubusercontent.com/assets/3498686/20294541/f3f1c9ec-ab52-11e6-95cc-c2b4fb525fdd.png)


Hourly averaging process applies a specific grid regardless of the latitude and longitude found in the radials. Instead it relies on the POSITION values:
-POSITION = 1 means LATITUDE = -29.363513 and LONGITUDE = 153.010561
-POSITION = 2 means LATITUDE = -29.377044 and LONGITUDE = 153.010561
-etc...
This is for the current known grid. On a previous grid this might be different (same point at a different POSITION value) and so lead to erratic results if still assuming the current grid.

I will remove the hourly averaged files and notify ACORN about this. If they agree might potentially remove radials as well or produce hourly averaged files on a different grid for this period.

**Comment by ggalibert** [comment]
SAG files in 02/10/2009 are empty (only fillValues), they shouldn't exist.

**Comment by ggalibert** [comment]
SAG files have been deleted. Current processing script cannot create empty files. This must have been created by an earlier version of the script.

**Comment by jonescc** [comment]
GoGoDuck will have problems trying to aggregate files using different grids.  These files would need to be kept separate somehow?

**Comment by ggalibert** [comment]
Hmmm, looks like I've just stuffed po_s3_del... The command is not doing anything anymore on some of the files I want to delete:
```Bash
po_s3_del IMOS/ACORN/gridded_1h-avg-current-map_non-QC/COF/2012/03/26/IMOS_ACORN_V_20120326T003000Z_COF_FV00_1-hour-avg.nc
```

**Comment by ggalibert** [comment]
COF FV00 erroneous hourly files from 09/03/2012 to 26/03/2012 00:30:00 included have been deleted. Portal is not showing the issue described in this post any more.

**Comment by ggalibert** [comment]
Also, this will prevent GGDuck to fail. No problem in keeping the radials though. Will notify ACORN and see if they can re-create the radials on the one grid already supported (usually possible). Then hourly files can be processed correctly and GGDuck will be fine.
