### ISSUE TITLE
SRS ALTIMETRY - Heath bad - no download

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#243]
The SRS ALTIMETRY layer is currently in the Health Bad category (how do we get notify of this by the way ?)

https://portal.aodn.org.au/search?health=bad

I tried to see what's wrong with it. The data can not be downloaded, with or without subsets. There is no error message.

**Comment by jonescc** [comment]
From the geoserver-123 log:

Failed to execute statement SELECT "site_name","instrument","TIME","LATITUDE","LONGITUDE","DEPTH","CNDC","PRES","PSAL","TEMP","UCUR","VCUR","CNDC_quality_control","PRES_qu
ality_control","PSAL_quality_control","TEMP_quality_control","UCUR_quality_control","VCUR_quality_control","CNDC_b","PRES_b","PSAL_b","TEMP_b","UCUR_b","VCUR_b",encode(ST_AsEWKB("geom"),'base64') as "geom" FROM 
"srs_altimetry"."srs_altimetry_timeseries_data" LIMIT 1

column "DEPTH" does not exist

**Comment by lbesnard** [comment]
hum thanks @jonescc . This is due to the fact that column names changed, but geoserver is not restarting automatically as it used to. Could you do this please @lwgordonimos  ?

**Comment by jonescc** [comment]
Perhaps there should be a nagios alert for collections failing health checks

**Comment by lwgordonimos** [comment]
@jonescc this is the sort of thing I had in mind for a potential Sumo/Nagios web service integration, since this is already picking up on this state from the logs.

**Comment by jonescc** [comment]
@lbesnard - I don't think geoserver has ever been restarted automatically by a talend harvester running and updating a view definition?

**Comment by lbesnard** [comment]
@jonescc I don't know how it worked in the past. It wasn't restarted by a talend harvester, but I think by the provision of the machine.

**Comment by lbesnard** [comment]
looks fixed now. @lwgordonimos did you have to do anything to update geoserver ?

**Comment by lwgordonimos** [comment]
Assuming it works now, it should just automatically remove it from the bad list when it runs once an hour. Looks like it's not on a bad list any more?

**Comment by lbesnard** [comment]
yeap yeap it works, but just wondering why ? if you did something or not >?

**Comment by pblain** [comment]
The requirements for this included an email (or other notification) that gets sent to the provider when a data collection is found to have failing services.  I don't think the notification has been implemented yet, but needs to be for AODN scalability.

**Comment by kereid** [comment]
@pblain looks like the email feature was originally in https://github.com/aodn/backlog/issues/88 but that issue is now closed, I had a quick look couldn't see any other items in the backlog for it, should it be re-opened so it can get looked at?

**Comment by pblain** [comment]
@kereid - I'll create a new backlog item for it.
