### ISSUE TITLE
CARS Monthly - negative values of concentration of Nitrate

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#245]
![bad_cars](https://cloud.githubusercontent.com/assets/2382814/19754791/6c106588-9c5c-11e6-908d-5e4433e2d678.jpg)

Looking at CARS, I stumbled across some negative values of moles for the Nitrate variable. 
Creating a colour bar from 0 to 35 highlights all the negative values in black

**Comment by ggalibert** [comment]
Indeed, looking at the [CARS usage documentation](http://www.marine.csiro.au/~dunn/cars2009/#use), we should replace any negative values from nutrients by zero.

**Comment by ggalibert** [comment]
Fixed with two new files. Content has also been updated to pass CF checks.
![screenshot from 2016-12-01 15-12-08](https://cloud.githubusercontent.com/assets/3498686/20781651/8d6b9c56-b7d8-11e6-9041-0fcc34e24556.png)
