### ISSUE TITLE
Geoserver 123 errors 1/11-2/11/2016

### ISSUE THREAD

**Issue by jonescc** [aodn/content#248]
The requested Style can not be used with this layer.  The style specifies an attribute of no_detections_at_station and the layer is: imos:aatams_acoustic_detections_map

Illegal property name: time_start for feature type imos:srs_oc_soop_rad_trajectory_map

Illegal property name: time_start for feature type imos:soop_sst_nrt_trajectory_map

Illegal property name: time_start for feature type imos:soop_sst_dm_trajectory_map

Illegal property name: time_start for feature type imos:soop_co2_trajectory_map

Illegal property name: time_start for feature type imos:soop_asf_mt_trajectory_map

Illegal property name: time_start for feature type imos:auv_trajectory_map

**Comment by jonescc** [comment]
The illegal property errors look to be due to wfs requests made using non-existent time_start properties (MARVL?).

The request producing the style error was:

```
/geoserver/imos/wms?LAYERS=imos:aatams_acoustic_detections_map&SERVICE=WMS&FORMAT=image/png&VERSION=1.1.1&REQUEST=GetMap&BBOX=110,-50,160,-3&WIDTH=1&HEIGHT=1
```

So looks like an issue with the default style for this layer

**Comment by xhoenner** [comment]
This is due to the fact that the corresponding changes in the harvester were never deployed to prod (see #717 in https://jenkins.aodn.org.au/view/talend/), could you do that for me please @jonescc ?

**Comment by jonescc** [comment]
Promoted the harvester in jenkins.  Should be deployed around 5pm this afternoon.

**Comment by julian1** [comment]
Do harvester changes get tested in RC anymore?

**Comment by xhoenner** [comment]
> Promoted the harvester in jenkins. Should be deployed around 5pm this afternoon.

Excellent, thanks @jonescc.

> Do harvester changes get tested in RC anymore?

Yes they do, except when RC is down. This particular harvester has been running successfully on RC for a month now.

**Comment by mhidas** [comment]
> Do harvester changes get tested in RC anymore?

Just to emphasize Xav's point, yes they do (same for pipeline & checker changes), but this has been increasingly difficult over the past month or so with all the problems on 14-nec-hob. Even when it's not 
"down" as such, it's very slow and the chef_cook_node often fails so the changes we want to test are not deployed.

**Comment by smancini** [comment]
Do we still have an issue with the default style for the "aatams_acoustic_detections" layer?
@xhoenner and @jonescc 
Can we close this issue?

**Comment by xhoenner** [comment]
Yes we can, this was solved by promoting the harvester to prod.
