### ISSUE TITLE
CARS metadata

### ISSUE THREAD

**Issue by pblain** [aodn/content#249]
I can't see anywhere in the CARS metadata a mention of what the CARS acronym stands for. "CSIRO Atlas of Regional Seas" I think.

**Comment by ggalibert** [comment]
Good point, although the link to the [CARS web page](http://www.marine.csiro.au/~dunn/cars2009/) is provided in the abstract and gives such information.

If you look at CSIRO's original CARS netCDF files (for example [this one](http://thredds.aodn.org.au/thredds/dodsC/CSIRO/Climatology/CARS/2009/temperature_cars2009a.nc.html)), you'll see that there is no mention of what the acronym stands for neither.

**Comment by atkinsn** [comment]
I have added the full name to the title and the abstracts.
