### ISSUE TITLE
Invalid links in ACORN metadata

### ISSUE THREAD

**Issue by jonescc** [aodn/content#250]
Refer  https://github.com/aodn/aodn-portal/issues/2384

Metadata for ACORN collections include invalid links to thredds folders.

For example, IMOS - ACORN - Rottnest Shelf HF ocean radar site (Western Australia, Australia) - Real-time sea water velocity includes a  link to http://thredds.aodn.org.au/thredds/catalog/IMOS/ACORN/monthly_gridded_1h-avg-current-map_non-QC/ROT/catalog.html . However, there is no monthly_gridded_1h-avg-current-map_non-QC folder in IMOS/ACORN

**Comment by ggalibert** [comment]
Good point, these monthly links need to be removed.

**Comment by ggalibert** [comment]
@atkinsn could you please update the ACORN metadata records that include references to monthly links in "Distribution" in order to remove these links?

-ROT RT and DM, 
-CBG RT and DM, 
-SAG RT and DM, 
-COF RT and DM, 
-TURQ RT and DM, 
-BONC RT and DM.

**Comment by atkinsn** [comment]
Will do so shortly :) @ggalibert

**Comment by atkinsn** [comment]
Done.
