### ISSUE TITLE
As a user I WANT the broken links in the MARVLIS portal fixed SO THAT they work again

### ISSUE THREAD

**Issue by pblain** [aodn/content#251]
The links to metadata and data point to an old version of geonetwork and thredds.

example records for Geilston Bay 
metadata record
http://geonetwork.marvlis.aodn.org.au/geonetwork/srv/en/metadata.show?uuid=25a8ddf6-9cf7-45be-857f-38b344137086

temperature data
http://geonetwork.marvlis.aodn.org.au/marvlis/data/RWQ/GeilstonBay_T.csv

acceptance criteria
The links are corrected and the metadata and data accessible.

(moved from https://github.com/aodn/backlog/issues/476)

**Comment by smancini** [comment]
The MARVLIS Geonetwork catalogue is not accessible.
Can someone clarify the expectation?
Should the MARVLIS catalogue be available again or should the metadata records be made available in another catalogue (catalogue-imos or catalogue-aodn)?
If it is the first solution, who is responsible for getting the MARVLIS Geonetwork catalogue up again?

**Comment by rogerproctor** [comment]
I want the MARVLIS portal and links re-established. There is a good chance that it will form the basis for a more comprehensive Derwent Estuary / Storm Bay portal for aquaculture. Probably move the links to the catalogue-aodn

**Comment by atkinsn** [comment]
@bhasin85 I have fixed the point of truth, and tested the download of the uploaded files to the metadata records, both from the marvlis geonetwork, and aodn geonetwork.
Remaining to be fixed is the link to thredds - will discuss with @bpasquer

**Comment by bpasquer** [comment]
Links to thredds cannot be fixed since this data collection is not on thredds yet. But data is on S3 under Derwent_Estuary_Program/.

**Comment by bpasquer** [comment]
Another broken set of link that need to be fixed are links to datafiles provided in the GetFeature info pop-up in the marvlis portal. I can't access geoserver to fix these links. Can anyone help me with this?

**Comment by pblain** [comment]
@bpasquer - access details are in keypass.  Perhaps @bhasin85 can help you with that.

**Comment by lwgordonimos** [comment]
@bpasquer I've added the dataset to the thredds template and deployed to here:
http://thredds-dev-thredds.ap-southeast-2.elasticbeanstalk.com/

PR: https://github.com/aodn/chef-private/pull/2188

**Comment by bpasquer** [comment]
@lwgordonimos i checked a few files. looks good to me 👍

**Comment by bpasquer** [comment]
and thanks for your help @lwgordonimos
