### ISSUE TITLE
folder named "'/" on data.aodn.org.au root

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#252]
see :
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/
hard to know what created this ? pipeline ? 

![untitled](https://cloud.githubusercontent.com/assets/2382814/20994670/0a624288-bd46-11e6-9442-1b6775a05e29.png)

**Comment by lwgordonimos** [comment]
Looking at the back end, it actually has a directory structure 'mnt/ebs/temp' with a bunch of Future_Reef_MAP files in it, created from about 4.08PM yesterday... was this something someone was running at about that time?

This is the danger of having a "bucket superuser" for everything :/

**Comment by bpasquer** [comment]
I pushed new Future Reef Map through the pipeline yesterday.

**Comment by julian1** [comment]
So a harvester can write anywhere it likes - including other collections?

**Comment by bpasquer** [comment]
The issue comes from the incoming_handler, not the harvester.

**Comment by julian1** [comment]
thanks @bpasquer . would be good if we could use the S3 permissions system to protect against accidents!

**Comment by smancini** [comment]
@bpasquer has updated recently the SOOP-CO2 incoming handler and harvester with the help of @lwgordonimos .
is it possible to remove the folder '/' before closing this issue?

**Comment by lwgordonimos** [comment]
@smancini done. We had fixed it, but an issue with the Jenkins merge job had preventing it from going into prod. 

https://github.com/aodn/data-services/pull/642
