### ISSUE TITLE
aatams sattag dm - databags not updated on AWS10

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#254]
@xhoenner has spent some time trying to figure out why some of his aatams files were not processed.

On aws10, the data bags  ```/mnt/ebs/talend/jobs/aatams_sattag_dm-aatams_sattag_dm/etc/aatams_sattag_dm-aatams_sattag_dm.conf```
contains this line ```exclude=>.*ct91.mdb|.*ct101.mdb|.*ct110.mdb```

However this line was removed on the 21st of December. See
https://github.com/aodn/chef-private/blob/master/data_bags/talend/aatams_sattag_dm.json
https://github.com/aodn/chef-private/commits/master/data_bags/talend/aatams_sattag_dm.json

It seems bizarre that the changes didn't make it to production. How does the system work ? Was a master prod merg supposed to be done on chef-private ? Isn't it an automated process ?

@lwgordonimos ?

Thanks

**Comment by xhoenner** [comment]
@lwgordonimos, has this been resolved?

**Comment by bpasquer** [comment]
Not relevant anymore - The pipeline will soon be decommissioned
