### ISSUE TITLE
SRS L3S 1d composite - night time - LAYER OFFLINE

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#255]
The layer SRS L3S 1d composite - night time is available in step 1. But Step 2 doesn't load the actual layer. Looks like a geoserver/geotnetwork config issue (?).

One of the issue is that this should go into health=bad. 
I think more checks should be performed on this

@pblain

**Comment by julian1** [comment]
https://github.com/aodn/VIT/issues/21

**Comment by lbesnard** [comment]
thanks @julian1 , however i think automated layer testing should be more bombproof

**Comment by julian1** [comment]
I agree with you @lbesnard!
