### ISSUE TITLE
Geoserver Capabilities Request fails in geoserver-123

### ISSUE THREAD

**Issue by kereid** [aodn/content#256]
@lbesnard @jonescc  Logging this as I have just conducted an audit of the Help page links and this had come up again so am just copying the last issue although the error message is different.

Steps to reproduce:

Click http://geoserver-123.aodn.org.au/geoserver/wms?VERSION=1.1.1&REQUEST=GetCapabilities&SERVICE=WMS

What does happen:

Get this error

Content Encoding Error

The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression.

    Please contact the website owners to inform them of this problem.

What should happen:

Get a valid Getcapabilities statement

This this is the same as #212

**Comment by julian1** [comment]
In the past, if GetCapabilites fails it has been treated as a VIT, eg. https://github.com/aodn/internal-discussions/issues/314

**Comment by jonescc** [comment]
Caused by: java.lang.NullPointerException: Layer aatams_sattag_qc_ctd_profile_data has no default style
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayer(GetCapabilitiesTransformer.java:939)
        at org.geoserver.wms.capabilities.GetCapabilitiesTransformer$CapabilitiesTranslator.handleLayerTree(GetCapabilitiesTransformer.java:826)
        ... 100 more

**Comment by kereid** [comment]
Closing as logged in VIT repo

**Comment by julian1** [comment]
@xhoenner is aatams_sattag_qc_ctd_profile_data  one of your layers?

**Comment by xhoenner** [comment]
Yes it's one of mine, weird that this issue arises now though, I haven't modified this layer since I created it [in early November](https://github.com/aodn/geoserver-config/pull/411).

**Comment by julian1** [comment]
It might be another layer next to it in the load sequence.

**Comment by julian1** [comment]
It looks like the style is missing, 

eg. 
```
$ grep -r StyleInfoImpl--1c66b917:1521a4e1b7c:-7ffc .
./workspaces/imos/JNDI_aatams_sattag_qc_ctd/aatams_sattag_qc_ctd_profile_data/layer.xml:    <id>StyleInfoImpl--1c66b917:1521a4e1b7c:-7ffc</id>
```

While the _map does have a style, 

```
$ grep -r StyleInfoImpl-7d713a00:1581d05d8dd:-6924
workspaces/imos/JNDI_aatams_sattag_qc_ctd/aatams_sattag_qc_ctd_profile_map/layer.xml:    <id>StyleInfoImpl-7d713a00:1581d05d8dd:-6924</id>
workspaces/imos/styles/aatams_sattag_qc_ctd.xml:  <id>StyleInfoImpl-7d713a00:1581d05d8dd:-6924</id>
```
