### ISSUE TITLE
No list of urls for IMOS - SRS Satellite - SST L3S - 01 day composite - day time

### ISSUE THREAD

**Issue by julian1** [aodn/content#257]
In download options, I have netcdf but no list of urls,

@atkinsn

**Comment by smancini** [comment]
There is a bit of history around this:
Last year while doing the migration from NSP to AWS, the satellite data was still stored on NSP and so it was not possible to add the appropriate service to have the list of URLS and also the ZIP folder with un-subsetted files.

Then a few months after the migration, Natlia and I configured the following collection "IMOS - SRS Satellite - SST L3S - 01 day composite - night time" with the appropriate online resource in the metadata.
And it is working fine in the portal.

But in the end we have never configured it for all the other collections.
I was worried that if a user is requesting 20 years of data and select "unsubsetted netCDF" option, it will download a large amount of data (>100GB) and put it in a Zip file.

Will it be an issue? 
Should be do more testing?
@pblain

**Comment by pblain** [comment]
Pretty sure it streams - so should be no problem for the server. If the user doesn't like it he can cancel the download. @julian1 ?

**Comment by julian1** [comment]
@pblain

Anything that stuffs individual netcdfs into a zip should be able to stream. Obviously, that doesn't apply to Geoserver WPS because it is fundamentally broken. 

According to @jonescc it is bodaac that is responsible for providing the zip stream of unsubsetted netcdfs - so should be no problem here.

For my part, I wanted the urls to verify an aggregation is working correctly.
