### ISSUE TITLE
Argo profile layer is slow causing issues on geoserver-systest

### ISSUE THREAD

**Issue by jonescc** [aodn/content#259]
Refer https://github.com/aodn/issues/issues/11

**Comment by lbesnard** [comment]
@jonescc the link doesn't work for me

**Comment by jonescc** [comment]
@pblain or @smancini - @lbesnard doesn't seem to have access to the issues repository?

**Comment by julian1** [comment]
I would like access too.

**Comment by pblain** [comment]
@jonescc @julian1 @lbesnard - everyone should have access now
