### ISSUE TITLE
NRS long term hydrological product has wrong link to portal step 2

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#263]
Collection "IMOS - ANMN National Reference Stations - Combined long-term hydrological data product (1944-2014)" doesn't have the right link to "View and download data though the AODN Portal" on step 2 in the Info tab.

**Comment by ggalibert** [comment]
@atkinsn and @mhidas, the metadata record might need to be updated with the right URL.

**Comment by atkinsn** [comment]
Fixed
