### ISSUE TITLE
data.aodn.org.au interface unusable with many objects

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#264]
Access to pages with many folders such as
http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/Argo/dac/aoml/

brings issues on chrome or firefox, 

```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

Script: http://cdn.datatables.net/1.10.2/js/jquery.dataTables.min.js:63
```

FYI @pblain @lwgordonimos

**Comment by pblain** [comment]
@lbesnard - this doesn't look like a data issue that POs can solve.  I've moved it to the issues repo for now.  

https://github.com/aodn/issues/issues/16
