### ISSUE TITLE
AUV - thumbnail creation using image magic - incorrect colors on VM's

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#265]
The AUV viewer uses thumbnails created by https://github.com/aodn/data-services/blob/master/AUV/auv_viewer_processing/auv_processing.py#L180

However there is a colour issue when this runs on PO, AWS10 ...

See for example
```bash
wget https://s3-ap-southeast-2.amazonaws.com/imos-data/IMOS/AUV/WA201204/r20120421_040204_rottnest_05_25m_s_out/i20120421_040204_gtif/PR_20120421_041129_089_LC16.tif

convert PR_20120421_041129_089_LC16.tif -resize 453x341 out.png
display out.png
```
![bad](https://cloud.githubusercontent.com/assets/2382814/23112987/f1cd3b10-f788-11e6-80b7-cf99ce00e0f5.png)

The version of image magick / convert on this machine is 6.6.9-7 .

However on my personal machine with a imageMagick version of 6.8.9-9 gives me the appropriate results
![good](https://cloud.githubusercontent.com/assets/2382814/23113056/6fb77720-f789-11e6-99a9-dc9cc834bcce.png)

@leigh, I don't know if the issue is due to imagemagick version. Would you have an idea of what could be the reason ?

@rogerproctor FYI re your email with Ari
@smancini FYI

**Comment by smancini** [comment]
@lbesnard Is it now all fixed?
Can this issue be closed?
