### ISSUE TITLE
FW: SOOP TRV - lat lon issues

### ISSUE THREAD

**Issue by pblain** [aodn/content#266]
**From:	Jessica Benthuysen <J.Benthuysen@aims.gov.au>
To:	Peter Blain <peter.blain@utas.edu.au>
Subject:	FW: SOOP TRV - lat lon issues
Date:	Mon, 20 Feb 2017 10:26:31 +1000 (20/02/17 11:26:31)**

Hi Peter,

I’m following up about the SOOP-TRV data accessed from the AODN Portal.

I checked the portal and it looks like the data is still only available as a csv or python file. The downloaded csv file only goes to 2009-05-29, corresponding to line 1000021.
 
From the AIMS Data Catalogue, the data is available as a netcdf file (for example http://data.aims.gov.au/aimsrtds/datatool.xhtml?trip=6521&project=100; Export Data -> Netcdf). It’s also possible to download all historical data as a netcdf file. The exported files are separate for temperature, salinity, turbidity, and chlorophyll. I’m not sure the methods involved in joining the data from different trips and converting it into the different formats.
 
...
 
Cheers,
Jessica

**Comment by pblain** [comment]
@smancini - perhaps this task should be allocated to @kereid so that she can follow up with Jessica. This issue came up at the IMSO annual planning. We should probably provide her with an update.

**Comment by pblain** [comment]
@smancini , @kereid - can someone follow up on this?

**Comment by lbesnard** [comment]
Just saw this old issue, which is not really one.

SOOP TRV files are downloaded as a current job from AIMS to our AWS10 machine. There is one NetCDF file per variable; salinity, conductivity, temperature and turbidity individual NetCDF file.

Once the files are downloaded, they are pushed to the INCOMING_DIR where the SOOP TRV talend harvester will run. The harvester merges the 4 different files/variable as they come into the harvester (one variable per NetCDF) into one table. The data merging is based on the TIME variable.

The files are available at http://thredds.aodn.org.au/thredds/catalog/IMOS/SOOP/SOOP-TRV/catalog.html
