### ISSUE TITLE
S3 ANFOG storage is almost entirely consumed by old versions

### ISSUE THREAD

**Issue by pblain** [aodn/content#268]
There are 1,964,195 objects in the ANFOG S3 storage.
Only 3,482 of these are current versions.  The other 99.8% are old versions.
See the following example:
IMOS/ANFOG/REALTIME/seaglider/Lizard20170110/sg540_xsec_density_last48hr.png

**Comment by lwgordonimos** [comment]
The proposed rules will look like:

Scope:
prefix: IMOS/ANFOG/REALTIME

Expiration:
Previous version
Permanently delete previous versions: After 90 days from becoming a previous version

**Comment by smancini** [comment]
Bene and I are happy with the rule.
Needs a confirmation from @pblain 

Then Leigh and I can implement the rule.

**Comment by pblain** [comment]
Our draft backup policy says that we will retain previous versions of non-SRS data for 6 months. 
We can either keep these ANFOG files for 6 months (consistent with other data collections), OR change the backup policy to make ANFOG/REALTIME a special case (i.e. 90 days). Probably easiest to go with an across-the-board six month policy. But I'm not sure how many unwanted PNGs this would accumulate.

**Comment by pblain** [comment]
Correction ... I should have said that previous versions of AUV will be retained for 6 months, not "non-SRS". So the policy will be to keep AUV and ANFOG/REALTIME previous versions for 6 months. We won't retain any previous versions of SRS. And we will retain other previous versions indefinitely - or at least until they become an issue. Sorry for the confusion - my mistake.

**Comment by lwgordonimos** [comment]
So that would mean the following two new rules?

### ANFOG
**Scope:**
prefix: IMOS/ANFOG/REALTIME

**Expiration:**
Previous version
Permanently delete previous versions: After 183 days from becoming a previous version

### AUV
**Scope:**
prefix: IMOS/AUV

**Expiration:**
Previous version
Permanently delete previous versions: After 183 days from becoming a previous version

**Comment by pblain** [comment]
One last question: how many duplicate PNGs do we get in each 183 day period? Will the new rules resolve the issue?

**Comment by bpasquer** [comment]
Reopening since the abovementioned solution hasn't been implemented.  Browsing to imos-data/IMOS/ANFOG/REALTIME/slocum_glider still produces a delay. The issue needs to be rediscussed.

**Comment by ocehugo** [comment]
Not sure if related, but I also notice a considerable delay in getting ANFOG/realtime from opendap addresses too.

**Comment by bpasquer** [comment]
Resolved by https://github.com/aodn/backlog/issues/1128
