### ISSUE TITLE
ANMN new data products to handle (PAR and CDOM data)

### ISSUE THREAD

**Issue by mhidas** [aodn/content#272]
We've received data from a couple of new WetLabs instruments (ECO-Triplet and ECO-PARSB) that the current pipeline doesn't know what to do with because it doesn't fit any of the existing categories (temperature, CTD_timeseries, Velocity, etc...). We also have no harvester, db schema or Geoserver layers for these data.

Long/standard names for the data variables in these files are:
* downwelling_photosynthetic_photon_flux_in_sea_water (PARSB)
* concentration_of_coloured_dissolved_organic_matter (ECO-Triplet)
* volume_scattering_function_of_radiative_flux_in_sea_water_for_wavelength_470nm (ECO-Triplet)
* volume_scattering_function_of_radiative_flux_in_sea_water_for_wavelength_532nm (ECO-Triplet)

**Comment by mhidas** [comment]
Sample files in ` 10-aws-syd:/mnt/ebs/wip/ANMN/NRS/error/new_category/` and 
`10-aws-syd:/mnt/ebs/wip/ANMN/QLD/new_category/`

**Comment by mhidas** [comment]
These files from both sub-facilities have been moved to
`10-aws-syd:/mnt/ebs/wip/ANMN/error_files/new_category/`

**Comment by atkinsn** [comment]
@mhidas are you able to let me know which moorings theses instruments are on?

**Comment by mhidas** [comment]
This may be incomplete, but here's what I know (site codes) based on the files we have:
ECO-Triplet: only at NRSROT
ECO-PARS: GBRHIS, GBRMYR, GBRPPS, NRSYON

**Comment by ggalibert** [comment]
PAR and CDOM are currently found in "Biogeochem_timeseries". It is not unusual to see them collected at the same time as other biogeochem variables. When collected alone, we could continue to put them in "Biogeochem_timeseries" for consistency.

**Comment by mhidas** [comment]
@ggalibert I agree.
