### ISSUE TITLE
Link to some Glider QC documents in Get feature info pop up does not work

### ISSUE THREAD

**Issue by kereid** [aodn/content#274]
Steps to reproduce:

In the portal from step 1 Add IMOS - Australian National Facility for Ocean Gliders (ANFOG) - delayed mode glider deployments

Select StormBay20160913 from the deployment name drop down

On the map click the glider icon to open the GFI

Select the link to Read the Quality Control report.

What should happen:

Report downloads in a new tab

What does happen:

Get eroor:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>IMOS/ANFOG/slocum_glider/StormBay20160913/StormBay20160913_QC_Report.pdf</Key><RequestId>7339CEDAD3941ADD</RequestId><HostId>UjHpNcuwjjUOg6ZjP1mJMpXKn8wR9rvl/XbXgaqrPHM4lCtIeOKwzgEf+M4bAz3l8ZxwRJLIo9Q=</HostId></Error>

**Comment by bpasquer** [comment]
This link as well as other broken path  to QC_reports have been fixed.
