### ISSUE TITLE
Glider showing on land on portal

### ISSUE THREAD

**Issue by kereid** [aodn/content#277]
Adding this in as although @bpasquer and I are aware of the steps we have followed to rectify which is to request reprocessing/correcting from the glider facility, no-one else is. Plus we now have users reporting it too. So putting here for official record.

Steps to reproduce:

Add DM Glider collection on step 1 of the portal, look at sa

What should happen:

there is nothing on the Australian land mass

What does happen:

There is a Yamba glider on the Australian land mass

**Comment by bpasquer** [comment]
I've just emailed ANFOG and asked for these missions to be reprocessed

**Comment by pblain** [comment]
What are we going to do about it in mean time? @smancini

**Comment by bpasquer** [comment]
It's been like this for a while now. I've been told that these missions are going to be reprocessed this week.

**Comment by bpasquer** [comment]
The corrected missions have been uploaded. There is no more glider missions on land
