### ISSUE TITLE
SRS SST migration to generic schema [follow up]

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#279]
This is a short summary of the migration of SRS data to the generic timestep harvester to enforce consistency with gogoduck. OC data is not yet covered

|layer name| generic schema  | prod availability   | comments |
|---|---|---|---|
srs_ghrsst_l3s_14d_dn_url | yes | yes
srs_ghrsst_l3s_1d_dn_url | yes | yes
srs_ghrsst_l3c_1d_ngt_n19_url | yes | yes
srs_ghrsst_l3s_1dS_dn_url | yes | yes
srs_ghrsst_l3s_14d_ngt_url | yes | yes
srs_ghrsst_l3s_3d_day_url | yes | yes
srs_ghrsst_l3s_14d_day_url | yes | yes
srs_ghrsst_l3c_3d_ngt_n19_url | yes | yes
srs_ghrsst_l3c_1d_S_day_n19_url | yes | yes
srs_ghrsst_l3c_1d_S_ngt_n19_url | yes | yes
srs_ghrsst_l3s_6d_dn_url | yes | yes
srs_ghrsst_l3s_1d_day_url | yes | yes
srs_ghrsst_l3s_3d_dn_url | yes | yes
srs_ghrsst_l3s_6d_ngt_url | yes | yes
srs_ghrsst_l3u_n19_url | yes | yes
srs_ghrsst_l3c_3d_day_n19_url | yes | yes
srs_ghrsst_l3u_S_n19_url | yes | yes
srs_ghrsst_l3s_6d_day_url | yes | yes
srs_ghrsst_l3c_1d_day_n19_url | yes | yes
srs_ghrsst_l3s_1d_ngt_url | yes | yes
srs_ghrsst_l3s_3d_ngt_url | yes | yes
srs_ghrsst_l3s_1m_dn_url | yes | no | compliant only 2015->now. Files to reprocess : 2009->2015
srs_ghrsst_l3s_1m_day_url  | yes | no |compliant only 2015->now. Files to reprocess : 2009->2015
srs_ghrsst_l3s_1m_ngt_url | yes | no |compliant only 2015->now. Files to reprocess : 2009->2015
srs_ghrsst_l3s_1mS_dn_url  | yes | no |compliant only 2015->now. Files to reprocess : 2009->2015
srs_ghrsst_l3p_url | no | no | files aren't cf/ghrsst compliant

@atkinsn , to finalise the transition of SRS layers using the new generic timestep schema, we need to do for the above layers (where __prod availability__ is set to yes) the following on catalogue-123
* modify the IMOS:NCWMS--proto distribution link to  __layer name__/sea_surface_temperature
* modify theOGC:WPS--gogoduck distribution link  to  __layer name__
* add the BODACC link when missing

Example:
IMOS:NCWMS--proto
srs_ghrsst_l3c_1d_day_n19_url/sea_surface_temperature

OGC:WPS--gogoduck
srs_ghrsst_l3c_1d_day_n19_url

Many files didn't pass neither of the CF nor GHRSST checkers. They need to be reprocessed by the SRS facility in order to have them indexed via the generic timestep harvester. This list is available on AWS 10 at ```$WIP_DIR/SRS/backlog_files_not_compliant```.  36842 didn't pass the checkers, mainly products we don't serve on the portal.

**Comment by lbesnard** [comment]
10/05/18:
recontacted Edward to reprocess the l3s monthly files from the start -> 2015

**Comment by lbesnard** [comment]
30/04/19:
recontacted Edward

**Comment by lbesnard** [comment]
srs_ghrsst_l3s_1m_dn_url
srs_ghrsst_l3s_1m_day_url
srs_ghrsst_l3s_1m_ngt_url

where updated to contain all data

**Comment by atkinsn** [comment]
All metadata updated

**Comment by lbesnard** [comment]
:)
