### ISSUE TITLE
Problem Layers

### ISSUE THREAD

**Issue by akashisama** [aodn/content#280]
CSV of time taken for layers to seed in geowebcache, using 1 thread, zoom levels 0-5: https://gist.github.com/akashisama/e8a90c651e4b219ebe8671f436ce82ff

And here we have the number of times  the online resource monitor has switched a particular layer on catalogue portal to health bad in the last 30 days. Obviously CARS is a problem. SRS layers seem to be generally problematic although no individual SRS layer has broken more than once.

| Layer | Count |
| ------ | ------- |
| CARS 2009 - CSIRO Atlas of Regional Seas - World monthly  | 54 |
| IMOS - Argo Profiles  | 5 |
| Nearshore temperature monitoring in Tasmanian coastal waters  | 5 |
| Growth and age across range extension region of Centrostephanus rodgersii in eastern Tasmania and morphometric comparison of urchins inhabiting kelp versus barrens habitats  | 4 |
| IMOS - SRS Satellite - SST L3S - 06 day composite - night time  | 1 |
| IMOS - SRS Satellite - SST L3S - 06 day composite - day and night time composite  | 1 |
| IMOS - SRS SATELLITE - SST L3S - 03 day composite - night time  | 1 |
| IMOS - SRS SATELLITE - SST L3S - 01 day composite - Southern Ocean - day and night time composite  | 1 |
| IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite  | 1 |
| IMOS - SRS Satellite - SST L3S - 03 day composite - day and night time composite  | 1 |
| IMOS - SRS Satellite - SST L3S - 14 day composite - night time  | 1 |
| IMOS - SRS Satellite - SST L3S - 14 day composite - day time  | 1 |
| IMOS - SRS Satellite - SST L3S - 14 day composite - day and night time composite  | 1 |
| IMOS - ANMN National Reference Stations - Darwin and Yongala - Near real-time meteorology and oceanographical data  | 1 |
| IMOS - SRS Satellite - SST L3S - 06 day composite - day time  | 1 |
| IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time  | 1 |
| IMOS - SRS Satellite - SST L3S - 01 day composite - night time  | 1 |
| IMOS - SRS SATELLITE - SST L3C - 01 day composite - NOAA-19 - day time  | 1 |
| IMOS - SRS SATELLITE - SST L3C - 01 day composite - NOAA-19 - night time  | 1 |

**Comment by ggalibert** [comment]
Regarding CARS: https://github.com/aodn/issues/issues/15
