### ISSUE TITLE
GoGoDuck aggregation failed for srs_sst_l3s_1m_dn_gridded_url

### ISSUE THREAD

**Issue by jonescc** [aodn/content#282]
A timeseries at a point aggregation failed for this collection last night trying to append variable "aerosol_dynamic_indicator" from 20160531092000-ABOM-L3S_GHRSST-SSTfnd-AVHRR_D-1m_dn.   This file doesn't contain this variable.

Looks like aggregations for this collection aren't restricted to the variables present in all files.  I think this problem was introduced with the changes made to use the new templating mechanism for srs_ghrsst collections.

Perhaps gogoduck.xml needs to select a specific template for this collection which includes only the variables present in all files e.g.

      <template match="srs_sst.*">srs_ghrsst</template>

@lbesnard?

The aggregation request (requested by harry.clarke@research.uwa.edu.au) was:

[request.txt](https://github.com/aodn/content/files/1073046/request.txt)

**Comment by kereid** [comment]
I have emailed Harry and let him know it's an issue on our end and that I will give him an estimate of when it will be fixed later today.

**Comment by lbesnard** [comment]
@jonescc the specific ghrsst template doesn't contain this variable though
https://github.com/aodn/geoserver-config/blob/master/wps/srs_ghrsst.xml

**Comment by jonescc** [comment]
Its currently using the default template which doesn't specify the specific variables to be included in the aggregation as srs_sst_l3s_1m_dn_gridded_url doesn't match any other template.

**Comment by lbesnard** [comment]
After investigating further, the reason is that for this collection and 4 other ones (as can be see in this table https://github.com/aodn/content/issues/279), only a small part of the entire collection was compliant to make it through the generic timestep harvester. So the metadata records for those collections still refer to the old geoserver layers. 

As @jonescc suggested, I will use the same template as for srs_ghrsst.

**Comment by lbesnard** [comment]
https://github.com/aodn/geoserver-config/pull/455

**Comment by kereid** [comment]
@lbesnard @jonescc can I let Harry know this  is resolved (saw you merged something) or does it still need to run through overnight processes before it is? Thanks

**Comment by jonescc** [comment]
@kereid, will restart geoserver when we merge it into production and there's a large aggregation being performed at the moment and a few in the queue after it.  Unlikely for those to be finished before I leave today - I'll check tomorrow morning.

**Comment by kereid** [comment]
Ok thanks

**Comment by jonescc** [comment]
Queue clear this morning.  Changes have been deployed and I am able to include the file causing the problem above now.

**Comment by pblain** [comment]
How will we prevent this sort of error from from reaching production in the future?

**Comment by jonescc** [comment]
Not sure - this was a config change that caused aggregations for this collection not to work for some time ranges (the aggregation which failed was for 1992 - 2016 and it got to 2016 before it found a file it couldn't append because it didn't have all the variables previously included).  Only way to pick that up would have been to try to run a full collection aggregation.  I think checking in the pipeline that we have all the minimum required variables is something we've discussed before - but that assumes we have the aggregations configured properly.

**Comment by pblain** [comment]
Should it be a requirement that config changes are tested against the entire data collection before releasing to prod?

**Comment by jonescc** [comment]
@pblain, in theory yes, but in practice that would require a full aggregation of all collections to catch regressions like this - on a single queue that would take weeks if not months.  Perhaps wait to see if this a regular occurrence before requiring that.
