### ISSUE TITLE
ABOS SOFS collections should mention SOTS site

### ISSUE THREAD

**Issue by mhidas** [aodn/content#283]
Feedback from ABOS facility staff:
> On the data portal, what is searched by the keywords search for a data collection? If I search for SOTS in the search box, only get the ABOS-SOTS-SOFS all delayed mode data, not the other data collections like real time, currents, temperature-salinity collection.

The other collections don't come up because their metadata records don't mention SOTS at all. It would make sense to add in a reference to the "Southern Ocean Time Series (SOTS)" site, as that is where the SOFS mooring is located

**Comment by mhidas** [comment]
@atkinsn Could you take a look please?

**Comment by atkinsn** [comment]
Will do @mhidas

**Comment by atkinsn** [comment]
Done - and will show up tomorrow after the next harvest @mhidas

**Comment by mhidas** [comment]
Thanks @atkinsn !
