### ISSUE TITLE
Should burst-averaging code produce a file with zero meaningful data in it?

### ISSUE THREAD

**Issue by mhidas** [aodn/content#284]
[This file](https://github.com/aodn/content/files/1084135/IMOS_ANMN-QLD_CKOSTUZ_20110309T215957Z_GBRHIS_FV02_GBRHIS-1103-WQM-14-burst-averaged_END-20120103T062944Z_C-20170421T081813Z.nc.ZIP) ended up in the error directory only because it failed the IMOS checker. The `geospatial_vertical_min/max` attributes (both set to 0.0) didn't match the range of any depth variable.  There is a `NOMINAL_DEPTH` variable, with value 14.0, and a `DEPTH` variable which is *all* FillValues. 

In fact, there isn't a single data value in the file that is not a FillValue, and the comment (copied from the imput file) explains it:
> Status mode changed to manual during setup. Instrument ran a full deployment but skipped ahead on the time stamp at various times. All sensors performing only partial plot available. NTU noisy. Coin battery 3.045V, UPS battery 0.001V with some rust on terminals. Flagged all data as Flag 3: Bad but potentiall correctable until the time issue can be resolved. ...

Two suggestions:
* If the `DEPTH` variable has no valid values, `geospatial_vertical_min/max` should be set to the value of `NOMINAL_DEPTH` (if it exists).
* If it turns out that *none* of the variables have any valid values, maybe we shouldn't bother producing the file at all?

@smancini @ggalibert @lbesnard Any thoughts?

**Comment by ggalibert** [comment]
> If the DEPTH variable has no valid values, geospatial_vertical_min/max should be set to the value of NOMINAL_DEPTH (if it exists).

Definitely agree.

> If it turns out that none of the variables have any valid values, maybe we shouldn't bother producing the file at all?

This is not an easy question to answer. Some might say that they want to see the file just because then we know it is not missing. If missing, some might think the original file hasn't been processed by the burst averaging code. I would be tempted to leave the file with nothing in it available. 

Might be good to contact the data provider to ask them what they would prefer?

**Comment by smancini** [comment]
I agree with both comments made by Guillaume

**Comment by lbesnard** [comment]
> If it turns out that none of the variables have any valid values, maybe we shouldn't bother producing the file at all?

Maybe a generic comment can be added in the global attributes to mention there is no valid data ?

**Comment by ggalibert** [comment]
> Maybe a ~~generic~~ comment can be added in the global attributes to mention there is no valid data ?

Good idea, this should be done by the data provider via the deployment database.

**Comment by mhidas** [comment]
Ok, so the general consensus is that we *do* want to produce and publish such a file, with an appropriate comment in the global attributes.

In the example above, the input file *did* have a comment explaining that all data had been flagged as "3: Bad but potentially correctable". This was copied into the product, where its meaning is a bit less clear because that file has no QC flags, though the `lineage` attribute does explain that data flagged 3 and above were excluded. 

How about something like this in the product's `comment` attributre?
> This product contains no valid data, because all input values were excluded by the algorithm used. See the 'lineage' attribute, and metadata in the input file for more details. Comment from input file: *<input_file_comment_text>*" ;

**Comment by ggalibert** [comment]
Sounds good to me.

**Comment by lbesnard** [comment]
@mhidas I could not find the new FV01 file (produced in 2017 and not 2012) on http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/ANMN/QLD/GBRHIS/Biogeochem_timeseries/ to reproduce this and make sure the code will be updated properly
