### ISSUE TITLE
Moorings on land in WA - WATR50

### ISSUE THREAD

**Issue by kereid** [aodn/content#289]
Not sure if this is known about couldn't see an issue in here 

Steps to reproduce:

Add ANMN Temp and Salinity Timeseries or ANMN Current velocity timeseries to map, zoom in on map to WA.

What should happen:
All moorings are in the water

What does happen:
WATR50 is displayed on land

**Comment by mhidas** [comment]
Thanks @kereid. I have asked the data processor to correct the location in the files.

**Comment by mhidas** [comment]
... and he's fixed it already!

**Comment by kereid** [comment]
@mhidas that's great news!
