### ISSUE TITLE
Download of Acoustic Tracking QC data takes a really long time to start

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#291]
Go to http://portal-rc.aodn.org.au/search?uuid=0ede6b3d-8635-472f-b91c-56a758b4e091.

Apply the following filters:

![screen shot 2017-08-25 at 9 44 54 am](https://user-images.githubusercontent.com/3443821/29693616-1a9c1ff6-897a-11e7-8e37-047dd6c31f0b.png)

Go to step 3, download as csv. Here's the output of the log for this particular request. Took over 6 minutes to start downloading a file of 440 KB...

```bash
GET /geoserver/ows?typeName=imos:atf_acoustic_qc_detections_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((148.7548828125%20-37.0908203125%2C148.7548828125%20-32.4326171875%2C152.9736328125%20-32.4326171875%2C152.9736328125%20-37.0908203125%2C148.7548828125%20-37.0908203125)))%20AND%20detection_timestamp%20%3E%3D%20'2016-01-01T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2016-03-01T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202&downloadToken=1503617480703" took 367283ms
```

@smancini could this be planned for in the next iteration? Leigh and I have been banging our heads on this performance issue on and off for over a week, mentioned it briefly to @jonescc yesterday.

**Comment by jonescc** [comment]
I can't get this to take anywhere near 6 minutes - not sure what was going on there - it does take a while to start (around 20 seconds) and that's because the filters applied are against separate indexes (spatial/other), the number of records involved and  because postgres is currently trying to minimise the total cost of the query and not the time to start returning data (something we've had issues before with in the past)

Looking at the execution plan below:

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Hash Join  (cost=127628.30..2724626.23 rows=5497 width=378)
   Hash Cond: (d.file_id = m.file_id)
   ->  Bitmap Heap Scan on qc_detections_data d  (cost=127187.04..2723930.73 rows=5497 width=217)
         Recheck Cond: ((geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry) AND (geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry))
         Filter: (("Detection_QC" <= 2) AND (timezone('UTC'::text, detection_timestamp) >= '2016-01-01 00:00:00+00'::timestamp with time zone) AND (timezone('UTC'::text, detection_timestamp) <= '2016-03-01 23:59:59.999+00'::timestamp with time zone) AND _st_intersects(geom, '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry))
         ->  Bitmap Index Scan on qc_detections_data_gist_idx  (cost=0.00..127185.67 rows=3352125 width=0)
               Index Cond: ((geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry) AND (geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry))
   ->  Hash  (cost=390.56..390.56 rows=4056 width=169)
         ->  Seq Scan on tag_metadata m  (cost=0.00..390.56 rows=4056 width=169)
(9 rows)
```

postgres is choosing to perform an index scan on the spatial index first using a bitmap to record the location of each page containing data.   It then fetches each record on the pages selected and applies the other filter conditions on detection_timestamp and Detection_qc to determine what records it should actually return.

The problem here is that it has to perform the full index scan before it can start returning any records.  

If I turn bitmap heap scans off for my session:

```
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop  (cost=0.70..9853260.71 rows=5497 width=378)
   ->  Index Scan using qc_detections_data_gist_idx on qc_detections_data d  (cost=0.42..9828155.73 rows=5497 width=217)
         Index Cond: ((geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry) AND (geom && '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry))
         Filter: (("Detection_QC" <= 2) AND (timezone('UTC'::text, detection_timestamp) >= '2016-01-01 00:00:00+00'::timestamp with time zone) AND (timezone('UTC'::text, detection_timestamp) <= '2016-03-01 23:59:59.999+00'::timestamp with time zone) AND _st_intersects(geom, '0103000020E61000000100000005000000000000002898624000000000A08B42C0000000002898624000000000603740C000000000281F634000000000603740C000000000281F634000000000A08B42C0000000002898624000000000A08B42C0'::geometry))
   ->  Index Scan using tag_metadata_file_idx on tag_metadata m  (cost=0.28..4.52 rows=1 width=169)
         Index Cond: (file_id = d.file_id)
(6 rows)
```

Then I can get the query returning records almost immediately but at a much greater overall cost.

**Comment by jonescc** [comment]
Not suggesting we should turn bitmapscans off or change the way postgres chooses execution plans - those are quite drastic actions.   Just illustrating whats going on here.  

I'll have a look at whether we can shard the query somehow.

**Comment by jonescc** [comment]
I couldn't reproduce the reported 6 minutes to start the download for this request.   In RC I consistently get around 20 seconds for this particular request to start delivering data, and its likely to be faster in production (was less than 10 seconds on my laptop).

The long start time (20 seconds in RC) is for this particular combination of filters/filter constraints - the spatial index by itself returns over 3 million hits and postgres then has to check each one to see if the records should be filtered out because of other filter conditions.  If the spatial filter was smaller or larger, other filters were omitted or the other filters could filter out more records the query wouldn't take as long to start.  Other requests will probably not not take anywhere near as much time as this.

We would need to revisit our strategy for delivering this type of data to improve on this or reduce the amount of data we make available.  Please raise a backlog item if you wish to pursue this option further.

**Comment by xhoenner** [comment]
Thanks @jonescc for looking into this in great details. It seems like quite an erratic behaviour indeed. The first download request I made this morning didn't even succeed, see the attached screenshot (and nothing in the rc log advising of this download failure), however all subsequent ones worked and were completed in a timely manner.

![screen shot 2017-09-04 at 9 58 39 am](https://user-images.githubusercontent.com/3443821/30007788-d9bd31d6-9159-11e7-8f52-dc2a86b1f1bf.png)

**Comment by jonescc** [comment]
OK - yes that one takes a while for me as well the first time.  I'll see if I can work out why.

**Comment by jonescc** [comment]
Runs in milliseconds on my laptop - something seriously wrong with 2-nec-hob at the moment.

**Comment by jonescc** [comment]
So for some reason yesterday morning, it was consistently taking 15 minutes to start returning data from this query on 2-nec-hob.   The apache timeout is 5 minutes and so the portal would fall over with a gateway timeout error (the query would continue to run in geoserver until it tried to return some data).

Later on in the day it was taking 5 minutes and the settled down to around 22 seconds.

Not quite sure why that was happening.  I suspect something else running on the machine or an environmental issue.   I've started a regular performance check to test the performance of the query and log performance statistics for the database and the machine to try and identify what the issue is.

Note that at the moment the cold start time (after postgres restart) for this query is around 72 seconds and the warm start time is around around 22 seconds.

**Comment by jonescc** [comment]
Looking a bit closer at the 22 second start time, I notice postgres isn't able to use the index on detection_timestamp on the underlying table as detection_timestamp isn't exposed in the view.  timezone('UTC'::text detection_timestamp) is exposed instead.  Queries using timezone('UTC', detection_timestamp) can't take advantage of an index on detection_timestamp.

Suggest you add an index on ('UTC'::text, detection_timestamp) on the underlying table.  That should speed up some queries (more than halves the time to do the query above on my laptop).

Another thing I notice is that detection_timestamp (and other timestamps in your schema) is defined as timestamp without time zone.  This isn't recommended for timestamps in postgres databases as a change in the underlying timezone of the database can change what these timestamps represent.

In other collections, timestamps are defined as timestamp with time zone and converted to UTC in views using AT TIME ZONE 'UTC' (or timezone('UTC',..)) to workaround geoserver time zone issues.

**Comment by jonescc** [comment]
Also, your current index on detection_timestamp is actually on url then detection_timestamp.    Was that intentional?

**Comment by jonescc** [comment]
I also had a look at partitioning the table into separate tables as described in https://www.postgresql.org/docs/9.6/static/ddl-partitioning.html

The ddl used to do this was: (https://github.com/aodn/content/files/1283584/create_qc_detections_data.txt)
[partitioned-table.txt](https://github.com/aodn/content/files/1283586/partitioned-table.txt)

This was generated using template parent/table definitions defined in a freemarker template: 
[create_qc_detections_data.txt]

On my laptop this reduced the cold start time for this query from 12 seconds to 20 ms

Something to look at a bit closer perhaps.   We'd need to do a lot of benchmarking of different types of queries before we went down this path.

**Comment by jonescc** [comment]
Slowed down last night starting at 18:20

```
Thursday 7 September  18:00:01 AEST 2017 Execution time: 22398.368 ms
Thursday 7 September  18:20:01 AEST 2017 Execution time: 665486.428 ms
Thursday 7 September  18:40:01 AEST 2017 Execution time: 623929.578 ms
Thursday 7 September  19:00:01 AEST 2017 Execution time: 612181.449 ms
Thursday 7 September  19:20:01 AEST 2017 Execution time: 620043.751 ms
Thursday 7 September  19:40:01 AEST 2017 Execution time: 515250.977 ms
Thursday 7 September  20:00:01 AEST 2017 Execution time: 624774.370 ms
Thursday 7 September  20:20:01 AEST 2017 Execution time: 666531.320 ms
Thursday 7 September  20:40:01 AEST 2017 Execution time: 259650.096 ms
Thursday 7 September  21:00:01 AEST 2017 Execution time: 24578.402 ms
Thursday 7 September  21:20:01 AEST 2017 Execution time: 24579.228 ms
Thursday 7 September  21:40:01 AEST 2017 Execution time: 493042.989 ms
Thursday 7 September  22:00:01 AEST 2017 Execution time: 40165.486 ms
Thursday 7 September  22:20:01 AEST 2017 Execution time: 23239.312 ms
Thursday 7 September  22:40:01 AEST 2017 Execution time: 22064.340 ms
'

**Comment by jonescc** [comment]
There was some other activity happening in the database at this time:

```
Thursday 7 September  18:20:01 AEST 2017
 datid | datname |  pid  | usesysid |          usename          | application_name | client_addr  | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin |                                                                                                                                                                                                                                                                                                                                         query                                                                                                                                                                                                                                                                                                                                          
-------+---------+-------+----------+---------------------------+------------------+--------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 16512 | harvest | 15930 |    65243 | aatams_acoustic_reporting |                  | 144.6.238.48 |                 |       41884 | 2017-09-07 08:01:53.258404+00 |                               | 2017-09-07 08:02:07.947834+00 | 2017-09-07 08:02:07.951439+00 |                 |            | idle   |             |              | INSERT INTO "aatams_acoustic_reporting"."project" ("id","name","is_protected") VALUES ($1,$2,$3)
 16512 | harvest | 15946 |    65243 | aatams_acoustic_reporting |                  | 144.6.238.48 |                 |       41886 | 2017-09-07 08:02:07.959871+00 | 2017-09-07 08:20:01.995493+00 | 2017-09-07 08:20:02.144904+00 | 2017-09-07 08:20:02.144905+00 |                 |            | active |     3733358 |      3733358 | INSERT INTO "aatams_acoustic_reporting"."valid_detection" ("id","receiver_deployment_id","timestamp","transmitter_id","receiver_name") VALUES ($1,$2,$3,$4,$5)
 16512 | harvest | 19785 |       10 | postgres                  |                  |              |                 |             | 2017-09-07 08:12:12.895677+00 | 2017-09-07 08:12:12.934989+00 | 2017-09-07 08:12:12.934989+00 | 2017-09-07 08:12:12.934994+00 |                 |            | active |             |      3732779 | autovacuum: VACUUM ANALYZE aatams_acoustic_reporting.valid_detection
 16512 | harvest | 21235 |    16493 | craigj                    | psql             | 127.0.0.1    |                 |       48488 | 2017-09-07 08:20:01.783454+00 | 2017-09-07 08:20:01.80758+00  | 2017-09-07 08:20:01.80758+00  | 2017-09-07 08:20:01.807587+00 |                 |            | active |             |      3733358 | explain analyze SELECT "id","file_id","url","transmitter_id","tag_id","release_id","tag_project_name","common_name","scientific_name","installation_name","station_name","detection_timestamp","longitude","latitude","sensor_value","sensor_unit","FDA_QC","Velocity_QC","Distance_QC","DetectionDistribution_QC","DistanceRelease_QC","ReleaseDate_QC","ReleaseLocation_QC","Detection_QC","release_longitude","release_latitude","ReleaseDate","sensor_slope","sensor_intercept","sensor_type","tag_sensor_unit","tag_model_name","tag_serial_number","tag_expected_life_time_days","tag_status","sex","measurement","dual_sensor_tag",encode(ST_AsEWKB("geom"),'base64') as "geom"+
       |         |       |          |                           |                  |              |                 |             |                               |                               |                               |                               |                 |            |        |             |              |   FROM "aatams_acoustic_qc"."atf_acoustic_qc_detections_data"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
       |         |       |          |                           |                  |              |                 |             |                               |                               |                               |                               |                 |            |        |             |              |  WHERE  ("geom" && ST_GeomFromText('POLYGON ((148.7548828125 -37.0908203125, 148.7548828125 -32.4326171875, 152.9736328125 -32.4326171875, 152.9736328125 -37.0908203125, 148.7548828125 -37.0908203125))', 4326)                                                                                                                                                                                                                                                                                                                                                                                                                                                                     +
       |         |       |          |                           |                  |              |                 |             |                               |                               |                               |                               |                 |            |        |             |              |    AND ST_Intersects("geom", ST_GeomFromText('POLYGON ((148.7548828125 -37.0908203125, 
 16512 | harvest | 21236 |    16493 | craigj                    | psql             | 127.0.0.1    |                 |       48490 | 2017-09-07 08:20:01.784423+00 | 2017-09-07 08:20:01.807551+00 | 2017-09-07 08:20:01.807551+00 | 2017-09-07 08:20:01.807553+00 |                 |            | active |             |      3733358 | select * from database_activity()
(5 rows)

Thursday 7 September  18:40:01 AEST 2017
 datid | datname |  pid  | usesysid |          usename          | application_name | client_addr  | client_hostname | client_port |         backend_start         |          xact_start           |          query_start          |         state_change          | wait_event_type | wait_event | state  | backend_xid | backend_xmin |                                                                                                                                                                                                                                                                                                                                         query                                                                                                                                                                                                                                                                                                                                          
-------+---------+-------+----------+---------------------------+------------------+--------------+-----------------+-------------+-------------------------------+-------------------------------+-------------------------------+-------------------------------+-----------------+------------+--------+-------------+--------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by jonescc** [comment]
Looks like aatams_acoustic_reporting was running during this time period.

**Comment by jonescc** [comment]
Don't believe this will be an issue in production as geoserever is running off a replicated database where this activity is not occurring.  @lwgordonimos ?

**Comment by jonescc** [comment]
Perhaps we should be running geoserver-rc off a replicated database to confirm?

**Comment by jonescc** [comment]
May also be just that this db is not specced high enough to handle this workload.

**Comment by jonescc** [comment]
Note that a rule of thumb for when to partition a table is when the size of the table exceeds the physical memory of the database server.

Partitioning reduces the memory requirements for processing queries of this type by the number of partitions used.

| relation | size |
| --- | --- |
|anfog_dm.measurements|39 GB|
|argo.profile_measurements|27 GB|
|aatams_acoustic_qc.qc_detections_data|13 GB|
|dw_aatams_acoustic.qc_detections_data|12 GB|
|dw_aatams_acoustic.valid_detection|9584 MB|
|argo.profile_measurements_pkey|9377 MB|
|anfog_dm.measurement_gist_idx|8809 MB|
|aatams_acoustic_reporting.valid_detection|8033 MB|
|aatams_acoustic_qc.qc_detections_data_idx|7937 MB|
|dw_aatams_acoustic.qc_detections_data_idx|7461 MB|
|anfog_dm.measurements_time_idx|4917 MB|
|anfog_dm.measurements_file_id_idx|3475 MB|
|anfog_dm.measurements_pkey|3448 MB|
|dw_aatams_acoustic.qc_detections_data_gist_idx|2771 MB|
|aatams_acoustic_qc.qc_detections_data_gist_idx|2643 MB|
|aatams_acoustic_qc.qc_detections_data_file_idx|1353 MB|

Note above that aatams_acoustic_reporting tables also have large indexes.

So some options here are increasing the amount of memory on 2-nec-hob, examining whether running off a replicated db helps, partitioning the tables, or reducing the amount of data we are trying to server.

**Comment by jonescc** [comment]
Actually, replication probably won't help if someone is doing a query on two large relations at a time.

**Comment by xhoenner** [comment]
I addressed @jonescc feedbacks in https://github.com/aodn/content/issues/291#issuecomment-327681434 and https://github.com/aodn/content/issues/291#issuecomment-327683996 through https://github.com/aodn/harvesters/pull/545. Those changes were deployed on rc and the corresponding harvester then ran successfully. 

  * 1st test this morning got me the exact same result as in https://github.com/aodn/content/issues/291#issuecomment-326841873, i.e. didn't even succeed.
  * 2nd test returned ~8,100 rows of data (3.8MB) after 9.3s.
  * 3rd test returned ~380 rows of data (172KB) after 137.1s.
  * 4th test returned ~48,000 rows of data (23.6MB) after 38.2s.
  * 4th test returned ~5,900 rows of data (2.8MB) after 6.3s.

**Comment by jonescc** [comment]
@xhoenner - can you capture the queries you are performing when you are doing these tests.  Can then use them for benchmarking/testing any changes.

**Comment by jonescc** [comment]
Would also be good if you can capture database_activity when you are having issues so we can confirm or deny previous findings.

**Comment by xhoenner** [comment]
No query was running against db-rc when I did those four tests except my own database_activity() query and geoserver-rc queries to produce the csv outputs.

* 1st test
```bash
CQL_FILTER=INTERSECTS(geom%2CPOLYGON((150.52230834962%20-34.941619873047%2C150.52230834962%20-34.782318115235%2C150.77
774047853%20-34.782318115235%2C150.77774047853%20-34.941619873047%2C150.52230834962%20-34.941619873047)))%20AND%20detection_timestamp%20%3E%3D%20'2010-04-01T00%3A
00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2010-06-01T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202%20AND%20common_name%20LIKE%20'Australian%20B
ass'
```
--> Took 6.6 secs, file size=3.1MB

* 2nd test
```bash
CQL_FILTER=detection_timestamp%20%3E%3D%20'2012-09-10T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2012-
09-12T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202%20AND%20common_name%20LIKE%20'Great%20Hammerhead'
```
--> Took 0.4 secs, file size=12KB

* 3rd test 
```bash
CQL_FILTER=detection_timestamp%20%3E%3D%20'2014-10-10T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2014-12-10T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202%20AND%20tag_project_name%20LIKE%20'Shark%20and%20ray%20movements%20patterns%20at%20Ningaloo%20Reef'```

--> Took 58 secs, file size=430KB

* 4th test
```bash
CQL_FILTER=INTERSECTS(geom%2CPOLYGON((135.6591796875%20-44.7373046875%2C135.6591796875%20-31.6416015625%2C153.6767578125%20-31.6416015625%2C153.6767578125%20-44.7373046875%2C135.6591796875%20-44.7373046875)))%20AND%20detection_timestamp%20%3E%3D%20'2015-07-15T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2015-10-15T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202
```

--> Took 37.2 secs, file size=4.2MB

**Comment by jonescc** [comment]
When you say took 58 secs - is that total time or time to start downloading?

**Comment by xhoenner** [comment]
> When you say took 58 secs - is that total time or time to start downloading?

This is the time reported in the geoserver-rc log, e.g.

```bash
13 Sep 23:16:06 INFO [geoserver.filters] - 144.6.238.217 "GET /geoserver/ows?typeName=imos:atf_acoustic_qc_detections_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=INTERSECTS(geom%2CPOLYGON((135.6591796875%20-44.7373046875%2C135.6591796875%20-31.6416015625%2C153.6767578125%20-31.6416015625%2C153.6767578125%20-44.7373046875%2C135.6591796875%20-44.7373046875)))%20AND%20detection_timestamp%20%3E%3D%20'2015-07-15T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2015-10-15T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202&downloadToken=1505344529424" took 37154ms
```

**Comment by jonescc** [comment]
Hmm... for me running the above queries in rc:

1 -> 2.218 secs
2 -> 0.109 secs
3 -> 1.075 secs
4 -> 5.130 secs

I'll have a look at the logs for when you were running these queries this morning and if nothing leaps out at  me I'll start running the regular performance monitoring queries I was doing before.  Hopefully next time this happens for you we'll be able to see what's happening.

**Comment by jonescc** [comment]
Have set up cronjobs to run all queries you ran this morning that took more than a couple of seconds and to capture system processing info on 3-nec-hob/2-nec-hob every 20 minutes.

Let me know when if you have find queries are taking longer than 10 seconds and I'll check the logs

**Comment by xhoenner** [comment]
Tried again this morning, nothing was running against db-rc.

1 --> 11.5 secs (6.8 MB)
```bash
CQL_FILTER=INTERSECTS(geom%2CPOLYGON((148.89221191406%20-36.12951660
1563%2C148.89221191406%20-34.437622070313%2C151.59484863281%20-34.437622070313%2C151.59484863281%20-36.129516601563%2C148.89221191406%20-
36.129516601563)))%20AND%20detection_timestamp%20%3E%3D%20'2011-01-01T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2011-03-
01T23%3A59%3A59.999Z'%20AND%20Detection_QC%20%3C%3D%202%20AND%20common_name%20LIKE%20'Dusky%20Flathead'
```

2 --> 77.3 secs (3.8 MB)

``` bash
CQL_FILTER=INTERSECTS(geom%2CPOLYGON((149.1064453125%20-25.4892578125%2C149.1064453125%20-21.1826171875%2C154.6435546875%20-21.1826171875%2C154.6435546875%20-25.4892578125%2C149.1064453125%20-25.4892578125)))%20AND%20detection_timestamp%20%3E%3D%20'2010-06-09T00%3A00%3A00.000Z'%20AND%20detection_timestamp%20%3C%3D%20'2010-09-09T23%3A59%3A59.999Z'
```

How did you go with your cronjobs @jonescc?

**Comment by jonescc** [comment]
All running fine,  but as discussed - I'm testing downloads from geoserver-rc and your testing downloads via portal-rc, so I need to look closer at what's going on with portal-rc as that appears to be the bottleneck.

**Comment by xhoenner** [comment]
Tested on both @jonescc's and my machine, all seems to be working as expected now.
