### ISSUE TITLE
csiro_oa_reconstruction layer name doesn't follow conventions

### ISSUE THREAD

**Issue by jonescc** [aodn/content#295]
gridded data url layers are normally suffixed with _url .  This is throwing out nagios which is treating it like a wms layer.

**Comment by akashisama** [comment]
On a related note, the get map url of [WAMSI NODE 3.4.2](https://catalogue-portal.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=67984a64-c5bd-485d-8ace-7b0b22806ffa) ends in "_data"
