### ISSUE TITLE
FAIMMS time values in CSV

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#296]
**It appears:**

1- the time provided in the CSV for FAIMMS is indeed local time. It is too bad that the time zone information is not provided like AIMS does.

AIMS data:

date time | date | time | seconds since 1970 | Wind Speed (Scalar avg 30 min) Lizard Island Weather Station_LEVEL0_value_RAW
-- | -- | -- | -- | --
2016-06-01T00:00:00+1000 | 2016-06-01 | 00:00:00 | 1464703200 | 45.612
2016-06-01T00:30:00+1000 | 2016-06-01 | 00:30:00 | 1464705000 | 44.676

IMOS data:

TIME | VALUES
-- | --
2016-06-01T00:00:00 | 45.612
2016-06-01T00:30:00 | 44.676

2- this local time is not consistent with the one provided by AIMS. It's like if we were trying to apply Daylight Saving Time while in QLD since 1992, there hasn't been any application of DST.

AIMS data:

date time | date | time | seconds since 1970 | Wind Speed (Scalar avg 30 min) Lizard Island Weather Station_LEVEL0_value_RAW
-- | -- | -- | -- | --
2016-11-01T00:00:00+1000 | 2016-11-01 | 00:00:00 | 1477922400 | 27.1836
2016-11-01T00:30:00+1000 | 2016-11-01 | 00:30:00 | 1477924200 | 27.0144

IMOS data:

TIME | VALUES
-- | --
2016-11-01T01:00:00 | 27.1836
2016-11-01T01:30:00 | 27.0144

**What we would like:**

Ideally, we want to provide correct times in UTC.

**Comment by lbesnard** [comment]
thanks @ggalibert , this should fix it https://github.com/aodn/harvesters/pull/554

**Comment by ggalibert** [comment]
@lbesnard there are 2 issues that need addressing:
1. We need to output the time zone in the string provided by the CSV file. So if we intend to provide UTC time we need to add Z at the end of the string for example. I don't think the fix you mention above is going to fix this.
2. The harvested time needs to be in UTC and stored as such so that then when you query it in UTC you get a consistent value. I suppose this is what your fix above is about.
