### ISSUE TITLE
Organisation missing?

### ISSUE THREAD

**Issue by pblain** [aodn/content#298]
Seems strange that these search results have the IMOS logo but don't have IMOS as an organisation. If they're CSIRO records, and not funded by IMOS, shouldn't they have a CSIRO logo? But if they're IMOS records shouldn't IMOS be listed as one of the organisations?
![image](https://user-images.githubusercontent.com/2802359/32466765-307ed03c-c39c-11e7-99c6-9526e07fc3f2.png)

**Comment by atkinsn** [comment]
The records are a copy from records held at CSIRO. They are IMOS datasets, and the decision was made at the time that we would host these metadata records for CSIRO, and only edit them to the bare minimum (add data parameters and online resources to power the Portal). IMOS is attributed in the suggested citation in the CC license details.

**Comment by lbesnard** [comment]
@atkinsn  can be closed ?

**Comment by atkinsn** [comment]
IMOS info was added so yes.
