### ISSUE TITLE
FAIMMS CSV header missing header

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#299]
The CSV output of FAIMMS is missing the header information explaining what the different columns are.

From what I (mis?)understand about this conversation: https://github.com/aodn/content/issues/297
It seems like there won't be any 'Z' added to the TIME string values because of the missing header info.

**Comment by jonescc** [comment]
All imos collections served from geoserver-portal use the csv_with_metadata format even if there is no metadata to be displayed so all imos collections should return time values as UTC.

#297 changes are currently in systest so the actual behaviour can be verified there.   And now would be a good time to do so.

**Comment by pblain** [comment]
@lbesnard - Could you please let me (or Seb) know what to do with this after you've taken a look?

**Comment by lbesnard** [comment]
The 'Z' part of the Time value is now there. However the CSV file is still missing its header

@xhoenner @smancini

**Comment by xhoenner** [comment]
This is due to the fact that there's no faimms_metadata_summary view in the parameters_mapping schema. @smancini has to update the [parameters_mapping.csv file](https://github.com/aodn/data-services/blob/master/PARAMETERS_MAPPING/parameters_mapping.csv) before that view can be created in Talend.

**Comment by lbesnard** [comment]
https://github.com/aodn/data-services/pull/925

**Comment by lbesnard** [comment]
@bpasquer , the change on the parameter mapping was done, deployed on RC. However the change didn't do anything via portal-rc. Anything I'm missing ?

**Comment by bpasquer** [comment]
Yes there is still no faimms_metadata_summary view in the parameters_mapping schema. The view has to be created in the harvester. I'll take care of it if you want.

**Comment by lbesnard** [comment]
done. working on Prod
