### ISSUE TITLE
Python option download in Satellite Relay Tagging Program - Delayed mode data

### ISSUE THREAD

**Issue by pblain** [aodn/content#300]
Ref: https://github.com/aodn/aodn-portal/issues/2576

**Comment by xhoenner** [comment]
@jonescc suggested it's a metadata issue so @atkinsn this is for you :neckbeard:

**Comment by atkinsn** [comment]
Just speaking to @xhoenner , as we were looking at another collection with multi-WFS (IMOS - AATAMS Facility - Satellite Relay Tagging Program - Delayed mode data), and we think that this has how it has always displayed in Step 3 of the Portal. 
So "python" always displays at the top of the download options, and when you have multi-WFS, the portal config has only been done to assign CSV options, and has left python at the top. Xav has pointed out that in his example, the python download is only relevant to the first type of data - CTD profile - so yes it does need to be changed, as it is confusing.

So looks like the config needs to be changed to move python down to sit under the corresponding correct data type.

**Comment by ggalibert** [comment]
I'm renaming this issue, looks like it has been fixed for Marvl3.
![Screenshot from 2020-04-22 16-51-15](https://user-images.githubusercontent.com/3498686/79949847-872e5c00-84b9-11ea-9a9f-220f3ba5a7b9.png)

**Comment by ggalibert** [comment]
Currently we have the following for Satellite Relay Tagging Program - Delayed mode data
![Screenshot from 2020-04-22 16-50-08](https://user-images.githubusercontent.com/3498686/79950094-e12f2180-84b9-11ea-85c5-fd9f16ec5459.png)
I have looked at the content of the Python file and it looks all good to me. Maybe thanks to some recent work from @evacougnon, @bpasquer  and @lbesnard . I believe we can close this issue.
