### ISSUE TITLE
Issue aggregating csiro_oa_reconstruction

### ISSUE THREAD

**Issue by jonescc** [aodn/content#301]
Got the following error from gogoduck when an end user tried to subset this collection over the weekend:

    Process failed during execution Could not read url substitutions for csiro_oa_reconstruction

Refer https://portal.aodn.org.au/wps/jobReport?server=http%3A%2F%2Fgeoserver-wps.aodn.org.au%2Fgeoserver%2Fows&uuid=1dc3981e-e246-4c11-b4f1-bc03532ab2f6

**Comment by jonescc** [comment]
Apparently this has been resolved since this error occurred.   Thanks @bpasquer @kereid 

@akashisama, this is the type of problem that the WPS check in the online resource monitor used to detect and remove the collection from portal.  @pblain - does the priority of restoring this checking need to be upped?

**Comment by jonescc** [comment]
Content issue has been fixed

**Comment by pblain** [comment]
> does the priority of restoring this checking need to be upped?

Yes, included in this iteration
