### ISSUE TITLE
SOOP CO2 RT tracks dissappearing

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#302]
The SOOP CO2 RT layer has been deployed to prod yesterday.
The number and length of voyage tracks appearing depend on the zooming level.

**Comment by jonescc** [comment]
May be related to https://github.com/aodn/issues/issues/138

**Comment by akashisama** [comment]
Related to https://github.com/aodn/internal-discussions/issues/386 and https://github.com/aodn/backlog/issues/720
