### ISSUE TITLE
portal-systest WPS testing - Issue in data content of CARS2009 dataset

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#304]
I started an aggregation with the __CARS 2009 - CSIRO Atlas of Regional Seas - World monthly__ data set:
https://wps-systest.aodn.org.au/wps/jobStatus?jobId=6f7a0d8a-c1fc-460b-a271-2efdfe6512ce&format=HTML

Here is the downloaded file:
[output-3.txt](https://github.com/aodn/content/files/1561227/output-3.txt)

DAY_OF_YEAR (UTC) | DEPTH (m) | LATITUDE (degrees_north) | LONGITUDE (degrees_east) | TEMP (Celsius) | TEMP_mean (Celsius) | TEMP_std_dev (Celsius)
-- | -- | -- | -- | -- | -- | --
2009-01-31T00:00:00Z | 0 | -40 | 140.5 | 16.823275 | 14.761617 | 1.6972518
2009-01-31T00:00:00Z | 50 | -40 | 140.5 | 14.592245 | 13.929517 | 1.2246654
2009-01-31T00:00:00Z | 200 | -40 | 140.5 | 11.458295 | 11.898265 | 0.9544504
2009-01-31T00:00:00Z | 1000 | -40 | 140.5 | 4.6380963 | 4.7381473 | 0.38850656
2009-01-31T00:00:00Z | 5000 | -40 | 140.5 | 0.91918576 | __25__ | 34.72123

__The TEMP_MEAN data is rising back to 25 degrees at 5000m !__ Maybe there is a volcano there, but I doubt this is handled by this climatology dataset.

Joking apart, i haven't tested if it was similar with the non systest version of the portal. However I suspect this is due to the variables not having the same amount of dimensions.

__For example__, see the original NetCDF file ncdump output:
http://thredds.aodn.org.au/thredds/dodsC/CSIRO/Climatology/CARS/2009/AODN-product/CARS2009_World_monthly_01.nc.info

TEMP: | Grid    coordinates:  DAY_OF_YEAR LATITUDE LONGITUDE DEPTH
-- | --
-> 4 dimensions

BUT

TEMP_mean: | Grid    coordinates:  LATITUDE LONGITUDE DEPTH
-- | --
-> 3 dimensions

I'm wondering how the difference of dimension is handled and I suspect the issue is most likely there than in the new WPS features.

@smancini @pblain @ggalibert @jonescc

**Comment by lbesnard** [comment]
Did a similar job but at a different point. This is better, but still highlight some issues on other variables
https://wps-systest.aodn.org.au/wps/jobStatus?jobId=591730ce-2664-4a8c-b959-08e030e2c687&format=HTML

**Comment by jonescc** [comment]
The 25 is for TEMP_sumofwgts. I think the columns have gotten out of whack above.

Looks to me like we are getting the same output with the old gogoduck. 

As discussed in review, non-time dependent variables aren't included in the aggregation process.  The first one encountered (i.e. from the first file) is subsetted spatially and included as an assumed non-varying variable as per previous ncrcat behaviour.   If this is not required we would need to add the required functionality as an option to the aggregator and should probably remove the variable from the aggregation until its implemented.

**Comment by jonescc** [comment]
Needs input from @ggalibert on whether current processing for TEMP_mean etc is correct.  If these values need to be recalculated based on the subsetted result of the TEMP variable for example, then this would require supporting functionality to be added to the aggregator and a task to do this should be added as a new backlog item.

**Comment by ggalibert** [comment]
Looks all good to me.

my CSV subset at a point shows:

DAY_OF_YEAR (UTC) | DEPTH (m) | LATITUDE (degrees_north) | LONGITUDE (degrees_east) | TEMP (Celsius) | TEMP_mean (Celsius) | TEMP_std_dev (Celsius) | TEMP_RMSspatialresid (Celsius) | TEMP_RMSresid (Celsius) | TEMP_sumofwgts (null) | TEMP_map_error (Celsius) | TEMP_anomaly (Celsius)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2009-01-01T00:00:00Z | 0 | -43.5 | 146 | 14.669466 | 13.702211 | 1.3893459 | 1.434575 | 0.7364229 | 566 | 0.030732607 | 0.96725464
2009-01-01T00:00:00Z | 50 | -43.5 | 146 | 13.312264 | 13.253979 | 1.3157035 | 1.3238215 | 0.6998917 | 593 | 0.028993027 | 0.058285713
2009-01-01T00:00:00Z | 200 | -43.5 | 146 | 11.248193 | 11.396686 | 0.80658597 | 0.7764332 | 0.6448049 | 395 | 0.03247219 | -0.14849281
2009-01-01T00:00:00Z | 1000 | -43.5 | 146 | 4.268288 | 4.4076266 |   |   |   | 231 |   | -0.1393385
2009-01-01T00:00:00Z | 5000 | -43.5 | 146 |   |   |   |   |   | 0 |   |  

while the equivalent susbset performed with ncks on the original file gives:
```
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 DAY_OF_YEAR(1)=1 TEMP(45716)=14.6695 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 DAY_OF_YEAR(1)=1 TEMP(284367)=13.3123 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 DAY_OF_YEAR(1)=1 TEMP(523018)=11.2482 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 DAY_OF_YEAR(1)=1 TEMP(761669)=4.26829 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 DAY_OF_YEAR(1)=1 TEMP(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_RMSresid(45716)=0.736423 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_RMSresid(284367)=0.699892 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_RMSresid(523018)=0.644805 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_RMSresid(761669)=_ Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_RMSresid(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_RMSspatialresid(45716)=1.43457 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_RMSspatialresid(284367)=1.32382 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_RMSspatialresid(523018)=0.776433 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_RMSspatialresid(761669)=_ Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_RMSspatialresid(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 DAY_OF_YEAR(1)=1 TEMP_anomaly(45716)=0.967255 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 DAY_OF_YEAR(1)=1 TEMP_anomaly(284367)=0.0582857 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 DAY_OF_YEAR(1)=1 TEMP_anomaly(523018)=-0.148493 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 DAY_OF_YEAR(1)=1 TEMP_anomaly(761669)=-0.139338 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 DAY_OF_YEAR(1)=1 TEMP_anomaly(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_map_error(45716)=0.0307326 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_map_error(284367)=0.028993 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_map_error(523018)=0.0324722 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_map_error(761669)=_ Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_map_error(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_mean(45716)=13.7022 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_mean(284367)=13.254 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_mean(523018)=11.3967 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_mean(761669)=4.40763 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_mean(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_std_dev(45716)=1.38935 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_std_dev(284367)=1.3157 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_std_dev(523018)=0.806586 Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_std_dev(761669)=_ Celsius
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_std_dev(1000320)=_ Celsius

LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(1)=0 TEMP_sumofwgts(45716)=566 
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(2)=50 TEMP_sumofwgts(284367)=593 
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(3)=200 TEMP_sumofwgts(523018)=395 
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(4)=1000 TEMP_sumofwgts(761669)=231 
LONGITUDE(293)=146 LATITUDE(64)=-43.5 DEPTH(5)=5000 TEMP_sumofwgts(1000320)=0
```

**Comment by ggalibert** [comment]
> As discussed in review, non-time dependent variables aren't included in the aggregation process. The first one encountered (i.e. from the first file) is subsetted spatially and included as an assumed non-varying variable as per previous ncrcat behaviour.

This is the expected behaviour, thanks.

**Comment by ggalibert** [comment]
@lbesnard I have read the file you attached and it displays fine in LibreOffice Cal. No volcano at the bottom of the ocean...
![screenshot from 2018-01-17 15-40-55](https://user-images.githubusercontent.com/3498686/35026037-d3cd82c8-fb9c-11e7-97d4-f68132016ca1.png)
