### ISSUE TITLE
SOOP-TMV empty folders thredds

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#305]
thredds empty folders
http://thredds.aodn.org.au/thredds/catalog/IMOS/SOOP/SOOP-TMV/VLST_Spirit-of-Tasmania-1/realtime/transect/10secs/2017/12/catalog.html

@bpasquer

**Comment by bpasquer** [comment]
These folders contain the original realtime files (log files) only. The pipeline is meant to be updated in the future to convert these log files to NetCDF.
