### ISSUE TITLE
Download Error 

### ISSUE THREAD

**Issue by kereid** [aodn/content#310]
A user tried to download CARS 2009 - CSIRO Atlas of Regional Seas - World Monthly CSV at a point for the whole of the temporal extent, and an error was produced: 

Exception occurred during aggregation :For input string: "${Z_MAX}"

The Xml for the failed job which I reproduced in systest is: 
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:Execute service="WPS" version="1.0.0" xmlns:ns2="http://www.opengis.net/wps/1.0.0" xmlns:ns1="http://www.opengis.net/ows/1.1" xmlns:ns3="http://www.w3.org/1999/xlink">
    <ns1:Identifier>gs:GoGoDuck</ns1:Identifier>
    <ns2:DataInputs>
        <ns2:Input>
            <ns1:Identifier>layer</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>csiro_cars_monthly_url</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>subset</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>TIME,2009-01-01T00:00:00.000Z,2009-12-03T00:00:00.000Z;LATITUDE,-16.3964,-16.3964;LONGITUDE,122.9275,122.9275</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>callbackUrl</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>
                    https://portal-systest.aodn.org.au/wps/jobComplete
               </ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
        <ns2:Input>
            <ns1:Identifier>callbackParams</ns1:Identifier>
            <ns2:Data>
                <ns2:LiteralData>email.to=kate.reid@utas.edu.au</ns2:LiteralData>
            </ns2:Data>
        </ns2:Input>
    </ns2:DataInputs>
    <ns2:ResponseForm>
        <ns2:ResponseDocument storeExecuteResponse="true" status="true">
            <ns2:Output asReference="true" mimeType="text/csv">
                <ns1:Identifier>result</ns1:Identifier>
            </ns2:Output>
        </ns2:ResponseDocument>
    </ns2:ResponseForm>
</ns2:Execute>

There have been a few error emails lately that don't have helpful errors,but turn out to be content so putting it straight in here. I have assigned to @pblain as I'm not sure if a developer will need to look into logs etc to work out where the issue is or if a PO can see what they need

**Comment by jonescc** [comment]
Looks like template changes for CARS Z_MAX attribute overrides have been merged into prod geoserver-config (https://github.com/aodn/geoserver-config/blob/master/wps/templates.xml#L39)  before the supporting code changes have made it to prod (https://github.com/aodn/geoserver-build/blob/master/src/aggregator/src/main/java/au/org/emii/aggregator/template/TemplateDataset.java#L161).  Template changes should be removed from prod geoserver-config until supporting code is in prod.

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/geoserver-config/pull/539
