### ISSUE TITLE
Portal breaks trying to look at bathymetry collection on single machine

### ISSUE THREAD

**Issue by pblain** [aodn/content#311]
See here: https://github.com/aodn/aodn-portal/issues/2611

**Comment by pblain** [comment]
@ggalibert - yeah wasn't implying there was anything incorrect with the files - only that they don't render fast enough - and that the issue belongs in this repo.

**Comment by ggalibert** [comment]
I have just uploaded a new version of Victorian-coast_Bathy_500m.nc that has been regridded on a geographic grid. @jonescc let me know if that works better. The file size 370Kb is significantly smaller due to the fact we don't need to store the lat/lon couple values for each point any more.
