### ISSUE TITLE
'abos_ts_timeseries_data' view causing Geoserver outages

### ISSUE THREAD

**Issue by pmbohm** [aodn/content#312]
https://github.com/aodn/issues/issues/170

Needs modifications to the SQL view

**Comment by mhidas** [comment]
Any advice on what modification is required? What's causing the "sequential scans"?

The discussion at https://github.com/aodn/issues/issues/170 suggests that removing the sort on TIME might help, but won't completely solve the problem. Generally users who download data as CSV would expect them to be ordered by time, so ideally we would leave that there.

Also, we already have indexes :
```
abos_ts.timeseries
    "timeseries_pk" PRIMARY KEY, btree (id)
    "timeseries_gist_idx" gist (geom)

abos_ts.measurement
    "measurement_fk" PRIMARY KEY, btree (ts_id, index)
    "measurement_time_idx" btree ("TIME")
```
Is the problem that we don't have a separate index for just `ts_id` in `measurement`, which is being used in the join?

**Comment by mhidas** [comment]
@jonescc @lwgordonimos ?

**Comment by lwgordonimos** [comment]
I don't think so, it would still be doing an index scan if that column is in any index. That said, I'm not 100% sure with composite primary keys in Postgres, so could be wrong. (@jonescc ?)

My thought was that it was simply the volume of data that makes the index slower than just streaming it out of the table.

For example, what percentage of the whole table(s) is that particular query requesting? 

Actual query at: https://github.com/aodn/issues/issues/170#issuecomment-370662245

**Comment by mhidas** [comment]
> what percentage of the whole table(s) is that particular query requesting?

That particular query is requesting pretty much ALL the data as the bounding box includes most of the world. It selects 620 of the 641 files listed in the `timeseries` table.

**Comment by mhidas** [comment]
> My thought was that it was simply the volume of data that makes the index slower than just streaming it out of the table.

Currently there are over 57 million rows in the `measurement` table, so yes, that could be an issue. If you're going to select any reasonable chunk of it, it's also pushing the limit of what's sensible to download in CSV format!

**Comment by lwgordonimos** [comment]
That is what we were suspecting, so I think the indexes are fine.

It definitely is an issue, because while it's streaming the enormous amount of rows from the DB, it's tying up both Geoserver threads and database connections, causing the denial of service.

You're right in that it is pretty ridiculous for a CSV, but the only way to stop it would be to somehow prevent requests over a certain size at the Geoserver level. Not sure what our options are here, because it really needs to be nipped in the bud *before* it makes the crazy requests to the DB.

**Comment by pblain** [comment]
@mhidas , @lwgordonimos , should it be on the backlog?

**Comment by jonescc** [comment]
Don't think there's anything the data services team can do here apart from add appropriate indexes that can be used when filtering - see https://github.com/aodn/issues/issues/170 - the current index on "TIME" cannot be used.

Options for addressing lockups will be looked at under https://github.com/aodn/backlog/issues/822

**Comment by lwgordonimos** [comment]
Closing this, as it's now being handled on the backlog.
