### ISSUE TITLE
thredds order of projects

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#314]
The order of projects on http://thredds.aodn.org.au/thredds/catalog.html used to be in reversed alphabetical order. Somewhat different than http://data.aodn.org.au (which I have always found weird)

However, the order on thredds seems completely random now. ```IMOS``` is at the top, and the rest is reversed. It doesn't seem very clean in my opinion.

**Comment by pmbohm** [comment]
Fixed by https://github.com/aodn/chef-private/pull/2797

**Comment by lbesnard** [comment]
@pblain is it really fixed ?

I can't see any changes on thredds and thredds-rc
and thredds-systest is not accessible

**Comment by ggalibert** [comment]
The requirements of this task were as follow:

What to do:
Go to any directory on THREDDS and look at how files and subdirectories in it are ordered.

What should happened:
Files and subdirectories should appear listed ordered alphabetically. Just like when browsing on S3:

![screenshot from 2018-05-22 10-49-42](https://user-images.githubusercontent.com/3498686/40336669-665d17f2-5dae-11e8-9830-935790fb89c3.png)


What happens:
Files and subdirectories are not following any clear order:

![screenshot from 2018-05-22 10-49-13](https://user-images.githubusercontent.com/3498686/40336673-69f4e8c2-5dae-11e8-9bc2-9ec547d7dac5.png)

**Comment by lwgordonimos** [comment]
The "subdirectories" are not configurable from the catalogue file, only the top level datasetScans.

I suspect this would require a Java code change to order the results appropriately when it queries them out of S3 and builds it's listing, i.e. somewhere in here: https://github.com/aodn/thredds/tree/4.6.x-imos/cdm/src/main/java/thredds/crawlabledataset/s3

@jonescc could you confirm that?

**Comment by pmbohm** [comment]
Yes my change only affects the top level datasetScan which will have to be kept alphabetical if new ones are added. 

Whats needed seems configurable hopefully:
https://www.unidata.ucar.edu/software/thredds/v4.6/tds/reference/DatasetScan.html

**Comment by lwgordonimos** [comment]
I'm wondering how the sort option interacts with the S3 querying under the hood, with things like pagination etc.

Just to avoid a situation like needed to query 10000s of files and sort them on the client side (with the S3 client being the THREDDS server in this case).

I think it needs looking at in the Java level as well to make sure it's optimal.

**Comment by pblain** [comment]
OK, Thanks

**Comment by jonescc** [comment]
Yes, would require java changes to sort the return bucket list.

**Comment by jonescc** [comment]
Hopefully we wouldn't be trying to return very large pages that would take too long to sort - we hit the 1000 limit for a couple of collections I think and had to handle that.

**Comment by jonescc** [comment]
Actually, java changes not required - it is configurable for our s3 extension using the sort option @pmbohm linked to above.

**Comment by pblain** [comment]
Great - Is there anything stopping @ggalibert from going ahead and configuring it?

**Comment by jonescc** [comment]
Its just a config change (which would then need to be deployed by jenkins).  Any one with access to modify the config at https://github.com/aodn/chef-private/blob/master/external_templates/templates/default/thredds/threddsConfig.xml.erb can change it.

Just need to add a sort element to all the datasetScan elements.

**Comment by pblain** [comment]
Do you want to do it @ggalibert ?

**Comment by ggalibert** [comment]
I can try.

**Comment by ggalibert** [comment]
The doc says:
> ### Sorting Datasets
> Datasets at each collection level are listed in ascending order by name. With a sort element you can specify that they are to be sorted in reverse order:
> ```XML
> <sort>
>  <lexigraphicByName increasing="false" />
> </sort>
> ```
> Note that the sort is done before renaming.

Do I really need to add a sort element? The doc seems to suggest that is should be sorted ascending by default no?

**Comment by jonescc** [comment]
Default seems to be descending not ascending - noting that lowercase letters are > uppercase letters

**Comment by ggalibert** [comment]
See also PR #2815 for ebprep template.

**Comment by jonescc** [comment]
Believe this has been resolved now.
