### ISSUE TITLE
Timeouts downloading AATAMS_ACOUSTIC_QC

### ISSUE THREAD

**Issue by jonescc** [aodn/content#318]
Logs show that users are getting timeouts trying to download this collection when filtering by installation_name or transmitter_id.

Looking at the definition of the supporting view/tables for this download it doesn't look like there are any indexes on these columns requiring postgres to examine every record to filter on them.

If we want to be able to filter on these properties we should add supporting indexes to the qc_detections_data table

**Comment by xhoenner** [comment]
Thanks for looking into that @jonescc. Does it mean one separate index for each subsetting option offered or is it more efficient to combine them all into a single index? 

Some of the filters (i.e. species name, sex)  in the [corresponding data collection](https://portal.aodn.org.au/search?uuid=0ede6b3d-8635-472f-b91c-56a758b4e091) come from another table, `tag_metadata`, which only has ~4,000 records. Is it worth adding an index to those fields as well?

**Comment by jonescc** [comment]
@xhoenner I'd start by adding separate indexes on installation_name and transmitter_id.  postgres can make use of multiple indexes where necessary and I'd wait to see if there were any other filter combinations that were causing issues that could be solved by adding composite indexes.

No harm in adding indexes on filters on the map table - may help improve performance.  But the main issue is filtering on the data table
