### ISSUE TITLE
Timeouts downloading anfog_dm

### ISSUE THREAD

**Issue by jonescc** [aodn/content#319]
Refer https://github.com/aodn/backlog/issues/710.  Logs show that users are getting timeouts trying to download this collection when filtering by "TIME".

Looking at the definition of the supporting view/tables for this download it doesn't look like there is any supporting index for filtering on "TIME" as "TIME" for this download is the value of a function -timezone('UTC'::text, m."TIME") (functions are a black box for postgres it can't use the index on "TIME" available on the measurements table)

If we want to be able to filter on "TIME" for this download then we should add a supporting index for this column.  In this case we need to add an index on the result of the function to the measurements table:

    CREATE INDEX measurement_time_idx
              ON anfog_dm.measurements (timezone('UTC'::text, "TIME"));

**Comment by jonescc** [comment]
Note that there is an index on "TIME" on the measurements table which can be used by the sort when postgres decides that its worthwhile, but this can't be used filtering on the "TIME" defined in the view.   Probably should remove the index on measurements "TIME" and sort using timezone('UTC'::text, "TIME") instead to reduce the amount of space taken by indexes when adding the new index on timezone('UTC'::text, "TIME").

**Comment by bpasquer** [comment]
Thanks for the clarification @jonescc. I'll do the necessary changes.

**Comment by bpasquer** [comment]
The measurement table has been reindexed on utc TIME.  @smancini has successfully tested the request that was timing out.
