### ISSUE TITLE
Timeout downloading anmn_ts_timeseries

### ISSUE THREAD

**Issue by jonescc** [aodn/content#321]
Refer aodn/backlog#710. Logs show that users are getting timeouts trying to download this collection when filtering by "TIME".

Looking at the definition of the supporting view/tables for this download it doesn't look like there is any supporting index for filtering on "TIME" as "TIME" for this download is the value of a function -timezone('UTC'::text, m."TIME") (functions are a black box for postgres it can't use the index on "TIME" available on the measurement table)

If we want to be able to filter on "TIME" for this download then we should add a supporting index for this column. In this case we need to add an index on the result of the function to the measurement table:

```
CREATE INDEX anmn_ts_measurement_time_idx
          ON anmn_ts.measurement (timezone('UTC'::text, "TIME"));
```

**Comment by mhidas** [comment]
Thanks @jonescc . I didn't realise that.

I will add that index. Can/should it be added directly to the view?

**Comment by jonescc** [comment]
No you can't add indexes to a view.   You add it to the underlying table and postgres works out it can use it.

**Comment by jonescc** [comment]
Tested locally and it fixes the timeout we had in prod.  Starts returning records immediately.
