### ISSUE TITLE
ADCP files with DIST_ALONG_BEAMS coordinate fail CF checks

### ISSUE THREAD

**Issue by mhidas** [aodn/content#323]
Many FV00 ADCP files created by recent Toolbox versions have a coordinate variable like this:
```
        float DIST_ALONG_BEAMS(DIST_ALONG_BEAMS) ;
                DIST_ALONG_BEAMS:comment = "Data is not vertically bin-mapped (no tilt correction applied). Cells are lying parallel to the beams, at heights above sensor that vary with tilt." ;
                DIST_ALONG_BEAMS:long_name = "distance_from_sensor_along_beams" ;
                DIST_ALONG_BEAMS:reference_datum = "sensor" ;
                DIST_ALONG_BEAMS:units = "m" ;
                DIST_ALONG_BEAMS:valid_max = 12000.f ;
                DIST_ALONG_BEAMS:valid_min = -12000.f ;
```
They also have several data variables that have dimensions `(TIME, DIST_ALONG_BEAMS)`.

With versions 3 and 4 of the compliance-checker, this leads to 
```
                                    Warnings                                    
--------------------------------------------------------------------------------
Name                   Reasoning
§2.4 Dimension Order:  ABSIC1's dimensions are not in the
                       recommended order T, Z, Y, X. They are
                       TIME, DIST_ALONG_BEAMS ABSIC2's
                       dimensions are not in the recommended
                       order T, Z, Y, X. They are TIME,
                       DIST_ALONG_BEAMS ABSIC3's dimensions are
                       not in the recommended order T, Z, Y, X.
                       ... etc ...
```
[CF](http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#dimensions) says:
> If any or all of the dimensions of a variable have the interpretations of "date or time" (T), "height or depth" (Z), "latitude" (Y), or "longitude" (X) then we recommend, but do not require (...), those dimensions to appear in the relative order T, then Z, then Y, then X in the CDL definition corresponding to the file. All other dimensions should, whenever possible, be placed to the left of the spatiotemporal dimensions.

So technically the checker is correct, because `DIST_ALONG_BEAMS` is not _really_ "height or depth".

Two possible solutions:
1. Update the Toolbox to put `DIST_ALONG_BEAMS` before `TIME` where variables have both these dimensions. This would require significant re-processing of existing files.
2. Pretend that `DIST_ALONG_BEAMS` _is_ a real vertical coordinate, and add the attributes 
`standard_name = "height/depth"`
`positive = "up/down"`,
`axis = "Z"`
(all three are required, otherwise other checks will fail)

**Comment by mhidas** [comment]
A third option is we simply skip the dimension order check, but that would mean we don't check any moorings file for this. It's true that it's only _recommended_, not _required_ by CF, but I think we need to be a bit careful about putting in exceptions like this. Perhaps something to consider in a broader context.

**Comment by mhidas** [comment]
@smancini @ggalibert Thoughts?

**Comment by ggalibert** [comment]
How critical is this warning? Is this going to make the checker test "fail"?

I'm not so keen about solution 2.

Would IOOS consider updating their check to take into account the "we recommend, but **do not require**" from CF? Could this be reflected in the level of warning? If not then I'd be happy to fix the toolbox (solution 1). There's already a large amount of ADCP data that needs reprocessing.

**Comment by mhidas** [comment]
IOOS already _have_ taken that into account. That's why it comes up as a "Warning" (level 2), not an "Error" (3). However, we're using 2 as the threshold for failure, so overall the file fails.

See https://github.com/aodn/internal-discussions/issues/410 for a more general discussion on troublesome checks.

**Comment by mhidas** [comment]
All the pipelines handling moorings data will be configured to skip the dimension order check to avoid this issue.

Possibly a future version of the Toolbox could switch the dimensions around for these variables (option 1. above), but we would then have inconsistent data until all ADCP files are re-processed with the new version (i.e. for a _long time_). Probably not worth the effort (@ggalibert ?)

**Comment by ggalibert** [comment]
I've lodged an issue in the toolbox repo to keep track of this: https://github.com/aodn/imos-toolbox/issues/512 . If this is not too painful to implement, I might do it for a next version.

**Comment by ocehugo** [comment]
2 cents:

I can't see how DIST_ALOG_BEAMS is not a spatial dimension. It is just a tilted vertical axis (for that case), so it should be to the right of time.
As a reciprocal, imagine the ADCP lying in the horizontal. DAB would be a tilted x or y-direction, thus to the right.

Moreover, 1 is quite a substantial change from the user and memory access perspective (TIME is always bigger).

I can't see why the attributes can't be added too (they need to be the exact strings as above!?)
my view is that, as long as you provide the information that z=f(DAB,**args), including the attrs should be fine.
