### ISSUE TITLE
incoming/dataupload folder aws10

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#324]
on aws10

I have stumbled across this folder on aws 10
/mnt/ebs/incoming/dataupload

I have never paid attention to it before. It looks likes a temporary folder with files such as
```
test.txt
Test.rar
result.zip
file.txt
DCLOCK.exe
fileassurancetest
index.html
Pics for Chris.zip
```

no comments ... but there are 14 Gb of this important data ...

@aodn/emii-data-team 
@lwgordonimos

**Comment by anguss00** [comment]
Pics for Chris.zip??

**Comment by lbesnard** [comment]
yeah right, prefer not to open that one

**Comment by lwgordonimos** [comment]
My understanding was that this was a general file sharing kind of non-pipeline files.

I'm very much in favour of getting rid of it and using something more suitable like CloudStor (https://www.aarnet.edu.au/network-and-services/cloud-services-applications/cloudstor) for this kind of thing.

FTP needs to die...

**Comment by mhidas** [comment]
Most of the stuff in there is from 2012 or earlier!

I think it's just stuff that was moved here from the the old ftp server, back when it was only used for random files (data from facilities went straight to the Data Fabric!)

**Comment by mhidas** [comment]
There are a few more recent files (modified dates in 2016), could be worth a look if they look familiar to anyone?
```
/mnt/ebs/incoming/dataupload$ ll -t pub/
total 2769460
-rw-rw-r-- 1 ftp users  34543418 Oct 19  2016 MARVL_MainHelp.zip
drwxrwsr-x 5 ftp users      4096 Oct 19  2016 ./
-rw-rw-r-- 1 ftp users     38948 May  9  2016 SAIMOS metadata record 190615.docx
-rw-r--r-- 1 ftp users  22584477 Feb  4  2016 rcowley-upload.tar.gz

/mnt/ebs/incoming/dataupload$ ll -t uploads/ANFOG_ERRORfiles/
total 1662184
drwxrwsr-x 2 bpasquer       users               4096 May 25  2016 ./
-rwxrwxr-x 1 bpasquer       users           69941992 May 25  2016 IMOS_ANFOG_BCEOPSTUV_20130221T100634Z_SL281_FV01_timeseries_END-20130313T012128Z.nc*
-rwxrwxr-x 1 bpasquer       users           81255774 May 25  2016 IMOS_ANFOG_BCEOPSTUV_20130905T081229Z_SL239_FV01_timeseries_END-20131107T001750Z.nc*
d-wxrwsr-x 7 ftp            users              12288 May 25  2016 ../
-r--r--r-- 1 projectofficer projectofficer 354844090 Mar 31  2016 IMOS_ANFOG_BCEOPSTUV_20150311T073916Z_SL248_FV01_timeseries_END-20150331T005409Z.zip
-r--r--r-- 1 projectofficer projectofficer 785247035 Mar 31  2016 IMOS_ANFOG_BCEPSTUV_20111104T122800Z_SL210_FV01_timeseries_END-20111124T234657Z.zip
-r--r--r-- 1 projectofficer projectofficer 410754027 Mar 31  2016 IMOS_ANFOG_BCEOPSTUV_20131120200843Z_SL209_FV01_timeseries_END-20131212022941Z.zip

```

I doubt anything older in there is of much use now, but to be on the safe side, we could zip it all up and put it in the archive.

**Comment by lwgordonimos** [comment]
I vote kill the access immediately (since it hasn't been used for over 2 years), and deal with the files at your leisure. PR created ;)

**Comment by ggalibert** [comment]
I haven't been using this stuff for ages and don't need anything of what's there so happy to delete.

**Comment by bpasquer** [comment]
The ANFOG files and the MARVL_MAinHelp.zip file can be deleted as well.

**Comment by mhidas** [comment]
I just had another look through these directories and deleted a few things, but most of the stuff in there I have no idea about. Anyone else still looking, or shall we just trash the lot?

Most of the files in the "uploads" sub-directory are only read-/write-able by the ftp user, so we'll need to ask @lwgordonimos to delete them.

**Comment by lbesnard** [comment]
just trash it

**Comment by lbesnard** [comment]
@lwgordonimos fee free to rm 
/mnt/ebs/incoming/dataupload

**Comment by lwgordonimos** [comment]
rm-ed
