### ISSUE TITLE
aodn:aodn_nsw_oeh_beachwatch_data generating errors in production logs

### ISSUE THREAD

**Issue by jonescc** [aodn/content#327]
Nagios is currently checking this layer and returning errors as it doesn't seem to have associated data and is not referenced in any metadata records.

Not sure what action should be taken here?  Remove the layer from production?

**Comment by mhidas** [comment]
That's weird. I don't think we have done any work on the beachwatch data yet!?!?
Maybe @atkinsn has created a draft metadata record for it and it accidentally got published?

**Comment by jonescc** [comment]
Its a layer in production geoserver - I couldn't find a metadata record for it.

**Comment by atkinsn** [comment]
@mhidas there is a draft metadata record in RC, but thats all - https://catalogue-rc.aodn.org.au/geonetwork/srv/en/metadata.show?uuid=ffcee3c0-a1f1-47ee-ab90-34c618a88ab5

**Comment by mhidas** [comment]
Sorry, I had forgotten that @xhoenner updated the AODN_NSW_OEH harvester for this data stream, and created the geoserver config back in January. However these were  not meant to be deployed to prod yet as the pipeline is not ready. I've put up a revert PR for now. We'll try to put it back in soon.
