### ISSUE TITLE
Improving links between AODN portal and Oceancurrent - Q4 deliverable 

### ISSUE THREAD

**Issue by rogerproctor** [aodn/content#328]
First candidate for this is to link to the Oceancurrent seals CTD page where the user can see plots of the CTD profiles from all seals; see http://oceancurrent.imos.org.au/aatams.php 

As a PORTAL USER I want to have a link to the Oceancurrent seals CTD page so I can view profile plots.

Requirement
1) Add link to http://oceancurrent.imos.org.au/aatams.php in the "info" tab of layers "IMOS - AATAMS Facility - Satellite Relay Tagging Program - Delayed mode data"; "IMOS - AATAMS Facility - Satellite Relay Tagging Program - Near real-time CTD profile data"; "Satellite relay tagging program - Southern Ocean - MEOP Quality Controlled CTD profiles" in Step 2.

2) Add link to http://oceancurrent.imos.org.au/aatams.php to the Get Feature Info pop-up in Step 2 for layers in 1).

3) Add link to http://oceancurrent.imos.org.au/aatams.php below "view metadata record" on Step 3 for layers in 1). 

Acceptance criteria
When selecting a layer in 1) above, there is a visible link as described in 1), 2), 3) which takes you to http://oceancurrent.imos.org.au/aatams.php

**Comment by atkinsn** [comment]
@rogerproctor due to "rules" that determine where links in the metadata appear within the Portal - I can get that URL to show up at 1 or 3. The only way to get it to show twice is to repeat the link in the metadata (with different protocols - so messy). So if we didn't go that way - which is higher priority: 1 or 3.

2 will have to be actioned by @xhoenner

**Comment by xhoenner** [comment]
> 2. Add link to http://oceancurrent.imos.org.au/aatams.php to the Get Feature Info pop-up in Step 2 for layers in 1).

Those changes have now been deployed to prod, so 2. can be ticked off.

**Comment by atkinsn** [comment]
@rogerproctor turns out you can now get links to show at both 1) and 3). So link to the CTD page has been added to the 3 collections.
