### ISSUE TITLE
500 errors reported for new ncwms layers

### ISSUE THREAD

**Issue by jonescc** [aodn/content#329]
We're currently getting around 1800 500 errors a day for a number of new layers which don't follow existing gridded data layer naming conventions:

imos:bathy_ppb_deakin_map
imos:acorn_wind_qc_sag
imos:acorn_wind_qc_rot
imos:acorn_wind_qc_cof
imos:acorn_wind_qc_cbg
imos:acorn_wave_site_qc_sag
imos:acorn_wave_site_qc_rot
imos:acorn_wave_site_qc_cof
imos:acorn_wave_site_qc_cbg

Nagios relies on this naming convention to apply appropriate checks and is currently testing these layers as normal wms layers throwing errors.  This creates a lot of noise in the logs and makes the elastic beanstalk load balancer for geoserver to consider geoserver unstable with a possible outcome being that that autoscaling replaces the instance.   Refer https://github.com/aodn/chef/blob/master/cookbooks/nagios/libraries/geoserver_helper.rb#L195).  Normally these layers would be suffixed with _url.

Would it be possible to rename these layers according to the naming convention?

**Comment by ggalibert** [comment]
Not sure what is wrong with `imos:bathy_ppb_deakin_map`. Why should it have `_url`? It is used to serve a lower resolution bathymetry on step 2 of portal rather than the higher resolution one `_url` used for download.

**Comment by jonescc** [comment]
Resolved.  That's 2000 less errors we'll get every day in the logs.  Thanks @ggalibert !
