### ISSUE TITLE
SRS Error folders on AWS10 to remove

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#332]
@lwgordonimos 

Some $ERROR_DIR folders for SRS should be deleted in my opinion as they aren't used by any pipelines.
I think some got renamed over the time explaining why they exist.

SRS_GRIDDED_OC/
SRS_SST_GRIDDED/
SRS_GRIDDED_SST/
SRS_GHRSST_GRIDDED/

Happy to sit down with you

**Comment by lbesnard** [comment]
same for 
DEAKIN/BATHYMETRY
Deakin/incoming

I actually don't understand why this ERROR dirs are so messy

**Comment by ggalibert** [comment]
$ERROR_DIR/DEAKIN_BATHY is correct and should be kept.

However $INCOMING_DIR/DEAKIN is not used and can be deleted. $INCOMING_DIR/Deakin is correct and should be kept.

**Comment by ggalibert** [comment]
Additional note: $INCOMING_DIR/Deakin/incoming is not used and can be deleted.

**Comment by lwgordonimos** [comment]
Accordingly to my dodgy script, these are the error directories not "owned" by either pipeline 1 or pipeline 2.

```
SRS_SST_GRIDDED
SRS_GHRSST_GRIDDED
ANMN_NRS_AIMS
SRS_GRIDDED_SST
ACORN_DM_HOURLY_AVG
ACORN_HOURLY_AVG
OA_Reconstruction
SRS_GRIDDED_OC
```

**Comment by ggalibert** [comment]
I agree for the ACORN ones.

**Comment by mhidas** [comment]
These directories are just owned by the projectofficer user, so we could delete them ourselves, but would they be re-created by Chef? @anguss00 @lwgordonimos

**Comment by lbesnard** [comment]
just removed them
