### ISSUE TITLE
Victorian Coastal Digital Elevation Model incorrectly configured

### ISSUE THREAD

**Issue by jonescc** [aodn/content#333]
ncwms abomination is returning not found for this layer.  Refer http://geoserver-portal.aodn.org.au/geoserver/ncwms?service=ncwms&request=GetMap&version=1.1.1&format=image/png&bbox=-180,-90,180,90&srs=EPSG:4326&width=1&height=1&STYLES=&LAYERS=bathy_ppb_deakin_lower_res_url/DEPTH

Looks like the layer is misconfigured in the metadata - there is no DEPTH variable.  DEPTH variable references should be replaced with HEIGHT which does exist?

**Comment by atkinsn** [comment]
We are waiting on someone at Deakin to make the change in their metadata.

**Comment by atkinsn** [comment]
Change has been made, will show up tomorrow.

**Comment by jonescc** [comment]
Resolved.  Thanks @atkinsn

**Comment by ggalibert** [comment]
There will be a problem with `bathy_ppb_deakin_url/DEPTH` though because I haven't been able to upload an updated version of the associated 60Gb file yet. Some more space is needed in `/mnt/ebs`.

**Comment by jonescc** [comment]
Aah OK, I can see that the 500m resoultion file uses HEIGHT and the 10m resolution file uses DEPTH. 
  Nat got Deakin to update the metadata to use HEIGHT for ncwms abomination (the 500m resolution file) which fixes the portal, albeit using HEIGHT under the covers.  If you are updating  Victorian-coast_Bathy_500m.nc to use DEPTH as per the 500m resolution file, then we can update the metadata again once its done.

**Comment by ggalibert** [comment]
There shouldn't be any problem now. I have finally managed to upload an updated version of `bathy_ppb_deakin_url` which now includes HEIGHT. Everything is now using HEIGHT.
