### ISSUE TITLE
acorn layers misconfigured

### ISSUE THREAD

**Issue by jonescc** [aodn/content#334]
Acorn wave and wind layers were recently renamed in geoserver to follow existing naming standards for gridded data layers (suffixed with _url).  I thought the metadata was changed to reflect these changes at the same time, but it appears that these changes have been reverted?  causing issues with these layers in production.

See https://portal.aodn.org.au/search?health=bad for problem layers

**Comment by jonescc** [comment]
Actually looks like the problem is that the OGC:WPS--gogoduck references haven't been updated rather than the previous changes being reverted.

**Comment by jonescc** [comment]
And IMOS:AGGREGATION--bodaac references.

**Comment by ggalibert** [comment]
I didn't think it would be a problem to have a layer name different from the collection_name in the generic harvester. Is it?

**Comment by ggalibert** [comment]
Ah ok, it seems for gogoduck and bodaac we need "collection_name"_url in the metadata record. The "_url" bit being reomoved somehow to query the database.

**Comment by ggalibert** [comment]
I've just performed the required changes. Should be visible tomorrow.

**Comment by jonescc** [comment]
GoGoDuck and Bodaac don't go directly to the database to get the list of files selected.  They go by geoserver which is why they need the same layer name used by ncwms abomination

**Comment by jonescc** [comment]
Resolved.  Thanks @ggalibert
