### ISSUE TITLE
Wave buoy observations CSV without header

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#336]
The following collection: `Wave Buoy Observations, near real-time, Australia` doesn't have any header in the CSV download. There should be one that explains the parameters, units and QC flags involved.

**Comment by bpasquer** [comment]
Yes, I know about this issue. What is the current workflow? Is the query to do the parameter mapping still manually ran @smancini @xhoenner?

**Comment by ggalibert** [comment]
bump

**Comment by bpasquer** [comment]
CSV header now available as demonstrated on RC at the review yesterday, and now in prod
