### ISSUE TITLE
Inconsistent title for SRS OC collections

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#339]
It would be good if the name of the satellite (if any) is found at a consistent place in the title of an SRS collection.

For example at the moment we have:
-`IMOS - SRS - MODIS - 01 day - Ocean Colour - SST`
-`IMOS - SRS SATELLITE - SST L3C - 01 day composite - NOAA-19 - night time`

Maybe we could update the NOAA-19 collections to be renamed to something like:
-`IMOS - SRS - NOAA-19 - SST L3C - 01 day composite - night time`

**Comment by lbesnard** [comment]
it is actually found at a consistent place. Your two examples are about two very different data collections(GHRSST and Ocean Colour).  The GHRSST metadata title follows actually the data hierarchy on thredds which is thought to be the more sensible one
see
http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/L3C-1d/day/n19/catalog.html

Moving the NOAA19 part would result in having weird alphabetical orders as the N19 satellite is included in many products.

Anyway, in a very near future, all L3C's products should disappear

**Comment by ggalibert** [comment]
I'm just trying to highlight the fact that in your metadata record title we could have an harmonised convention. 

Looks like you're handling the following information:
-sub-facility name: SRS or SRS SATELLITE (to be harmonised too!),
-satellite name,
-product type: SST L3C, Ocean Colour - SST?
-composite type: 01 day or 01 day composite (to be harmonised too! Please maybe shortest option)

These 4 information for example could be positioned consistently in the title for example.

**Comment by ggalibert** [comment]
Based on the efforts already made for the MODIS metadata records:
```
IMOS - SRS - MODIS - 01 day - Chlorophyll-a concentration (OC3 model)
IMOS - SRS - MODIS - 01 day - Nanoplankton fraction (OC3 model and Brewin et al 2010 algorithm)
IMOS - SRS - MODIS - 01 day - Nanoplankton fraction (OC3 model and Brewin et al 2012 algorithm)
IMOS - SRS - MODIS - 01 day - Net Primary Productivity (GSM model and Eppley-VGPM algorithm)
IMOS - SRS - MODIS - 01 day - Net Primary Productivity (OC3 model and Eppley-VGPM algorithm)
IMOS - SRS - MODIS - 01 day - Ocean Colour - SST
IMOS - SRS - MODIS - 01 day - Picoplankton fraction (OC3 model and Brewin et al 2010 algorithm)
IMOS - SRS - MODIS - 01 day - Picoplankton fraction (OC3 model and Brewin et al 2012 algorithm)
```

I suggest that we adopt a similar convention for other NOAA SST records. They would be renamed as follow:

Before | After
-- | --
IMOS - SRS - MODIS - 01 day - Ocean Colour - SST | IMOS - SRS - MODIS - 01 day - SST
IMOS - SRS SATELLITE - SST L3C - 01 day composite - NOAA-19 - day time | IMOS - SRS - NOAA - 01 day - SST L3C - day time
IMOS - SRS SATELLITE - SST L3C - 01 day composite - NOAA-19 - night time | IMOS - SRS - NOAA - 01 day - SST L3C - night time
IMOS - SRS SATELLITE - SST L3C - 01 day composite - Southern Ocean - NOAA-19 - day time | IMOS - SRS - NOAA - 01 day - SST L3C - day time - Southern Ocean
IMOS - SRS SATELLITE - SST L3C - 01 day composite - Southern Ocean - NOAA-19 - night time | IMOS - SRS - NOAA - 01 day - SST L3C - night time - Southern Ocean
IMOS - SRS SATELLITE - SST L3C - 03 DAY composite - NOAA-19 - DAY TIME | IMOS - SRS - NOAA - 03 day - SST L3C - day time
IMOS - SRS SATELLITE - SST L3C - 03 DAY composite - NOAA-19 - NIGHT TIME | IMOS - SRS - NOAA - 03 day - SST L3C - night time
IMOS - SRS SATELLITE - SST L3S - 01 day composite - day and night time composite | IMOS - SRS - NOAA - 01 day - SST L3S - day and night time
IMOS - SRS Satellite - SST L3S - 01 day composite - day time | IMOS - SRS - NOAA - 01 day - SST L3S - day time
IMOS - SRS Satellite - SST L3S - 01 day composite - night time | IMOS - SRS - NOAA - 01 day - SST L3S - night time
IMOS - SRS SATELLITE - SST L3S - 01 day composite - Southern Ocean - day and night time composite | IMOS - SRS - NOAA - 01 day - SST L3S - day and night time - Southern Ocean
IMOS - SRS Satellite - SST L3S - 03 day composite - day and night time composite | IMOS - SRS - NOAA - 03 day - SST L3S - day and night time
IMOS - SRS SATELLITE - SST L3S - 03 day composite - day time | IMOS - SRS - NOAA - 03 day - SST L3S - day time
IMOS - SRS SATELLITE - SST L3S - 03 day composite - night time | IMOS - SRS - NOAA - 03 day - SST L3S - night time
IMOS - SRS Satellite - SST L3S - 06 day composite - day and night time composite | IMOS - SRS - NOAA - 06 day - SST L3S - day and night time
IMOS - SRS Satellite - SST L3S - 06 day composite - day time | IMOS - SRS - NOAA - 06 day - SST L3S - day time
IMOS - SRS Satellite - SST L3S - 06 day composite - night time | IMOS - SRS - NOAA - 06 day - SST L3S - night time
IMOS - SRS Satellite - SST L3S - 14 day composite - day and night time composite | IMOS - SRS - NOAA - 14 day - SST L3S - day and night time
IMOS - SRS Satellite - SST L3S - 14 day composite - day time | IMOS - SRS - NOAA - 14 day - SST L3S - day time
IMOS - SRS Satellite - SST L3S - 14 day composite - night time | IMOS - SRS - NOAA - 14 day - SST L3S - night time
IMOS - SRS Satellite - SST L3S - 1 month composite - day and night time composite | IMOS - SRS - NOAA - 1 month - SST L3S - day and night time
IMOS - SRS Satellite - SST L3S - 1 month composite - day time | IMOS - SRS - NOAA - 1 month - SST L3S - day time
IMOS - SRS Satellite - SST L3S - 1 month composite - night time | IMOS - SRS - NOAA - 1 month - SST L3S - night time
IMOS - SRS Satellite - SST L3S - 1 month composite - Southern Ocean - day and night time composite | IMOS - SRS - NOAA - 1 month - SST L3S - day and night time - Southern Ocean
IMOS - SRS SATELLITE - SST L3U - NOAA-19 | IMOS - SRS - NOAA - SST L3U
IMOS - SRS SATELLITE - SST L3U - NOAA-19 - Southern Ocean | IMOS - SRS - NOAA - SST L3U - Southern Ocean

I think we can drop the NOAA-19 information since it is in the metadata record and is being used by the platform facets. Instead just put NOAA (covers NOAA-19, 18 and/or 17) to differentiate from MODIS.

**Comment by ggalibert** [comment]
@smancini - table above to be shared with SRS facility leader in order to confirm changes.

**Comment by lbesnard** [comment]
I have new records to create. Would be good to take a decision on this matter before @atkinsn creates them for me

**Comment by ggalibert** [comment]
@smancini can you please comment on the above table/suggestion of changes.

**Comment by lbesnard** [comment]
Proposed naming in following table:
https://universitytasmania-my.sharepoint.com/:x:/g/personal/laurent_besnard_utas_edu_au/EefX1JBoONxFjNpnK99IHeUBnmnaxVTpVE8Y9UzdnN6Msg?e=wFvQVx

I think we need to add in the title the reference to GHRSST or at least SST as nothing says this is actually SST data

**Comment by ggalibert** [comment]
Can we close this?

**Comment by lbesnard** [comment]
maybe we could change the title and remove sst. We still have to deal with OC
