### ISSUE TITLE
Link to BlueNet records is wrong in the pop-ups (get feature info) in the AODN Portal

### ISSUE THREAD

**Issue by atkinsn** [aodn/content#34]
For the BlueNet layers on the AODN Portal, the link to the "Data metadata record" in the get feature info, is wrongly pointing to a former IMOS MEST URL (imosmest.emii.org.au - which now resolves to 123 MEST), and not to the BlueNet MEST.
ie. http://catalogue-123.aodn.org.au/geonetwork/srv/en/metadata.show?uuid=e7b78290-be65-11dc-9c72-00188b4c0af8
should be http://bluenet.aodn.org.au/geonetwork/srv/en/metadata.show?uuid=e7b78290-be65-11dc-9c72-00188b4c0af8

I think there has been a bulk update or something in Geoserver which has been wrongly applied to the BlueNet layers.

**Comment by smancini** [comment]
Not relevant anymore
