### ISSUE TITLE
anmn_nrs_dar_yon.anmn_nrs_dar_yon_timeseries_data regularly missing

### ISSUE THREAD

**Issue by jonescc** [aodn/content#340]
We regularly get failed downloads due to this table being missing.   From the geoserver logs:

```
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: relation "anmn_nrs_dar_yon.anmn_nrs_dar_yon_timeseries_data" does not exist
  Position: 206
	at org.geotools.jdbc.JDBCFeatureReader.<init>(JDBCFeatureReader.java:155)
	at org.geotools.jdbc.JDBCFeatureSource.getReaderInternal(JDBCFeatureSource.java:619)
	... 96 more
```

Looking at the harvester we are using CASCADE when dropping views in one changeset which will automatically drop views which use it in other changesets.

Liquibase commits after each changeset so these views go missing until they are recreated later.   I also notice we are using runAlways=true which means the views will always be dropped every time the harvester is run excacerbating the problem.

I'd suggest putting all views like this in one changeset (separate sql statements) and removing the runAlways, so that the views are only ever dropped when they have been changed and so that the views/data never look like they've been dropped outside the transaction

**Comment by jonescc** [comment]
Thinking about this further, it may be helpful to use a separate changeset for refreshing the materialised view instead of dropping it and recreating it every time which is perhaps one of the reasons for the run always..

**Comment by mhidas** [comment]
Although it's a moorings collecion, this one is @lbesnard's domain.
