### ISSUE TITLE
VIT - SRS OC aqua file corrupt causing aggregations for that collection to fail

### ISSUE THREAD

**Issue by jonescc** [aodn/content#341]
Refer https://github.com/aodn/issues/issues/231

Problem file is http://data.aodn.org.au/IMOS/SRS/OC/gridded/aqua/P1D/2018/01/A.P1D.20180105T000000Z.aust.chl_oc3.nc

**Comment by mhidas** [comment]
This file has been un-harvested and removed from S3. I have saved a copy to
10-aws-syd:/mnt/ebs/wip/SRS/corrupt_chunk_in_file/
