### ISSUE TITLE
Inconsistent labels for THREDDS catalog data collection url in metadata records

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#342]
The labels used to describe the THREDDS urls for a collection of NetCDF files are inconsistent. Example:

-`Data available through the OPeNDAP server` -> http://thredds.aodn.org.au/thredds/catalog/IMOS/SRS/SST/ghrsst/L3S-3d/dn/catalog.html
-`Data available through the IMOS Thredds server` -> http://thredds.aodn.org.au/thredds/catalog/IMOS/ANMN/catalog.html

From the links above, I'd say that the exact generic label could be `Data available through THREDDS catalog`, with upper case letters to highlight the fact it is an acronym. OPeNDAP is a protocol used by THREDDS.

**Comment by ggalibert** [comment]
All ACORN metadata record have been updated so that `THREDDS catalog` is being mentioned.

**Comment by mhidas** [comment]
Batch update??

**Comment by atkinsn** [comment]
Sorry @ggalibert, it hadn't risen to the top of my pile before I went away.

**Comment by ggalibert** [comment]
We could adopt the following common label for every collection that includes one link to THREDDS catalog: **NetCDF files on THREDDS catalog**. This can be automated.

If there is multiple links to THREDDS then add a distinction in the label.

**Comment by ggalibert** [comment]
> Or even just "Data access via THREDDS catalog"? 

Why not but ...

> Couldn't THREDDS potentially serve data from other formats?

This is not currently enabled. Explicitly naming "NetCDF" was to make it clear the reason why one would access THREDDS or S3 (we also have links to S3, especially for data in non NetCDF format).

**Comment by mhidas** [comment]
:+1: Ok, makes sense.

**Comment by atkinsn** [comment]
To be done manually by me - just to confirm the final wording - "NetCDF files via THREDDS catalog" - @ggalibert ?

**Comment by ggalibert** [comment]
Yep, looks good, thanks!

**Comment by atkinsn** [comment]
All metadata records related to the Portal have been updated.
