### ISSUE TITLE
SST units is in Kelvin (not Celcius)

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#343]
From @ocehugo:
> The current portal behaviour on SST visualization is to show SST data with raw units: Kelvin.
>
> From the user perspective, this is suboptimal. Everyone is used to see data in Celsius. Would be hard to just poke a simple decorator on top to do C=K-273.15 ?

**Comment by ggalibert** [comment]
This might be a difficult one to address. The dataset is provided to us in Kelvin and we're not going to duplicate the data to create a Celsius dataset. I believe ncWMS abomination is used to render the maps on step 2 which uses the GetMap request from the WMS protocol and I don't see any way to convert the unit.

http://docs.geoserver.org/stable/en/user/services/wms/reference.html#getmap

**Comment by ocehugo** [comment]
@gg,

I'm not js/ncWMS expert, but would ncWMS allow to just shift the value when reading them? Maybe they call that functionality a lambda, or a filter. I remember seeing things like logscale in those type of maps, so the functionality or calling something atop the data is buried somewhere!

**Comment by ggalibert** [comment]
Looks like [this is not possible to achieve with older version of ncWMS](https://www.unidata.ucar.edu/mailing_lists/archives/thredds/2013/msg00411.html) (which I believe we're using). Even if we were to upgrade to [ncWMS2](https://reading-escience-centre.gitbooks.io/ncwms-user-guide/content/) this functionality wouldn't be available.

Unless we're hacking ncWMS, the only option would be to re-process all the satellite data in degree Celsius. Anyway which I don't think any of this will happen. 

@smancini can we close this?

**Comment by ggalibert** [comment]
After further reading on NcML (see "variable Element" in https://www.unidata.ucar.edu/software/thredds/current/netcdf-java/ncml/AnnotatedSchema4.html) looks like it is possible to modify attributes of an existing variable. 

So the hack would consist in modifying the 'units' attribute as well as the 'offset' one (substract 273.15 to the current offset value) in the relevant variable. Modifying the 'offset' attribute has a direct impact on the values being provided and would enable us to convert values from Kelvin to Celsius. 

Implementing this hack is a different story, each file having its own set of 'scale' and 'offset' attributes on this variable for optimal packing reasons. We would have to have a pipeline that creates a specific ncml file for each file we serve.

I've just tested this hack for one file following "Exercise 4" in https://www.unidata.ucar.edu/software/thredds/v4.6/netcdf-java/ncml/Tutorial.html and it works.

**Comment by ggalibert** [comment]
For example for this file [20180117032000-ABOM-L3C_GHRSST-SSTskin-AVHRR19_D-1d_day.nc](http://thredds.aodn.org.au/thredds/fileServer/IMOS/SRS/SST/ghrsst/L3C-1d/day/n19/2018/20180117032000-ABOM-L3C_GHRSST-SSTskin-AVHRR19_D-1d_day.nc) I have used toolsUI from Unidata to generate an NcML file and made the following modification in it:
```diff
91c91
<     <ncml:attribute name="units" value="kelvin" />
---
>     <ncml:attribute name="units" value="degrees_Celsius" />
95c95
<     <ncml:attribute name="add_offset" type="double" value="294.9328155517578" />
---
>     <ncml:attribute name="add_offset" type="double" value="21.782815552" />
```

**Comment by lbesnard** [comment]
there is nothing wrong with displaying data in Kelvin. data is correct and so is the unit. I'm closing.
