### ISSUE TITLE
Geographic extents incorrect in catalogue for some collections

### ISSUE THREAD

**Issue by craigrose** [aodn/content#345]
The affected collections appear to be all those from NOAA-17, NOAA-18 and NOAA-19 collections.  eg IMOS - SRS SATELLITE - SST L3C - 01  day composite - NOAA-19  - night time

By my estimate the east bound should be something like 170W (-170) and the west bound 70E (70) for these collections.

**Comment by craigrose** [comment]
For reference this first showed up as https://github.com/aodn/aodn-portal/issues/2667

**Comment by atkinsn** [comment]
@craigrose metadata records need to be updated.

I however need to wait until @lbesnard returns from leave (tomorrow) to provide me with a list of which records need updating, and to what.

**Comment by atkinsn** [comment]
@craigrose all metadata records (SST) have been updated - the change will be evident in production tomorrow (however note, we now have 2 bounding boxes which cross the anti-meridian, so mini-map for the short-term will display poorly until that fix is in production).

**Comment by atkinsn** [comment]
Looks like it can be closed @craigrose ?
