### ISSUE TITLE
anfog_dm.anfog_dm_trajectory_data includes trajectory data from map layer

### ISSUE THREAD

**Issue by jonescc** [aodn/content#347]
This results in geoserver using an excessive amount of memory when downloading the collection (currently causing out of memory errors - refer https://github.com/aodn/issues/issues/232).

It doesn't make sense to me to include the trajectory geometry with every measurement.  The geometry should be the latitude/longitude of the measurement.

**Comment by bpasquer** [comment]
Resolved by https://github.com/aodn/harvesters/pull/619
