### ISSUE TITLE
Incorrect description for BODAAC service on metadata records

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#353]
All metadata records mentioning the BODAAC service in "Distribution -> Online resources" has an incorrect description:

> The BODAAC is a WFS service that returns a list of OpenDAP URLs matching a query.

At the moment the service provides HTTP URLs, not OPeNDAP. In the future we might be able to use this single entry in the metadata record to provide both HTTP and OPeNDAP URLs, so I suggest we simplify the description to:

The BODAAC is a WFS service that returns a list of URLs matching a query.

**Comment by ggalibert** [comment]
All ACORN metadata records have been updated accordingly.

**Comment by mhidas** [comment]
This affects nearly _every_ collection, doesn't it. Surely this could be done as a batch update on the metadata records?

**Comment by atkinsn** [comment]
BODAAC service has been updated as part of #1014, with the following:

When a BODAAC service is present, the description text is updated to “The ncUrlList is a WFS service that returns a list of URLs matching a query." and the gmd:CI_OnlineResource description updated to "ncUrlList help documentation" i.e. replace "BODAAC help documentation" with "ncUrlList help documentation"
