### ISSUE TITLE
IMOS - SRS Bio-optical database of Australian Waters (SRS-OC-BODBAW) Sub-Facility

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#354]
The title for this metadata record could be simplified.

I believe "Sub-Facility" is not necessary.

Do we need the acronym in parenthesis? What is OC standing for?

Title could be simplified and harmonised to:
IMOS - SRS Bio Optical Database of Australian Waters

**Comment by atkinsn** [comment]
I am ok with this, if @lbesnard is?

**Comment by lbesnard** [comment]
OC stands for ocean colour. Would be nice to have this.

**Comment by ggalibert** [comment]
Ok, then I suggest to rename it:

IMOS - SRS - Ocean Colour - Bio Optical Database of Australian Waters

What do you think?

**Comment by lbesnard** [comment]
sure

**Comment by atkinsn** [comment]
Done :)
