### ISSUE TITLE
Download for aatams_sattag_nrt timed out

### ISSUE THREAD

**Issue by jonescc** [aodn/content#359]
From geoserver logs - the online resource monitor got a timeout (499) yesterday at 12:04 testing aatams_sattag_nrt_profile_map:

```
09/08/201812:04:08.000 +1000 | 172.31.8.31 - - [09/Aug/2018:02:04:08 +0000] "GET /geoserver/imos/wms?LAYERS=imos:aatams_sattag_nrt_profile_map&SERVICE=WMS&FORMAT=image/png&VERSION=1.1.1&REQUEST=GetMap&BBOX=110,-50,160,-3&WIDTH=1&HEIGHT=1 HTTP/1.1" 499 0 "-" "curl/7.47.0" "172.31.3.165"
```

This puts the collection into bad health for around 3 hours.

The reason for this is that the harverster was running at the time and used truncate to clear existing records.  This uses an exclusive lock stopping this table from being read.  Refer https://github.com/aodn/harvesters/issues/507 for more information on this issue and other harvesters affected.

**Comment by xhoenner** [comment]
@jonescc, has this issue been resolved by https://github.com/aodn/harvesters/pull/620?

**Comment by jonescc** [comment]
Resolved by https://github.com/aodn/harvesters/pull/620
