### ISSUE TITLE
IMOS NC convention - QC flag meanings 

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#360]
http://content.aodn.org.au/Documents/IMOS/Conventions/IMOS_NetCDF_Conventions.pdf
p44 of the doc, the "meaning" column values don't match exactly the expected values in the NetCDF.

For example, p44, the meaning of the flag value 0 is "No QC performed". However the expected value in the NetCDF file is "No_QC_performed" . This later value is only found in the appendix of the document.

**Comment by ggalibert** [comment]
Well spotted. I've just taken note on this for a future draft of the IMOS NetCDF convention document.

> the expected value in the NetCDF file is "No_QC_performed"

You mean expected by the checker? Have you see any IMOS NetCDF files that uses whitespaces instead of underscores like in the current convention?

**Comment by lbesnard** [comment]
Actually the checker only checks for the convention value
https://github.com/aodn/data-services/blob/master/lib/cc_plugin_imos/cc_plugin_imos/imos.py#L87

I couldn't find anywhere in the code a check on flag_values and flag_meanings. It should probably be added.

I haven't seen flag_meaning values with whitespaces, however I have seen some in lower case

**Comment by lbesnard** [comment]
@ggalibert the last version of the doc doesn't include this changes. who can do this?

**Comment by lbesnard** [comment]
is this something @ana-berger  could do?
