### ISSUE TITLE
CF compliance checker - wave standard name missing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#362]
The CF checker is complaining about an apparently non valid standard name available.
The parameter name is __sea_surface_wind_wave_period_at_variance_spectral_density_maximum__
available at:
http://cfconventions.org/Data/cf-standard-names/58/build/cf-standard-name-table.html

but the checker throws a 
```
§3.3 Standard Names                    :3:    35/36 : The standard name
                                                      'sea_surface_wind_wave_per
                                                      iod_at_variance_spectral_d
                                                      ensity_maximum' is not in
                                                      standard name table

```
maybe the standard names file needs to be updated ?

**Comment by ggalibert** [comment]
By default the checker uses an older version than v58 of the CF standard names.

Use option `-d` of the compliance checker to force it to use v58.

```bash
ggalibert@10-aws-syd:~$ compliance-checker -h
usage: compliance-checker [-h] [--test TEST]
                          [--criteria [{lenient,normal,strict}]] [--verbose]
                          [--skip-checks SKIP_CHECKS] [-f {text,html,json}]
                          [-o OUTPUT] [-V] [-l] [-d DOWNLOAD_STANDARD_NAMES]
                          [dataset_location [dataset_location ...]]

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test TEST, -t TEST, --test= TEST, -t= TEST
                        Select the Checks you want to perform. Defaults to
                        'acdd' if unspecified
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.
  --skip-checks SKIP_CHECKS, -s SKIP_CHECKS
                        Specifies tests to skip
  -f {text,html,json}, --format {text,html,json}
                        Output format
  -o OUTPUT, --output OUTPUT
                        Output filename
  -V, --version         Display the IOOS Compliance Checker version
                        information.
  -l, --list-tests      List the available tests
  -d DOWNLOAD_STANDARD_NAMES, --download-standard-names DOWNLOAD_STANDARD_NAMES
                        Specify a version of the cf standard name table to
                        download as packaged version
```

**Comment by mhidas** [comment]
Yes, we need to download the latest version into the environment used by the pipeline. However this needs root access. If just run `compliance-checker -d 58` on the command line, I get
```
IOError: [Errno 13] Permission denied: '/mnt/ebs/aodn-pipeline/local/lib/python2.7/site-packages/compliance_checker/data/cf-standard-name-table.xml'
```
@lwgordonimos @anguss00 Could we add this to the Chef code that sets up the pipeline environment?

The standard name table used doesn't have to always be the latest, it could just be a fixed version specified by a config item.

**Comment by mhidas** [comment]
Or maybe it's not worth the effort of setting this up in chef? You could just run it once as root. Then I assume that cached table will stay in place as long as that virtualenv doesn't get wiped and re-built?

**Comment by lwgordonimos** [comment]
https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/util.py#L325

It appears that it expects to update the file provided by the package *in place*, which means updates would clobber it again. It would probably be best if "properly" Chef managed, otherwise it would hit issues whenever we update it. Probably not too difficult.

1. manage compliance_checker dependency (EXISTING STEP)
1. test version of standard names XML and update if required (NEW STEP)

**Comment by lwgordonimos** [comment]
FYI, I've put up the following to see if this is a generically useful idea: https://github.com/ioos/compliance-checker/pull/603

This is not mandatory, but would make managing the file easier, and also prevent the following unlikely but possible scenario:

1. update compliance_checker
1. attempt to update standard names, but fail
1. pipelines potentially fail due to older bundled version of standard names

**Comment by ggalibert** [comment]
On a side note (this might be a bit off topic), ideally the `standard_name` version used in the file should be described and could then be used by the checker. The global attribute `standard_name_vocabulary` should endorse this role [according to ACDD](http://wiki.esipfed.org/index.php/Attribute_Convention_for_Data_Discovery) but unfortunately it doesn't give a strict convention on how to represent this information:

> The name and version of the controlled vocabulary from which variable standard names are taken. (Values for any standard_name attribute must come from the CF Standard Names vocabulary for the data file or product to comply with CF.) Example: 'CF Standard Name Table v27'.

For example files created by the toolbox follow this convention:

`standard_name_vocabulary: NetCDF Climate and Forecast (CF) Metadata Convention Standard Name Table 45`

If there was a strict convention the checker could infer which version to use.

**Comment by mhidas** [comment]
The checker does actually try to get the version number out of that attribute (see code [here](https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L117)). It doesn't rely on a specific standard wording, it basically just looks for a number in that string. However I think there might be a bug or two in there, though I haven't actually tested it.

**Comment by mhidas** [comment]
@lbesnard The standard name table used by the checker in the pipeline has been updated to v58. Could you please test this by pushing one of those wave files through the pipeline in RC?

**Comment by lbesnard** [comment]
on nec4
```
 source /mnt/ebs/aodn-pipeline/bin/activate
 netcdf-checker -t=cf /home/lbesnard/DOT-WA_W_19980101T234500Z_JUR40_WAVERIDER_FV01_END-19981203T024500Z.nc


....
--------------------------------------------------------------------------------
                  Reasoning for the failed tests given below:                   


Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
§3.3 Standard Names                    :3:     7/ 8 : The standard name
                                                      'sea_surface_wind_wave_per
                                                      iod_at_variance_spectral_d
                                                      ensity_maximum' is not in
                                                      standard name table
```

**Comment by lwgordonimos** [comment]
1. `netcdf-checker` is a confusing link to the compliance-checker installed in the system Python. Use `compliance-checker` instead

1. the name table is managed by Chef independently from the compliance-checker package, and as a result, it finds it by reading an environment variable

```bash
lbesnard@4-nec-hob:~$ source /mnt/ebs/aodn-pipeline/bin/activate
(aodn-pipeline) lbesnard@4-nec-hob:~$ export CF_STANDARD_NAME_TABLE="/mnt/ebs/aodn-pipeline/etc/cf-standard-name-table.xml"
(aodn-pipeline) lbesnard@4-nec-hob:~$ compliance-checker -t=cf /home/lbesnard/DOT-WA_W_19980101T234500Z_JUR40_WAVERIDER_FV01_END-19981203T024500Z.nc
Running Compliance Checker on the datasets from: ['/home/lbesnard/DOT-WA_W_19980101T234500Z_JUR40_WAVERIDER_FV01_END-19981203T024500Z.nc']


------------------------------------------------------------------------------------------------------------------------
                                             IOOS Compliance Checker Report                                             
                                                         cf:1.6                                                         
                                                http://cfconventions.org                                                
------------------------------------------------------------------------------------------------------------------------
                                                   Corrective Actions                                                   
DOT-WA_W_19980101T234500Z_JUR40_WAVERIDER_FV01_END-19981203T024500Z.nc has 1 potential issue


                                                        Warnings                                                        
------------------------------------------------------------------------------------------------------------------------
Name                                   Reasoning
§2.6.2 Recommended Global Attributes:  global attribute history should exist and be a non-empty
                                       string

```
@mhidas and I were talking about this last week, and it's likely that we should set this environment variable in the interactive environment, so that it is effectively the default name table.

**Comment by lwgordonimos** [comment]
In addition, the other thing which would affect the version of the name table is whether the file itself specifies a version in the standard_name_vocabulary global attribute:

https://github.com/ioos/compliance-checker/blob/master/compliance_checker/cf/cf.py#L133

In this case, the file *does* specify a version but the string isn't formatted in a way which matches the check, so is using the "default" name table (i.e. the one from the environment variable if that is set, or the one shipped with the Python package if not set).

So it's a bit confusing really.

**Comment by ggalibert** [comment]
> In this case, the file does specify a version but the string isn't formatted in a way which matches the check

I've just had a look and it seems the global attribute is set to an old version which is not consistent with the standard names used in the file anyway:

```
                :standard_name_vocabulary = "NetCDF Climate and Forecast (CF) Metadata Convention Standard Name Table 27" ;
```

Latest version is 60!

**Comment by lbesnard** [comment]
> Latest version is 60!

thanks ! fixing this

**Comment by lwgordonimos** [comment]
We can now upgrade by either setting the Chef default here: https://github.com/aodn/chef/blob/master/cookbooks/imos_po/attributes/pipeline.rb#L35

Or the same attribute can be set on a per-environment basis in the node file (e.g. for testing in RC before prod).
