### ISSUE TITLE
NOBS2 is meaningless for Seasonde ACORN data

### ISSUE THREAD

**Issue by ocehugo** [aodn/content#367]
The NOBS2 variable in Seasonde ACORN data appears meaningless in the current AODN catalog.

For both NEWC and BONC, this variable is empty for all files in the catalog. This did not occur with other datasets. This is also not self-explained in the netcdf file.

I decided to create three metrics for both NOBS1 & NOBS2 variable in each hourly hf-radar in the catalog.

Coverage [see title]:

![minimum_coverage](https://user-images.githubusercontent.com/1202691/44828254-69fca800-ac5a-11e8-8b93-b1e08a0d5297.png)

All good so far, a minimum coverage is attained for every hourly file in the catalog. Seasonde is the one having the better "coverage" in the metric terms, while the others still pretty good given >99.99 percent of the time.

Invariant NOBS1 [ All valid values are the same for all gridpoints]:  

![invariant_n1](https://user-images.githubusercontent.com/1202691/44828256-6e28c580-ac5a-11e8-9198-25defebe1494.png)

All good too. Very few cases that hourly data got a singleton value for the NOBS1.

Invaraint NOBS2 [same as above]:
![invariant_n2](https://user-images.githubusercontent.com/1202691/44828259-6f59f280-ac5a-11e8-9dc3-43513600fa79.png)

The problem peak clearly here. All Seasonde files have constant values for NOBS2.

These values are all zero :

![zeros](https://user-images.githubusercontent.com/1202691/44828494-864d1480-ac5b-11e8-93c0-4577c3a4e458.png)

This indicate a leak at least in one place:
1. In the QC procedure
2. In the Seasonde data processing.
3. Both or something in the middle.

Details:
Percentages are from the total files tested.

Files are from:
```
http://thredds.aodn.org.au//thredds/dodsC/IMOS/ACORN/gridded_1h-avg-current-map_QC
```
via dap-requests.
Some files are not included, but the coverage of files is 95+% of the total.

textfile with stats : https://expirebox.com/download/a9f32279c83a414f6a202888f0d9e683.html

**Comment by scosoli** [comment]
can't understand to what products you're referring. is it FV00 or FV01?

**Comment by ggalibert** [comment]
FV01, the QC'd one.

**Comment by scosoli** [comment]
for both BONC and NEWC you say

**Comment by scosoli** [comment]
I need to check with Yasha, I've passed data qc steps to him. I'll talk to him tomorrow and see where the problem lies. any date range or all the dataset is affected?

**Comment by ggalibert** [comment]
It looks like all the datasets from BONC and NEWC that have been inspected (more than 95% of the total collection) is affected.

**Comment by scosoli** [comment]
I think I know what is going on. not a problem with qc, not a problem with ss data processing but a bug in the netcdf conversion steps that cab be easily fixed

**Comment by scosoli** [comment]
good catch ocehugo and ggalibert. there is indeed an index swapped that points to a nan-filled variable instead of pointing to the correct variable. easy to fix for NEWC FV01, will take a bit longer for BONC FV01

**Comment by ocehugo** [comment]
always good to spot a good bug and be useful :)

**Comment by scosoli** [comment]
I've launched the creation of FV01 netcdf files for the BONC vectors with the corrected NOBS2 variable. it should not take long to finish, possibly today. once ready, I'll upload the updated files to the portal.

**Comment by scosoli** [comment]
netcdf files created and uploaded / being uploaded. NOBS2 variable should make sense now

**Comment by ocehugo** [comment]
@ggalibert can you poke me when this is done (at the opendap end)? I can easily double check by just running the code again.

**Comment by scosoli** [comment]
concluded creation of netcdf files also for NEWC node; upload of updated netcdf files is ongoing

**Comment by ggalibert** [comment]
Thanks @scosoli , looks like we've received all the reprocessed files for both BONC and NEWC.

@ocehugo would you mind running your scripts again and check the results?

**Comment by ocehugo** [comment]
@gg,

sorry, this was at the bottom of my notifications!

Will download locally and run the tests, so as to avoid the dev/sumologic/thredds harassment problem

**Comment by ocehugo** [comment]
```health_status(NEWCstats)
statistics for http://thredds-systest.aodn.org.au/thredds/dodsC/IMOS/ACORN/gridded_1h-avg-current-map_QC/NEWC/
Nobs1 field have 100% of valid data
Nobs1 field have 100% of non invariant data
Nobs1 field have 100% of non zero data

Nobs2 field have 100% of valid data
Nobs2 field have 99% of non invariant data
Nobs2 field have 100% of non zero data
```

```
health_status(BONCstats)
statistics for http://thredds-systest.aodn.org.au/thredds/dodsC/IMOS/ACORN/gridded_1h-avg-current-map_QC/BONC/
Nobs1 field have 99% of valid data
Nobs1 field have 99% of non invariant data
Nobs1 field have 100% of non zero data

Nobs2 field have 99% of valid data
Nobs2 field have 99% of non invariant data
Nobs2 field have 100% of non zero data
```

I think it's safe to close the issue, the 99% are maybe cases where there were no a single valid point coverage.
