### ISSUE TITLE
Check box for Salinity filter for ANMN Temp and Salinity collection could be more informative

### ISSUE THREAD

**Issue by kereid** [aodn/content#373]
Not sure who can change the filter labels but after a helpdesk query yesterday where the user was expecting there to be salinity data @ggalibert suggested the label of the checkbox could be more informative for https://portal.aodn.org.au/search?uuid=7e13b5f3-4a70-4e31-9e95-335efa491c5c.

I just had a look at some other collections and found that the ABOS collection filter check box labels say "Has air pressure" "Has salinity" so perhaps we could change the Temp and Sal collection to match this and be labelled "Has salinity"

**Comment by mhidas** [comment]
Easily done: https://github.com/aodn/geoserver-config/pull/573 

Could we check with the person who sent the query whether "Has salinity" is informative enough?
