### ISSUE TITLE
Wave buoy observations CSV header incomplete?

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#377]
The following collection `Wave Buoy Observations, near real-time, Australia` has its header missing the description of the following parameter:

-SPCC

**Comment by bpasquer** [comment]
Thanks for spotting it @ggalibert. 
SOOP CO2 NRT parameter mapping has same issue for parameter xH2O_PPT_raw.   Will be resolve after new units are added to the vocabulary @smancini

**Comment by bpasquer** [comment]
Resolved by https://github.com/aodn/harvesters/pull/641

**Comment by ggalibert** [comment]
Why is SPCC on a different representation than the other parameters?


data_column_name | cf_standard_name | long_name | imos_vocabulary_name | unit_name | unit_short_name | uv.definition
-- | -- | -- | -- | -- | -- | --
BOT_DEPTH | sea_floor_depth_below_sea_surface |   | Sea-floor depth below surface of the water body | Metres | m |  
DSDW | sea_surface_wave_directional_spread |   |   | Degrees True | deg T |  
LATITUDE | latitude |   | Latitude north | Degrees | deg |  
LONGITUDE | longitude |   | Longitude east | Degrees | deg |  
RDUR |   | Duration of record of wave |   | Seconds | s |  
SIF |   | Sampling interval frequency |   | Seconds | s |  
SPWP | sea_surface_wave_period_at_variance_spectral_density_maximum |   |   | Seconds | s |  
VDIR | sea_surface_wave_from_direction_at_variance_spectral_density_maximum |   |   | Degrees True | deg T |  
WHTH | sea_surface_wave_significant_height |   | Significant height of waves on the water body | Metres | m |  
WMXH | sea_surface_wave_maximum_height |   | Maximum height of waves on the water body | Metres | m |  
WPMH | sea_surface_wave_mean_period |   |   | Seconds | s |  


data_column_name | long_name |   |   |   |   |  
-- | -- | -- | -- | -- | -- | --
SPCC | Indicator for method of calculation of spectral data (WMO Code Table 1744: 1=Longuet-Higgins (1964) | 2=Longuet-Higgins (F3 method) | 3=Max likelihood method | 4=Max entropy method) |   |  

Another problem is the use of commas in the SPCC long_name. Maybe replace with ";".

Also, what is the uv.definition column for?

**Comment by bpasquer** [comment]
improve by 
https://github.com/aodn/data-services/pull/919
