### ISSUE TITLE
Wave buoy observations metadata record title

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#378]
The metadata record title for this collection is:

"Wave Buoy Observations, near real-time, Australia"

We have never used commas in this way before in a title and I think we should refrain:
1. these commas look weird in the CSV file name.
2. we already try to consistently use "-" for delimiting such information in a title.

In addition, I suggest we change the order of information so that we have something like:

"Wave Buoy Observations - Australia - near real-time"

So that if one day we have a delayed mode dataset, they will both sit next to each other in an alphabetical order. In addition this practice is already being used in other collections.

**Comment by atkinsn** [comment]
@ggalibert this record is derived from a copy of a BOM record. The naming convention comes from them, and matches the record they have in their catalogue. I will have a look in their catalogue and see what they normally do. We can go to our BOM rep and see if she is willing to change it based on the csv issue.

**Comment by atkinsn** [comment]
Just discussed with @bpasquer  - To match the delayed MHL waverider buoy collection already public, a further tweak could be: "Waverider buoys Observations - Australia - near real-time"

**Comment by ggalibert** [comment]
Sounds good.

**Comment by atkinsn** [comment]
Title change agreed to by BOM, so edited in our catalogue.
