### ISSUE TITLE
aatams_sattag_dm_metadata_summary view in parameters_mapping has three empty rows at end

### ISSUE THREAD

**Issue by akashisama** [aodn/content#380]
Which has been causing https://github.com/aodn/issues/issues/321
I've fixed our geoserver build to handle empty rows now, so that issue will be fixed, but the empty rows are probably still not meant to be there?

**Comment by ggalibert** [comment]
@xhoenner can we close this?

**Comment by xhoenner** [comment]
Yep, fixed by https://github.com/aodn/harvesters/pull/644
