### ISSUE TITLE
Inconsistent labels for S3 data collection url in metadata records

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#381]
In the Supplementary Resources from Info tab on Step 2 of the portal we can see that some links to S3 storage are not documented properly nor consistently labelled.

- [ ] Any urls to S3 should start with [data.aodn.org.au](data.aodn.org.au) and not http://imos-data.s3-website-ap-southeast-2.amazonaws.com for example.
- [ ] Any urls to S3 could be labelled something like: **Files to S3 storage**

These changes could be automated.

**Comment by atkinsn** [comment]
I need to come up with a consistent label for urls to S3 for another task I am doing. I am not sure i like @ggalibert's suggestion above "Files to S3 storage" - as requires the user to know what S3 refers to. Can we come up with something else a bit more explanatory @ggalibert and @smancini ?

To be consistent with the thredds label (NetCDF files via THREDDS catalog), something more like "Files via IMOS storage", although not sure about IMOS.

**Comment by ggalibert** [comment]
How about "Files via Amazon Web Services S3 storage"? At least now the user know where to look for info about S3. I quite like mentioning S3 just like THREDDS because both are kind of technologies with API for smart access.

**Comment by atkinsn** [comment]
Sounds like good reasoning to me @ggalibert
