### ISSUE TITLE
Layer wfs:imos:noaa_drifters_data is slow

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#39]
URL to test against:
http://geoserver-123-12-nsp-mel.aodn.org.au/geoserver/imos/wfs?typeName=imos:noaa_drifters_data&SERVICE=WFS&version=1.0.0&request=GetFeature&maxFeatures=50&outputFormat=csv

Nagios graphs:
https://nagios.aodn.org.au/pnp4nagios/graph?host=12-nsp-mel.emii.org.au&srv=geoserver+wfs%3Aimos%3Anoaa_drifters_data&view=2&start=&end=

Layer takes ~10 seconds to load in a good day.

**Comment by danfruehauf** [comment]
After the harvester redeploy and reharvest - this layer is slow indeed:
https://nagios.aodn.org.au/pnp4nagios/graph?host=12-nsp-mel.emii.org.au&srv=geoserver+wfs%3Aimos%3Anoaa_drifters_data&view=2&start=&end=

This must be addressed.

**Comment by danfruehauf** [comment]
A propsed fix for that layer is to remove the `ORDER BY` clause on the `noaa_drifters.noaa_drifters_data` view. The current view is defined as:
```
 SELECT measurement.driftnum,
    measurement.file_id,
    measurement.index,
    date(timezone('UTC'::text, measurement."time")) AS date_utc,
    timezone('UTC'::text, measurement."time") AS time_utc,
    measurement.latitude,
    measurement.longitude,
    measurement.geom
   FROM noaa_drifters.measurement
  ORDER BY measurement.driftnum, timezone('UTC'::text, measurement."time");
```

Alternatively an index can be put in place to mitigate it, but that will require more thought I guess.

**Comment by danfruehauf** [comment]
The solution is simple, an index needs to be created on both `driftnum` and `time`. For example:
```
  CREATE INDEX some_index_TODO
  ON noaa_drifters.measurement
  USING btree
  (driftnum, timezone('UTC'::text, "time"));
```

Queries will return instantly after.

**Comment by julian1** [comment]
what is the reason for the order clause ?

**Comment by danfruehauf** [comment]
@julian1 Not sure, but it's none of our business :)

**Comment by danfruehauf** [comment]
For the sake of coherency, this is the query that's being run:
```
SELECT "driftnum","file_id","index","date_utc","time_utc","latitude","longitude",encode(ST_AsEWKB("geom"),'base64') as "geom" FROM "noaa_drifters"."noaa_drifters_data" LIMIT 1
```

**Comment by julian1** [comment]
It's our business if we're required to help fix it. We should clarify with PO and then remove it if it's not required.

**Comment by julian1** [comment]
@lbesnard ?

**Comment by lbesnard** [comment]
> @lbesnard ?

I have no idea. Haven't created this harvester. Maybe required, maybe not

**Comment by lbesnard** [comment]
onto it anyway

**Comment by lbesnard** [comment]
heaps faster : https://github.com/aodn/harvesters/pull/230

**Comment by danfruehauf** [comment]
Fix works in RC.

**Comment by danfruehauf** [comment]
Deployed to Prod. Fixed.
