### ISSUE TITLE
What do we do with "NOAA - Australasian Surface Drifting Buoys" collection?

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#399]
This collection is available on prod, yet is not being updated (set up a while ago by @mhidas) and associated noaa_drifters_map layer is too slow according to Nagios (looks not too bad on the portal though).

This dataset is not IMOS nor AODN, as far as I understood it was first set up as prototype. The question is should we get rid of it or try to complete this?

**Comment by mhidas** [comment]
Related issues: #196, #335 

The layer was set up very quickly for a TAMS workshop years ago and not maintained since then. We'd need to check whether they (or anyone else) are still using it.

**Comment by ggalibert** [comment]
@mhidas, @kereid do you have a point of contact at NOAA or TAMS for this dataset?

**Comment by kereid** [comment]
@ggalibert no I don't have contact details for anyone at NOAA @smancini might? And Perhaps it would be best to contact Jessica Boomer for TAMS @mhidas will know if she is the best contact for that.

**Comment by mhidas** [comment]
Jessica Boomer is the current coordinator of TAMS. This layer was originally added in 2014 for Jason Everett, and working also with Erik van Sebille (both at UNSW).

**Comment by mhidas** [comment]
I'll contact them  to see if they're still using this collection for TAMS.

**Comment by mhidas** [comment]
They are no longer using this layer in the TAMS workshop, so I think we can safely remove it from the portal!
@ggalibert @smancini

**Comment by mhidas** [comment]
We could also remove the layers from geoserver-config, the db schema, and the harvester!
That would also resolve https://github.com/aodn/content/issues/335 and https://github.com/aodn/content/issues/196

:bird: :bird:  :bird:  with one stone! (sort of)

**Comment by ggalibert** [comment]
Sounds like a great plan!

@atkinsn could you please remove the relevant metadata record from Geonetwork?

**Comment by atkinsn** [comment]
@ggalibert  as we have had this collection up for a number of years on the Portal. What I would like to do is, to remove the WMS and WFS (etc) from the record, it will then be "removed" from the Portal. But still have it in GeoNetwork, in case someone has used this data and cited it, the link to the metadata will still resolve. I will add text to the metadata to explain when it was taken down etc.

**Comment by lbesnard** [comment]
@atkinsn is this done? can be closed?

**Comment by mhidas** [comment]
For this to be closed, the following need to happen:
- [ ] Remove WMS & WFS links from metadata record
- [ ] Remove `noaa_drifters_` layers from geoserver-config
- [ ] Remove the db schema and role
- [ ] Remove any associated files (I don't actually see any on S3 or even in archive)

**Comment by atkinsn** [comment]
> 
> 
> @atkinsn is this done? can be closed?

WMS and WFS removed, will disappear from Portal from tomorrow.
