### ISSUE TITLE
Instrument typo - Ocean Acidification - Battele instead of Battelle

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#400]
in https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=4d3d4aca-472e-4616-88a5-df0f5ab401ba (and many more)

instrument is 
```
instrumentation - Battele Seaology pCO2 monitor
```

There is a typo. Should be Battelle

https://www.battelle.org/government-offerings/national-security/maritime-systems-technologies/sensors/pco2-monitoring-system

should be fixed via regexp by devs

**Comment by atkinsn** [comment]
It's on 6 metadata records, I will fix manually.

**Comment by atkinsn** [comment]
Fixed.
