### ISSUE TITLE
SRS metadata record with link to url www.ghrsst-pp.org

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#401]
Some metadata records include a wrong link to ghrsst in the abstract part. These links need to be updated to the correct location http://ghrsst-pp.metoffice.com/ .

Example: 
https://catalogue-imos.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=744ac2a9-689c-40d3-b262-0df6863f0327
https://researchdata.ands.org.au/imos-satellite-remote-srs-facility/476864

**Comment by atkinsn** [comment]
Only found in this metadata record - has been updated.
