### ISSUE TITLE
Can we rename the IMOS parameter "Concentration of inferred chlorophyll from relative fluorescence per unit volume of the water body" to be more accurate?

### ISSUE THREAD

**Issue by mhidas** [aodn/content#403]
A couple of ANMN collections (and possibly others? https://github.com/aodn/data-services/pull/905#issuecomment-465445384) contain estimates of chlorophyll concentration derived from fluorometers (e.g. from WQM instruments). Because these are not direct measurements of chlorophyll concentration, they should **NOT** be associated with the IMOS parameter "Concentration of chlorophyll per unit volume of the water body" (or CF standard_name "mass_concentration_of_chlorophyll_in_sea_water"). In the netCDF files these have a long_name attribute "mass_concentration_of_inferred_chlorophyll_from_relative_fluorescence_units_in_sea_water" (see https://github.com/aodn/imos-toolbox/blob/master/IMOS/imosParameters.txt#L42).

We need a new parameter name in the IMOS vocab to correctly describe these variables.

**Comment by bpasquer** [comment]
There is already a term in the parameters vocab:

> Concentration of inferred chlorophyll from relative fluorescence per unit volume of the water body

**Comment by mhidas** [comment]
Ah! That's great!
(Silly me, I just assumed it didn't exist because it wasn't in the parameters_mapping schema)

Call me pedantic, but wouldn't "Concentration of **chlorophyll inferred** from relative fluorescence per unit volume of the water body" be more gramatically correct? (same goes for the long_name)

**Comment by mhidas** [comment]
Actually, "Concentration of chlorophyll per unit volume of the water body inferred from relative fluorescence" seems like the most accurate description to me.

**Comment by ggalibert** [comment]
> Actually, "Concentration of chlorophyll per unit volume of the water body inferred from relative fluorescence" seems like the most accurate description to me.

Thanks @mhidas, maybe renaming the parameter can be treated as a separate issue.

**Comment by mhidas** [comment]
> maybe renaming the parameter can be treated as a separate issue.

Ok, well since the original issue described here is already resolved (i.e. the IMOS vocab _does_ have the relevant parameter), maybe _this_ issue can become that separate issue.

**Comment by atkinsn** [comment]
The naming structure of these parameters follows a general structure. So @smancini would of crafted these terms based on this.

This term with its re-ordered components would have to be represented by a new vocab term, rather than a simple "edit", so @smancini would have to decide whether this work is warranted.

**Comment by mhidas** [comment]
Righto... I guess sticking to the established structure probably makes more sense than re-ordering the words just so it makes more sense to me.

**Comment by ggalibert** [comment]
I think @mhidas 's first suggestion "Concentration of chlorophyll inferred from relative fluorescence per unit volume of the water body" is more grammatically correct and yet still conforms to the general structure used by @smancini .

**Comment by ggalibert** [comment]
Minor change required so won't fix for now. But would be good to know how we can do this properly for the day we really want to change/update a parameter.
