### ISSUE TITLE
Absorption parameter facets

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#407]
Absorption parameter is currently found on step 1 under
```Parameter -> Physical-Water -> Optical Properties```

Could absorption parameter also be under 
```Parameter -> Biological ```
alongside Pigments ... ?

**Comment by ggalibert** [comment]
What is your motivation? Absorption is a physical property.

**Comment by lbesnard** [comment]
The reason is that for the Bio Optical database which has pigment data (biological), some users expect to see Absorption at the same level

**Comment by ggalibert** [comment]
@atkinsn all absorptions param could also be visible via the Biological facet.

**Comment by atkinsn** [comment]
I have added the 3 absorption parameters to the 'pigment' category under Biological. 

This will show up on the Portal once the next version of the parameter vocab is published (timing currently undetermined).

**Comment by atkinsn** [comment]
Work has now been done, and absorption parameters show up under both categories
