### ISSUE TITLE
soop tmv nrt - no bodaac link available

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#418]
bodaac link needs to be added to this collection to have NetCDF available via step 3
https://portal.aodn.org.au/search?uuid=d24d26cc-cd8c-4c5b-94e5-809051043d7e

**Comment by atkinsn** [comment]
Added

**Comment by lbesnard** [comment]
@atkinsn Different issue but related. Would it be possible to change in the content of the info tab of step 2 ?

removing the link to s3 and adding a link to the NetCDF's ?
NetCDF files via THREDDS catalog

Thanks a lot

**Comment by atkinsn** [comment]
Done - will show on the Portal tomorrow
