### ISSUE TITLE
Bad files harvested by soop_ba harvester

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#42]
This file causes an error in the soop_ba harvester run:
```/mnt/opendap/1/IMOS/opendap/SOOP/SOOP-BA/FV_Rehua/Rehua_20110617-20110620/IMOS_SOOP-BA_AE_20110617T092723Z_ZMRE_FV02_Rehua-ES60-38_END-20110620T204819Z_C-20140904T060129Z.nc```

This is due to `vessel_name` being absent.

**Comment by danfruehauf** [comment]
@bpasquer Was this fixed?

**Comment by bpasquer** [comment]
yes @danfruehauf .
