### ISSUE TITLE
talend aodn_ran_ctd to be decommissioned

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#421]
Talend harvester aodn_ran_ctd is highlighted by Nagios to have output errors. Who is responsible for this harvester and what can we do about it for Nagios to be happy?

**Comment by bpasquer** [comment]
It's one of the harvesters we can decommission
see https://universitytasmania-my.sharepoint.com/:x:/g/personal/craig_jones_utas_edu_au/EesdOfukYDxMhO-SG9f8pbwBnO-gMc3FYvmi9ljBYEOQVA?rtime=pCwDzLjR1kg

**Comment by bpasquer** [comment]
Achieved with https://github.com/aodn/harvesters/pull/739
and
https://github.com/aodn/chef-private/pull/3217
