### ISSUE TITLE
talend tsunami_buoys in error

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#423]
Talend harvester tsunami_buoys is highlighted by Nagios to have output errors. Who is responsible for this harvester and what can we do about it for Nagios to be happy?

**Comment by ggalibert** [comment]
This harvester can be decommissioned?

**Comment by jonescc** [comment]
Looks like it.   Its not used in production (no metadata/geoserver_config).

**Comment by bpasquer** [comment]
This issue is part of a wider discussion 
https://github.com/aodn/internal-discussions/issues/441
