### ISSUE TITLE
ANMN inconsistency in feature_type attribute 

### ISSUE THREAD

**Issue by diodon** [aodn/content#424]
From the last pull from [moorings_all_map](http://geoserver-123.aodn.org.au/geoserver/ows?typeName=moorings_all_map&SERVICE=WFS&REQUEST=GetFeature&VERSION=1.0.0&outputFormat=csv), a table of feature_type showed time**s**eries and time**S**eries. They should be the same.

Number of files by feature_type

|profile |        timeseries|         timeSeries|   timeSeries Profile|
|--------------|------------------|-----------------|-----------------------------|
3166 |     606 |   14884 |     704 

All the feature_type *timeseries* (all lower case) came from 2016, but not from a single site_code or toolbox version.

![image](https://user-images.githubusercontent.com/2551823/57205145-cf7e1100-6fff-11e9-958f-db914fc181af.png)

**Comment by mhidas** [comment]
I don't think this is a big deal. Technically CF says "The value assigned to the featureType attribute is case-insensitive" (http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#featureType), so you should always convert these attributes to lower case when comparing them.

**Comment by diodon** [comment]
ok.
