### ISSUE TITLE
SOOP SST facet update

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#426]
the spirit of tasmania 2 data is handled by BOM (Helen Beggs) and is therfore part of the soop sst sub-facility.
the spirit of tasmania 1 data is handled by EPA (Randall) and is part of the soop tmv facility

the soop tmv collection is found in the "vessel of opportunity on fixed route'. I feel like it should be the same for soop sst

FYI @smancini

**Comment by atkinsn** [comment]
@lbesnard this is actually something that comes from me.

The reason that SOOP SST is discoverable under "vessel of opportunity" is because the majority of vessels delivering this data are this type of platform.

**Comment by atkinsn** [comment]
With the new metadata standard, platform is no longer bundled with parameter. 

I have added missing vessel types to the following sub-facilities records

- SOOP SST
- SOOP BA
- SOOP XBT
