### ISSUE TITLE
AODN_WAVE_DM  timezone issue with value extracted in timezone UTC

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#429]
see  https://github.com/aodn/harvesters/issues/745
the issue is impacting the platform_coverage_start/end column only. 
We will wait for TOS7 to be deployed to PROD  to correct the impacted value. 
Fixing the issue imply reprocessing the earliest and latest file for each institution

**Comment by lbesnard** [comment]
@bpasquer do we have to push those files back or is this done?

**Comment by bpasquer** [comment]
The relevant file have not been re-pushed as far as I can remember

**Comment by lbesnard** [comment]
ok, but I don't find it clear which files need to be re-push

**Comment by bpasquer** [comment]
The data in DB prod are correct. The issues has been fixed when we reprocessed the dataset a few months ago.
