### ISSUE TITLE
SOOP TMV NRT schema to delete

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#431]
Since the SOOP TMV NRT data is now under the "soop_tmv" schema. I would recommend that we remove the "soop_tmv_nrt" schema from RC and PROD harvest databases.

Can @smancini and @ggalibert approve this on this thread so we can move forward with @ccmoloney

**Comment by lbesnard** [comment]
This is still relevant.

**Comment by ggalibert** [comment]
Please create a backlog item for this https://github.com/aodn/backlog/issues with label new and top of backlog milestone.
