### ISSUE TITLE
ACORN grid inconsistency for SAG currents between 2013 and 2014

### ISSUE THREAD

**Issue by scosoli** [aodn/content#432]
I have been contacted recently by a user in SA about a problem with DM FV01 vectors occurring between December 2013 and January 2014. Aggregation works properly as I have downloaded the entire FV00 and FV01 data sets, however data since 20140101 are mapped on a rotated grid relative to data up to 20131231. will fix this and re upload files.

**Comment by scosoli** [comment]
FV00 aggregated, 20140101T0030, looking reasonable: 
20140101T003000-aggregated-FV00.png

FV01 aggregated, 20140101T0030, looking not so much reasonable:
20140101T003000-aggregated-FV01.png
FV00 from the thredds portal, 20140101T0030, looking reasonable:
20140101T003000-thredds-FV00.png
FV01 from the thredds portal, 20140101T0030, looking as expected:

20140101T003000-thredds-FV01.png

**Comment by scosoli** [comment]
![20140101T003000-aggregated-FV00](https://user-images.githubusercontent.com/20392257/59407308-5b721e00-8da0-11e9-8068-6886d9f59058.png)
![20140101T003000-aggregated-FV01](https://user-images.githubusercontent.com/20392257/59407310-5c0ab480-8da0-11e9-8e27-f0259633052a.png)
![20140101T003000-thredds-FV00](https://user-images.githubusercontent.com/20392257/59407311-5c0ab480-8da0-11e9-9a3d-83e84267d55f.png)
![20140101T003000-thredds-FV01](https://user-images.githubusercontent.com/20392257/59407312-5c0ab480-8da0-11e9-991e-82465a868045.png)

**Comment by scosoli** [comment]
@kereid @ggalibert how do we deal with empty files in the catalog?  I have ran QC for 2013 data and found that some of the data originally on the thredds portal are empty; for instance: 10-May-2013 07:30:00; 09-Aug-2013 23:30:00; 18-Aug-2013 04:30:00, U-V and other variables are filled with nan's. I usually tend not to generate and upload these files when no data are available. what do we want to do here?

**Comment by ggalibert** [comment]
> how do we deal with empty files in the catalog?

This is a separate issue, in the future please open a different issue. See https://github.com/aodn/content/issues/433.

**Comment by scosoli** [comment]
all files have been updated and uploaded to the portal. I do not anticipate any further problems at this regard
