### ISSUE TITLE
No index supporting time filtering on soop_tmv_nrt_trajectory_data

### ISSUE THREAD

**Issue by jonescc** [aodn/content#437]
Problem identified in https://github.com/aodn/issues/issues/482

In that issue it was noticed that a download request for soop_tmv_nrt_trajectory was timing out.  The request was for:

    INTERSECTS(geom,POLYGON((144.5361328125 -41.2216796875,144.5361328125 -38.4091796875,148.0517578125 -38.4091796875,148.0517578125 -41.2216796875,144.5361328125 -41.2216796875))) AND TIME >= '2019-04-20T00:00:00.000Z' AND TIME <= '2019-05-10T23:59:59.999Z'

Looking at the postgres query plan for this request it looks like the TIME filter is used as recheck condition after using the spatial index to narrow down results, but the TIME filter looks more selective.

Looking at the view TIME is defined as:

    timezone('UTC'::text, measurements."TIME")

The only index on TIME in the measurements table is:

```
CREATE INDEX measurements_idx
  ON soop_tmv.measurements
  USING btree
  (file_id, "TIME");
```

Which can't be used as the value we are filtering on is  timezone('UTC'::text, measurements."TIME")

Can we look at whether an index on timezone('UTC'::text, measurements."TIME") (with or without file_id) can improve the performance of this request?

**Comment by lbesnard** [comment]
this was added to the harvester and deployed to aws10.
