### ISSUE TITLE
aatams sattag

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#438]
Part of the aatams sattag workflow is to download from an FTP server the newly available data. This is done in the following script, which I wrote, via a cronjob
https://github.com/aodn/data-services/blob/master/AATAMS/AATAMS_sattag_nrt/aatams_nrt.py#L66

This script uses the following metadata file, which used to be edited by Xavier to add the new wmo ids:
https://github.com/aodn/data-services/blob/master/AATAMS/aatams_sattag_metadata.csv

Since we still don't have a way to monitor PO's scripts results (Sumologic/Nagios), I only noticed today buried in my mailbox (I'm the only one I guess who receives cronjob emails) that a lot of the new tags aren't being pushed to the AODN since they aren't referenced in the aatams_sattag_metadata.csv file.

**Comment by lbesnard** [comment]
@evacougnon this is old, but I feel we probably can close this

**Comment by evacougnon** [comment]
yes @lbesnard it is not relevant now, as we are setting up a new harvester. The new way we will harvest the data will include all the data we need to harvest, including metadata. So, we won't need to look at the csv at:
