### ISSUE TITLE
australian phytoplankton static harvester

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#439]
The static version (instead of the ongoing one) of the Australian phytoplankton db harvester ran today by mistake on aws10:
aus_phyto_db

A backup of the schema 'aus_phyto_db' (and **NOT** 'aus_phyto_db_ongoing') should be uploaded to overwrite the changes done.

**Comment by ggalibert** [comment]
Can you please create a backlog item?

**Comment by atkinsn** [comment]
@ggalibert this is related to a DOI and a Data paper, so this is an issue that needs to be rectified ASAP, so its a bug.

**Comment by atkinsn** [comment]
@lwgordonimos is restoring this now. Estimate is a couple of hours, so for now, I won't worry about deactivating the DOI etc.

**Comment by lwgordonimos** [comment]
Well, that didn't take as long as I feared...

@lbesnard could you do a quick spot check on the RC database to confirm that the `aus_phyto_db` schema is as expected? If so, I will restore to prod.

**Comment by lwgordonimos** [comment]
@atkinsn @lbesnard this schema has now been restored on production

**Comment by lwgordonimos** [comment]
For posterity, the actions taken were:

```sql
harvest=# select drop_objects_in_schema('aus_phyto_db');
```

```bash
$ pg_restore -v --dbname=harvest < aus_phyto_db.dump
```
