### ISSUE TITLE
SOOP TMV Spirit of TAS realtime missing 2016

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#441]
Spirit of TAS realtime transect data NetCDF and .log files are missing for year 2016: http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/SOOP/SOOP-TMV/VLST_Spirit-of-Tasmania-1/realtime/transect/1sec/ .

**Comment by bpasquer** [comment]
I have notes from back in December 2015 mentioning an update/review in progress at EPA of the SOOP-TMV NRT workflow. The data flow was interrupted during the update and lasted until early Jan 2017(made a note on 03 Jan 2017 about receiving TMV near real-time data )
