### ISSUE TITLE
ACORN station tidy up in data reports

### ISSUE THREAD

**Issue by atkinsn** [aodn/content#444]
Here is a reminder about our discussion (from August) around noticing that in the latest Data report that there were several stations listed under site “null”
 
•	Some are due to being stations that have been added to replace others
•	The rest is due to a site of Coral Coast not being produced.

**Comment by lbesnard** [comment]
@leonardolaiolo could you have a look at the SQL queries generating the reports for ACORN and responsible for the null values?

see report
https://imos.org.au/fileadmin/user_upload/shared/IMOS_General/documents/Data_Reports/Jul21_OceanRadar_radials_Summary.pdf

**Comment by leonardolaiolo** [comment]
There are 6 new site_code than the ones reported in the SQL query used for report. I believe 2 of them (CORL and NEWC) are new sites and 4 of them may need correction in DB. Related to [this](https://github.com/aodn/content/issues/290#issuecomment-894949092).
