### ISSUE TITLE
ACORN - errors found in DM FV01 WERA radial data after 20171106T0415Z

### ISSUE THREAD

**Issue by scosoli** [aodn/content#452]
we've discovered some errors in the DM FV01 radials for WERA systems starting from 201711  and involving the ssr_Surface_Radial_Sea_Water_Speed variable. for some reason, it is written as signed integer. another variable that is affected - although in a different way, is 'ssr_Surface_Radial_Sea_Water_Speed_Standard_Error', whic is filled with '0-valued' data and a few metadata descriptors are also missing, including the 'TIME' variable, and the 'wera_Header_xxxx' vaiable, too. 
this is affecting all data starting from 0415Z. I think I have an idea of what is going on and need to work on a fix. will then upload all radials when fixed and reprocessed. luckily this is not affecting data aggregation but may be affecting users interested in accessing radial velocity data

**Comment by scosoli** [comment]
error was found in the ncread command that for some reason imported data as int32 rather than float. routine fixed and updated. pending reprocessing and upload of the updated radial velocity data for all WERA stations from 201711 on. will close this issue as soon as updated files have been uploaded to the portal

**Comment by lbesnard** [comment]
@scosoli Do you know if this was fixed?

**Comment by scosoli** [comment]
@lbesnard yes it was fixed back in 2020, I believe we can close this
