### ISSUE TITLE
SRS Seawifs TSM empty

### ISSUE THREAD

**Issue by ocehugo** [aodn/content#460]
Apparently, all of SeaWiFS TSM data presented here:
```http://thredds.aodn.org.au/thredds/dodsC/IMOS/SRS/OC/gridded/seawifs/P1H/``` are empty.

The affect files are the ```*tsm_clark.nc``` ones, with the main variable filled with zeros (useless files).

It may worth it to check for the same case in other files. I detected this when checking a user request regarding CHLA data.

**Comment by lbesnard** [comment]
http://thredds.aodn.org.au/thredds/godiva2/godiva2.html?server=http://thredds.aodn.org.au/thredds/wms/IMOS/SRS/OC/gridded/seawifs/P1H/2002/06/S.P1H.20020601T004500Z.overpass.tsm_clark.nc#

First file I'm looking at has data in. Is this the product you are referring to @ocehugo ?

**Comment by lbesnard** [comment]
All the files I'm trying have data in:
http://thredds.aodn.org.au/thredds/godiva2/godiva2.html?server=http://thredds.aodn.org.au/thredds/wms/IMOS/SRS/OC/gridded/seawifs/P1H/2002/12/S.P1H.20021201T003400Z.overpass.tsm_clark.nc
http://thredds.aodn.org.au/thredds/godiva2/godiva2.html?server=http://thredds.aodn.org.au/thredds/wms/IMOS/SRS/OC/gridded/seawifs/P1H/2002/12/S.P1H.20021202T024900Z.overpass.tsm_clark.nc
http://thredds.aodn.org.au/thredds/godiva2/godiva2.html?server=http://thredds.aodn.org.au/thredds/wms/IMOS/SRS/OC/gridded/seawifs/P1H/2007/10/S.P1H.20071001T012800Z.overpass.tsm_clark.nc
http://thredds.aodn.org.au/thredds/godiva2/godiva2.html?server=http://thredds.aodn.org.au/thredds/wms/IMOS/SRS/OC/gridded/seawifs/P1H/2004/07/S.P1H.20040701T002400Z.overpass.tsm_clark.nc

**Comment by ocehugo** [comment]
@lbesnard , you are right, closing this.

The only reason I can think off here is that I selected a region that never got data in the first place. I certainly did a subregion that because accessign this data via thredds is superslow because thredds densify the data when requesting, even if the data is super sparse like those files.
