### ISSUE TITLE
10-aws ASYNC_UPLOAD - files in ERROR_DIR

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#462]
There are 3 files in the ASYNC_UPLOAD $ERROR_DIR ```/mnt/ebs/error/ASYNC_UPLOAD``` folder on 10-aws. I have no idea who is responsible for those datasets and if those files could be deleted safely:

* Marine_larvalfish_database.map_manifest.ff50020a-9dea-466a-acd3-6539900b7dd2
* SAMUSG-1910-NXIC-CTD.map_manifest.39e8765d-c992-4eca-ae03-e4137605748f
* write_check.map_manifest.619ee96d-236c-4de2-8a55-02027cd599b8

@aodn/data-team

**Comment by mhidas** [comment]
SAMUSG-1910-NXIC-CTD.map_manifest.39e8765d-c992-4eca-ae03-e4137605748f was me. I have removed it. Dunno about the others.

**Comment by bpasquer** [comment]
none are mine.

**Comment by atkinsn** [comment]
I don't do data....

**Comment by ocehugo** [comment]
I don't deal with fish

**Comment by evacougnon** [comment]
I don't know about these files, none seem to be related with animal tracking

**Comment by lwgordonimos** [comment]
@mhidas are you *sure* you don't know about the larval fish one? ;)

```
$ cat Marine_larvalfish_database.map_manifest.ff50020a-9dea-466a-acd3-6539900b7dd2 
/mnt/wip/CSIRO/Marine_larvalfish_database.map_manifest,CSIRO/Atlas/Larval_Fish/Marine_larvalfish_database.map_manifest
/mnt/wip/CSIRO/Marine_larvalfish_database_snapshot_20180323.csv,CSIRO/Atlas/Larval_Fish/Marine_larvalfish_database_snapshot_20180323.csv
/mnt/wip/CSIRO/Master_species_list_larvalfish_database.xlsx,CSIRO/Atlas/Larval_Fish/Master_species_list_larvalfish_database.xlsx
```
```
/mnt/wip/CSIRO/Atlas/Larval_Fish$ ls -l
total 1756
-rw-rw-r-- 1 mhidas mhidas 1764369 Sep  4  2019 Marine_larvalfish_database_snapshot_20180323.csv
-rw-rw-r-- 1 mhidas mhidas   31088 Sep  4  2019 Master_species_list_larvalfish_database.xlsx
```

**Comment by mhidas** [comment]
Oh, who can be sure of anything these days?

Just delete the damn things!

**Comment by atkinsn** [comment]
My bad, I assumed this was a recent file related to the water sampling database, not from 2018. This is data for a data paper, that was emailed to me (they must of tried to send it this way initially). So agree, can be deleted.

**Comment by mhidas** [comment]
No, it wasn't "they" ... it would've been me, I just forgot. Getting old...

**Comment by mhidas** [comment]
ASYNC_UPLOAD error directory is now empty.
