### ISSUE TITLE
FAIMMS - small data quantity in recent years

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#463]
Looking at the FAIMMS collection, https://portal.aodn.org.au/search?uuid=4260aa0a-0d0a-4dd0-9ebc-74d2bf937e21
A great number of channels has not sent any data in a very very long time. Some sites seem to be down, and other active ones barely collect sea surface temperature anymore.

I think it would be interesting to look also at the data reports created by @jachope 

To do:
- [ ] look into the FAIMMS data reports
- [ ] check with IMOS office the status of FAIMMS
- [ ] contact AIMS

**Comment by ggalibert** [comment]
Closing since transferred to po-backlog.
