### ISSUE TITLE
SRS OC layer missing file url download

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#465]
From issues created by [ocehugo](https://github.com/ocehugo): aodn/issues#860  

We are missing a "file url download" option at step 3 for SRS OC netcdf files. See https://portal.aodn.org.au/search?uuid=f73daf07-eb81-4995-a72a-ca903834509f

I think the recent request from a user to bulk download the data is related to this missing option, since the only option available at the moment is the subset download.

**Comment by ggalibert** [comment]
@atkinsn may you check if this is a metadata problem!?

**Comment by ggalibert** [comment]
adding the bodaac link would be great. However I suggest we wait until next iteration as we will modify those records anyway soon to point to the generic schema.

**Comment by ggalibert** [comment]
We don't have this option configured on any of the Ocean colour collections on the Portal.
@lbesnard would be best placed to comment on whether this download option is applicable/possible for these collections.

**Comment by ggalibert** [comment]
To be converted to a content issue.

**Comment by ggalibert** [comment]
Will be fixed as part of https://github.com/aodn/PO-Backlog/issues/1240

**Comment by lbesnard** [comment]
@atkinsn can we close this?

**Comment by atkinsn** [comment]
Work done as part of https://github.com/aodn/PO-Backlog/issues/1265
