### ISSUE TITLE
Four CHLA Southern Ocean layers do not provide file list url download option

### ISSUE THREAD

**Issue by ocehugo** [aodn/content#467]
I found this issue when looking into a recent CHLA Helpdesk inquiry. 

At the moment, these CHLA Southern Ocean products do not provide a file url download option. I think they should.  For instance, daily IMOS SRS CHLA OC3 layers contains this option.

Blamed layers:
https://portal.aodn.org.au/search?uuid=bd2a812b-d76d-42eb-9654-9f2e13d305ff
https://portal.aodn.org.au/search?uuid=10fcb776-d331-4a04-ac1f-4a48fa050385
https://portal.aodn.org.au/search?uuid=ce859887-bdf0-4eb0-acf2-80d38af4c85c
https://portal.aodn.org.au/search?uuid=54023994-e1aa-479d-a693-c18dfc57a175

Requirements:
- [ ] Southern Ocean CHLA Seawifs/Aqua product layers contain the file list url download option.

@ggalibert

**Comment by atkinsn** [comment]
@lbesnard am I ok to go ahead and add (like we have just done with the other Ocean Colour collections) to these metadata records?

**Comment by atkinsn** [comment]
Content added

**Comment by ocehugo** [comment]
Don't want to step up, but shouldn't we only close when the released portal got the featureworking?

**Comment by atkinsn** [comment]
The feature will be there tomorrow when the records get harvested. This isn't related to Portal releases.
