### ISSUE TITLE
IMOS NetCDF File Naming Convention needs updating

### ISSUE THREAD

**Issue by mhidas** [aodn/content#470]
Various things need updating in the IMOS NetCDF File Naming Conventions document, including
* Text about our naming conventions being based on the OceanSITES User's Manual v 1.1 - I don't think this is very relevant anymore, as the two conventions have diverged significantly since then.
* Allow date-only timestamps in file names (YYYYMMDD) - some facilities are already doing that, including our own mooring time series products.
* Remove the table of platform codes from this document, as it is not the right place to maintain an up-to-date list of platforms. Replace with a link to the AODN Platform Vocabulary (https://vocabs.ardc.edu.au/viewById/25), and mention that the "alt label" from that vocab is the platform code.
* Also remove/update footnote 2 (page 3) which also talks about platform codes, and still refers to eMII and the old info@emii email address. 

And possibly a more significant change:
* Remove data_code field from file names?

There are some more detailed comments in the Word doc on Sheryl. The most recent file with comments is R:\IMOS\emiiSheryl\Public Documents\IMOS_AODN Public Documents\Drafts\IMOS_NetCDF_File_Naming_Convention\IMOS_NetCDF_File_Naming_Convention_v1.5.1.doc

**Comment by ana-berger** [comment]
A new version of this file with the suggested modifications addressed was recently uploaded in S3. Can we close this issue?

**Comment by mhidas** [comment]
:+1:
