### ISSUE TITLE
AusCPR: Phytoplankton Abundance - data on step appears at the same longidute of 110E (vertical line)

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#475]
see collection: https://portal.aodn.org.au/search?uuid=c1344979-f701-0916-e044-00144f7bc0f4

There is a suspicious vertical line of data in the year 2019 at 110E for IMOS - AusCPR: Phytoplankton Abundance collection. Is the data correct?

@bpasquer @mhidas

**Comment by mhidas** [comment]
There's nothing wrong with that - research ships often do transects along a meridian. In fact, if you add e.g. the [SOOP Underway CO2 delayed mode](https://portal.aodn.org.au/search?uuid=63db5801-cc19-40ef-83b3-85ccba884cf7) collection, you'll see there is indeed a line going straight through those plankton samples:

![image](https://user-images.githubusercontent.com/3579859/107439582-66d5a800-6b86-11eb-92a4-c1c056131510.png)
