### ISSUE TITLE
The IOOS compliance checker version 2.3.1 is outdated and missing standard_names 

### ISSUE THREAD

**Issue by ana-berger** [aodn/content#477]
The compliance checker needs to be updated for a more recent version as we need some wave parameters to be included in the checker, like 'sea_surface_wave_directional_spread_at_variance_spectral_density_maximum' and 'sea_surface_wave_directional_spread'. @mhidas can we have a look at this please?

**Comment by mhidas** [comment]
2.3.1 is an ancient version of the compliance-checker which was used by the old pipeline v1. As far as I know it is no longer needed - so it could be uninstalled from the system python environment on 10-aws-syd, along with the "netcdf-checker" alias (@aodn/devops ).

To run the checker manually on 10-aws-syd, please use the pipeline's virtualenv:
```bash
10-aws-syd:~$ source /mnt/ebs/pipeline/bin/activate
(pipeline) 10-aws-syd:~$ compliance-checker -V
IOOS compliance checker version 4.1.1
```

The version of the standard name table is independent of the checker itself. There is some [code](https://github.com/ioos/compliance-checker/blob/2f92a132fa5c6863b37e8b024cb390930aee22b2/compliance_checker/cf/cf.py#L117) in there to parse the version out of the global attribute `standard_name_vocabulary`, download that version (if necessary), and use it for checking the current file. The attribute needs to contain a string like "CF standard name table v60".

The checker should print a message like "Using downloaded standard name table v60" (to stderr) to confirm what it's doing.

**Comment by mhidas** [comment]
@ana-berger Please close this when you've confirmed that this works.

**Comment by ana-berger** [comment]
@mhidas thank you for your comment and for showing the code. I edited the `standard_name_vocabulary` attribute and it works as expected now, checking the CF table version that is contained in the attribute.
