### ISSUE TITLE
corrupted L3SM-6d file - contact Edward King when back from leave

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#478]
The following file was removed 
IMOS/SRS/SST/ghrsst/L3SM-6d/dn/2014/20140301212000-ABOM-L3S_GHRSST-SSTfnd-MultiSensor-6d_dn.nc

```
sst_dtime =
NetCDF: HDF error
Location: file /build/netcdf-StLR0y/netcdf-4.4.0/ncdump/vardata.c; line 473
```

contact Ed when he's back

**Comment by ggalibert** [comment]
New file uploaded 25/06 fixes this issue.
