### ISSUE TITLE
talend srs failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#48]
Due to this file:
```
http://thredds.aodn.org.au/thredds/dodsC/IMOS/SRS/SRS-OC/SRS-OC-SOOP_Rad/VMQ9273_Solander/2014/IMOS_SRS-OC_F_20140312T030831Z_VMQ9273_FV01_DALEC_20140312T032541Z_C-20140629T231726Z.nc
```

**Comment by xhoenner** [comment]
@julian1 the reporting tables in the dw_ schemas are basically a materialised view of a view in the corresponding non dw_schemas. 



> If so, then we could change the harvester config so the reporting talend connection is the same as the destination connection, and channel evertything into its correct schema.

Sounds like a good option to me, go ahead and I'll re-point my SQL queries for reporting once that's done.

**Comment by danfruehauf** [comment]
https://github.com/aodn/chef-private/pull/1458
