### ISSUE TITLE
ACORN reprocessed FV00 files

### ISSUE THREAD

**Issue by scosoli** [aodn/content#481]
FYI: We had to reprocess in DM some of the RT files fro GHED station for the time period 20210226 - 20210316 when data were collected with crossed RX wiring in the internal receiver module.
this has affected collection of radials and creation of vectors for CORL for the same time frame. 
Both radials and vectors (FV00) have been - are being updated accordingly

**Comment by lbesnard** [comment]
@scosoli , I'm not very knowledgeable with the ACORN data. I looked at the radial GHED data 
http://thredds.aodn.org.au/thredds/catalog/IMOS/ACORN/radial/GHED/2021/02/catalog.html

but can't seem to see new data uploaded there for the time period you're mentionning. Am I looking at the wrong place?

**Comment by scosoli** [comment]
There is a time gap between 20210226T030000Z and 20210305T040000Z due to failures in the power supply, hence there is ono data in this time frame for the GHED station. if you notice 20210226T020000Z was modified last on 2021-03-05T050000Z and all remaining data for 202103 mentioned above were last modified around 2021-04-28. 

what happened here is the following: I disabled RT processing from the site computer, reprocessed all affected raw data collected when wiring were swapped (as I could not transfer them over the network due to their volume), created new radials on site computer, transferred them to our server where our RT processing converts radials in proprietary format to netcdf, and updated vector maps in a similar manner.

**Comment by scosoli** [comment]
hope this is clear now

**Comment by lbesnard** [comment]
thanks a lot
