### ISSUE TITLE
University of Newcastle sea level data

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#489]
Noticed 2 separate issues with this dataset (sea level data stored in NetCDF format) 
- the .map_manifest file is published on S3
- the folder UON/NSW is not available on  the THREDDS server

**Comment by lbesnard** [comment]
@bpasquer how was the data published? I can't find a handler associated to it, async-upload?

**Comment by lbesnard** [comment]
@bpasquer 
1) I removed the manifest file
2) I added the folder to thredds
https://github.com/aodn/chef-private/pull/3905

**Comment by bpasquer** [comment]
> @bpasquer how was the data published? I can't find a handler associated to it, async-upload?

I don't know. @mhidas can you comment?

**Comment by mhidas** [comment]
I know nothing

**Comment by bpasquer** [comment]
@atkinsn  any clues what this dataset is?

**Comment by atkinsn** [comment]
Its for a DOI. Hugo put the data up at the start of the year, and @leonardolaiolo swapped some files over recently.

**Comment by leonardolaiolo** [comment]
Yes, the person wanted to update 2 or 3 files, I used async-upload - NetCDF had same structure and variables, just different numbers

**Comment by lbesnard** [comment]
BTW, I'm very surprised as of why we use both acronyms and full names on s3. http://imos-data.s3-website-ap-southeast-2.amazonaws.com/

I personally think that using acronyms is a bad habit and won't make much sense in 50 years or so

**Comment by bpasquer** [comment]
>I personally think that using acronyms is a bad habit and won't make much sense in 50 years or so
You're right. 
I have done it in the past for universities, UWA and UNSW, but it's true that I did ask myself what UON was.
It is bad practices and we should avoid it as much as we can.

**Comment by lbesnard** [comment]
it's maybe not too late. @leonardolaiolo  do you think you could see with @atkinsn a better name ? do a po_s3_del and repush the files ? I'll have a look at other folders to see if their data is linked in the harvest db

**Comment by atkinsn** [comment]
All the other universities are acronyms aside from Macquarie. Shouldn't we just leave it be (the paper is currently in review), and next time spell it out...

**Comment by bpasquer** [comment]
>it's maybe not too late

Maybe too late for some the datasets that have their URL referred to in publications

**Comment by lbesnard** [comment]
fix is made. wiating for someone to merge  https://github.com/aodn/chef-private/pull/3905
