### ISSUE TITLE
talend argo failing

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#49]
Please refer to the log, there are 534 files currently that cannot be processed.

**Comment by danfruehauf** [comment]
This is still open - still not working in prod.

**Comment by lbesnard** [comment]
@jonescc 
Was the harvester deployed to prod ? looking at the log on nsp9, it seems like we still have the same problem with files getting reprocessed ?

**Comment by jonescc** [comment]
@lbesnard - looks like the version from 12/1/15 is deployed in production (git commit 762f04f97e13100acd39a59ba2f45c80f6261ddf)

Normally, talend harvesters are written to reprocess any files they haven't successfully processed before.   For other harvesters, manual intervention is required either to fix the problem files, remove them or add them to an exclusion list.
