### ISSUE TITLE
AODN_WAVE_DM - missing some WA-DoT sites data in DB-prod 

### ISSUE THREAD

**Issue by ana-berger** [aodn/content#491]
From the 29 WA-Department of Transport buoy sites, only 11 have data harvested in the database. The portal shows all the 29 sites but apart from those 11 sites (listed below), when the data is downloaded from the portal, it has empty columns. However, in THREDDS the files are complete and contain data.

PO-Backlog item for this in https://github.com/aodn/PO-Backlog/issues/2205

These are the sites that have data in the database:
```
"Albany 04"
"Cape Naturaliste 01"
"Cape Naturaliste 02"
"Cockburn"
"Cottesloe"
"Esperance 04"
"Exmouth"
"Jurien Bay 02"
"Mandurah"
"Rottnest Island 01"
"Rottnest Island 02"

```
And these are the sites with missing data in the database:
```
Albany 02
Augusta 03
Bremer Bay 01
Bremer Bay 02
Augusta 03
Coral Bay
Dawesville 01
Dawesville 02
Dawesville 03
Esperance 02
Esperance 03
Geraldton 03
Geraldton 04
Geraldton 05
Guilderton 01
Guilderton 02
Ledge Point
Ningaloo
Oakagee 02
```

**Comment by ggalibert** [comment]
This will become irrelevant when publishing new wave dataset following ARDC project.

**Comment by ggalibert** [comment]
@ana-berger this may now be obsolete and could be closed. Please check.
