### ISSUE TITLE
AODN_WAVE_DM - filenames for the DES-Qld data files do not follow file naming convention 

### ISSUE THREAD

**Issue by ana-berger** [aodn/content#492]
The DES-Qld wave data files are the only ones between the other institutions from the National Wave Archive that contain temperature data. Based on the IMOS file naming convention, they should have a "T" in the filenames, although they do not. Something easy to be fixed in the script, as we produce the NetCDF files and their names.

Example of a current file name (1) and how it should be (2):

(1) DES-QLD_W_20081125T013000Z_Albatross-Bay_WAVERIDER_FV01_END-20151231T123000Z.nc
(2) DES-QLD_**T**W_20081125T013000Z_Albatross-Bay_WAVERIDER_FV01_END-20151231T123000Z.nc

PO-Backlog item for this in https://github.com/aodn/PO-Backlog/issues/2204

**Comment by ggalibert** [comment]
This will become irrelevant when publishing new wave dataset following ARDC project.

**Comment by ggalibert** [comment]
@ana-berger I think this is now obsolete and can be closed.
