### ISSUE TITLE
AODN_WAVE_DM and ARDC - global attribute 'instrument' in BOM files should be called 'platform'

### ISSUE THREAD

**Issue by ana-berger** [aodn/content#493]
From the discussion about data and metadata standards with the ARDC partners, it was decided that the attribute 'instrument' should be renamed to 'platform'. Review of previous wave collection will be part of a late stage of the ARDC project.

PO-Backlog item in https://github.com/aodn/PO-Backlog/issues/2206

**Comment by ggalibert** [comment]
Why is this only relevant for BOM files? 

What sort of value will you put in the attribute platform?

**Comment by ggalibert** [comment]
Also add that instrument will now hold make and model info as per IMOS convention.

**Comment by ggalibert** [comment]
This will become irrelevant when publishing new wave dataset following ARDC project.

**Comment by ggalibert** [comment]
@ana-berger I think this is now obsolete and can be closed.
