### ISSUE TITLE
Location points misleading for user (Styles on map layer)

### ISSUE THREAD

**Issue by moniquebreslin** [aodn/content#5]
Data Collections:
eg. IMOS SOOP-TMV - Data collected on the Spirit of Tasmania I during transect between Melbourne and Devonport (Near real-time),
IMOS - Australian Animal Tagging and Monitoring System (AATAMS) Facility - Tracking of Short-tailed shearwaters

On Step 2, along tracks (eg. SOOP transects, or shearwater tracks) there are  blue dots along the transect at 'bends' (visible when zoomed in to track). Under the Styles tab they are called "Measurement location" for SOOP, and "Animal geolocation" for shearwaters, but these labels are misleading for the user since the blue dots are not special locations in that sense.

Remove the blue dots?

**Comment by xhoenner** [comment]
@jachope yes this is the expected behaviour.
