### ISSUE TITLE
The Victorian bathy dataset is not a cloud optimised .tif and the .nc file is enormous

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#504]
From issues created by [alexgleith](https://github.com/alexgleith): aodn/issues#1224  

In short, I think we should delete the .nc file, as it's redundant and 60 times the size of the .tif file.

I also think that it's important to create overviews for the .tif file.

Using the command `rio cogeo create Victorian-coast_Bathy_10m.tif Victorian-coast_Bathy_10m_cog.tif` resulted in a minor file size reduction and a dramatic performance increase, including making the file work streaming over http, rather than requiring download.

Original files are here: http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=Deakin_University/bathymetry/

**Comment by ggalibert** [comment]
Nat:
> Note - this is external data that is hosted by us, the decision does not rest with us. This was set up in 2017 (and we were aware of performance issues at the time) and in view of the architecture review, future performance may be different.

**Comment by ggalibert** [comment]
@alexgleith data issues are lodged in https://github.com/aodn/content/issues. I will close this one and clone it to content.

**Comment by alexgleith** [comment]
I was thinking maybe we should simply upload another file into this folder, with `_cog.tif` at the end.

It's a little thing, but makes the .tif file much easier to use.

**Comment by ggalibert** [comment]
Send it to me and I should be able to add the cog version on S3.

**Comment by ggalibert** [comment]
For info on why NetCDF and size:

Bathymetry data is useful in oceanography for running oceanographic models. These models don't know how to read geotif, usually they get ASCII or NetCDF files, hence my choice of producing a NetCDF file.

The geotif file provides earth coordinates and only the bounds which is clever because you don't have to store all the values if in earth coordinates the grid points are all equally spaced which is the case in this file.

When running oceanographic models the reference coordinates used is a geographic lat/lon one so I had to convert the earth coordinate values to geographic values say in WGS84. When doing this conversion, you realise that the grid points are not equally distant on the geographic grid so I have to store these values for the modeller to use them in theiur model.

The reason why the NetCDF file is much bigger is because the geotiff only stores the bathy values, which in this file is around 10Gb. It is clever in the sense that it doesn't store the earth coordinate values for each grid point, it only stores the boundaries and the number of row and columns equally spaced in this rectangle. Howver, to be used in an oceanographic model we need the geographic coordinates of every grid point.

The Z values in the geotif is in single precision and amounts to ~10Gb. In the NetCDF I added all the eartjh coordinates values and all the geographic coordinates values in double precision so that the total size is roughly 10Gb (Z values in single precision) + 20Gb (earth coord in double precision) + 20Gb (geographic coord in double precision) = ~50Gb which is close to the netCDF 60Gb. The difference probably lies in the different compression used between geotiff and netCDF.

We could have not included the earth coordinatesd and save 20Gb but since I calculated the geographic ones I thought maybe someone would like to do it again to make sure I didn't make a mistake. Also we could have used single precision for both earth coordinates and geographic ones and save another 10Gb.

**Comment by alexgleith** [comment]
It's still an 800 MB file. Might be better for me to just upload direct to S3?

Or if you have a Python environment, you can install `rio_cogeo` and make the file using `rio cogeo create Victorian-coast_Bathy_10m.tif Victorian-coast_Bathy_10m_cog.tif`.

**Comment by atkinsn** [comment]
AGAIN, we need to make sure we liase with the relevant researcher at Deakin, this is NOT our data to make decisions on, we are just hosting it on their behalf. I worked with the researcher to integrate this in the past, so I need to be involved.

**Comment by alexgleith** [comment]
@atkinsn is going to email Deakin and check that they're ok with us uploading an alternative version of the .tif. They'll need to update their metadata record if we do.

**Comment by atkinsn** [comment]
We have approval from the data contributors for the addition of the additional file.

Therefore now @ggalibert 
- who is creating this file?
- who is going to upload it to the storage?

I will coordinate the update of the metadata record at Deakin and here (due to Portal hack)

**Comment by ggalibert** [comment]
> (due to Portal hack)

What this refers to is that normally we should harvest the content of the Deakin metadata record (so only one update required) but if I'm correct this automated harvest has been intentionally disabled due to some incompatibility during the Geonetwork upgrade. At that time, to overcome this blocker it has been decided that we would keep a copy of the Deakin record and that we would manage it manually ourselves. The idea is that in the future we should revisit this and make sure we can harvest the original record properly into our GN v3.

**Comment by ggalibert** [comment]
> - who is creating this file?

@alexgleith created the file. It would be good if he could send it to @evacougnon and share with her some info or script about how the conversion was done for her to be able to re-produce in the future. I will pass on to @evacougnon my other scripts that created the NetCDF files.

> - who is going to upload it to the storage?

@evacougnon will upload the file to /mnt/ebs/incoming/Deakin/bathymetry/incoming

**Comment by alexgleith** [comment]
Hey @evacougnon if you have somewhere you can install a Python package, do `pip install rio-cogeo` and then download the original .tif and run this in the same folder `rio cogeo create Victorian-coast_Bathy_10m.tif Victorian-coast_Bathy_10m_cog.tif`

**Comment by evacougnon** [comment]
File on s3 now: http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=Deakin_University/bathymetry/

**Comment by alexgleith** [comment]
Fantastic, @evacougnon 

I've tested with: `rio cogeo validate https://s3-ap-southeast-2.amazonaws.com/imos-data/Deakin_University/bathymetry/Victorian-coast_Bathy_10m_cog.tif`

And it works!

> https://s3-ap-southeast-2.amazonaws.com/imos-data/Deakin_University/bathymetry/Victorian-coast_Bathy_10m_cog.tif is a valid cloud optimized GeoTIFF
