### ISSUE TITLE
AIMS_MMP_CTD pipeline pointing to non-existent incoming dir

### ISSUE THREAD

**Issue by mhidas** [aodn/content#507]
Looks like this pipeline recently got deployed to prod (https://github.com/aodn/chef-private/pull/4201) but also had a last-minute change to the incoming directory name (https://github.com/aodn/chef-private/pull/4058). However, the [watch config](https://github.com/aodn/chef-private/blob/master/data_bags/imos_po_watches/AIMS_MMP_CTD.json) wasn't updated, so this pipeline can't be set up.

Unfortuntely this also prevents ALL pipelines from bing set up, so all incoming files are stacking up in the incoming dirs...

**Comment by mhidas** [comment]
This should fix it https://github.com/aodn/chef-private/pull/4204

**Comment by ggalibert** [comment]
@mhidas I assume we can now close this?

**Comment by mhidas** [comment]
Fixed in https://github.com/aodn/chef-private/pull/4207
