### ISSUE TITLE
CSV subset of ATTAMS SATTAG DM turtle data contains seal data

### ISSUE THREAD

**Issue by bpasquer** [aodn/content#523]
Creating an a subset from the collection:
IMOS - Animal Tracking Facility - Satellite Relay Tagging Program - Delayed mode data with quality-controlled locations

to get  turtle data for location in Northern Territory  (like for ex Lat/Lon -12.174, 139.966 to Lat/Lon -10.328, 145.239)

returns a csv file that contains the relevant turtle data  but  also Seal data from the Kerguelen Isl 
See the extract here:

[IMOS_-_Animal_Tracking_Facility_-_Satellite_Relay_Tagging_Program_-_Delayed_mode_data_with_quality-controlled_locations-Argos_locations.csv](https://github.com/user-attachments/files/17335935/IMOS_-_Animal_Tracking_Facility_-_Satellite_Relay_Tagging_Program_-_Delayed_mode_data_with_quality-controlled_locations-Argos_locations.csv)

**Comment by xhoenner** [comment]
The CSV content is looking fine. The metadata header contains seal metadata, but I don't think there's anything that can be done about this. After removing all rows starting with `#`, I get the following data summary per species
![image](https://github.com/user-attachments/assets/9ea36e81-de1d-4eb0-a783-047273ccdd38)
