### ISSUE TITLE
Temporary rsync files lying in filesystem

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#53]
I've sent an email about it, but I'll open an issue as well.

How to reproduce:
 * Look for hidden files on the production filesystem (opendap and public)

What to expect:
 * No temporary rsync files lying around

What happens:
 * ~30K temporary rsync files out and about

**Comment by ggalibert** [comment]
@lbesnard why can --delete-before be really dangerous?

If I understood well : --delete-before deletes files in the destination directory before copying file-with-same-name from source directory.

**Comment by danfruehauf** [comment]
@ggalibert `--delete-before` factors a list of deletions before transfer takes place. This is why I think @lbesnard believes it is dangerous. And it is.

**Comment by ggalibert** [comment]
ACORN is not a problem anymore, I've updated my calls to rsync so that option --delete-before is added.

@danfruehauf I identified 3992 files of 0byte each on OPENDAP which I deleted.

**Comment by danfruehauf** [comment]
@ggalibert Thanks!

**Comment by ggalibert** [comment]
Ok, to all who would follow this discussion, --delete-before is dangerous if you perform your rsync with --remove-source-files on a directory : 

rsync -vaR --remove-source-files $DATA/ACORN/WERA/radial_nonQC/output/datafabric/gridded_1havg_currentmap_nonQC/./ $OPENDAP/ACORN/gridded_1h-avg-current-map_non-QC/

Next call to this rsync command will see empty directories as source so that same name directories in target will be deleted...

If rsync is performed on a list of files as input : 

cat /tmp/move_FV00_vector.checkedList | rsync -va --remove-source-files --files-from=- $STAGING/ACORN/acorn-migration-hierarchy/vector/ $OPENDAP/ACORN/vector/

then --delete-before should be safe.

**Comment by danfruehauf** [comment]
I don't think this can be closed.

**Comment by danfruehauf** [comment]
I'd like to shed some more light on that. I think the root of the problem is the crappy network that we have on NSP, which results in bad NFS performance. After migrating the ACORN processing to use the event driven infrastructure, more than once already I've seen files being denied from reaching the production filesystem because of null permission files such as:
```
$ ls -l /mnt/opendap/1/IMOS/opendap/ACORN/radial/GUI/2015/07/02/IMOS_ACORN_RV_20150702T085000Z_GUI_FV00_radial.nc
---------- 1 nobody users 0 Jul 10  1993 /mnt/opendap/1/IMOS/opendap/ACORN/radial/GUI/2015/07/02/IMOS_ACORN_RV_20150702T085000Z_GUI_FV00_radial.nc
```

Files that are denied will be put in the error directory and it is pretty easy to move them back to the incoming directory after cleaning up the bogus file with the 000 permissions.

Before that, ACORN used rsync to move the files. rsync uses temporary files and then renames them. This caused all sort of random files to stay on the production filesystem, such as:
```
./NNB/2015/06/06/.IMOS_ACORN_RV_20150606T143500Z_NNB_FV00_radial.nc.wsa4Ff
./NNB/2015/06/06/.IMOS_ACORN_RV_20150606T121500Z_NNB_FV00_radial.nc.uSvQAc
./NNB/2015/06/06/.IMOS_ACORN_RV_20150606T143500Z_NNB_FV00_radial.nc.Xtc4Ff
./NNB/2015/06/30/.IMOS_ACORN_RV_20150630T094500Z_NNB_FV00_radial.nc.rTYMO0
./NNB/2015/06/16/.IMOS_ACORN_RV_20150616T090500Z_NNB_FV00_radial.nc.qx0cp0
./CSP/2015/05/15/.IMOS_ACORN_RV_20150515T090500Z_CSP_FV00_radial.nc.iOcJkd
./CSP/2015/05/28/.IMOS_ACORN_RV_20150528T074500Z_CSP_FV00_radial.nc.rnmvDF
./CSP/2015/05/31/.IMOS_ACORN_RV_20150531T191500Z_CSP_FV00_radial.nc.Fqanqz
./CSP/2015/05/31/.IMOS_ACORN_RV_20150531T014500Z_CSP_FV00_radial.nc.p72Srn
./CSP/2015/05/31/.IMOS_ACORN_RV_20150531T152500Z_CSP_FV00_radial.nc.IBmq0M
./CSP/2015/05/31/.IMOS_ACORN_RV_20150531T230500Z_CSP_FV00_radial.nc.lFEfpY
./CSP/2015/05/30/.IMOS_ACORN_RV_20150530T121500Z_CSP_FV00_radial.nc.PKHHZ6
```

272 in total in the `radial` directory. All are zero sized with null permissions:
```
---------- 1 9008 users 0 May  2  1974 ./LEI/2015/06/04/.IMOS_ACORN_RV_20150604T072500Z_LEI_FV00_radial.nc.NHJjdc
---------- 1 9008 users 0 Jul  1  1980 ./LEI/2015/06/12/.IMOS_ACORN_RV_20150612T221500Z_LEI_FV00_radial.nc.nTRuD4
---------- 1 9008 users 0 Jul 24  1975 ./LEI/2015/06/06/.IMOS_ACORN_RV_20150606T023500Z_LEI_FV00_radial.nc.kUin9L
---------- 1 9008 users 0 Mar 31  1976 ./LEI/2015/06/06/.IMOS_ACORN_RV_20150606T213500Z_LEI_FV00_radial.nc.kmvF6K
---------- 1 9008 users 0 Nov 26  1975 ./LEI/2015/06/06/.IMOS_ACORN_RV_20150606T140500Z_LEI_FV00_radial.nc.IT2IpJ
---------- 1 9008 users 0 Mar 31  1976 ./LEI/2015/06/06/.IMOS_ACORN_RV_20150606T193500Z_LEI_FV00_radial.nc.qTQTwd
---------- 1 9008 users 0 Mar 31  1976 ./LEI/2015/06/06/.IMOS_ACORN_RV_20150606T220500Z_LEI_FV00_radial.nc.AVerIe
```

It seems like only half the move transaction is done (creating the file) without setting permissions. I suspect due to a timeout on either side of the NFS volume. We can probably mitigate it in code, but ideally I'd like to mitigate it by not relying on crappy NFS volumes for moving files around.

**Comment by danfruehauf** [comment]
Cleaned up ACORN completely now. Shouldn't have more in `radial` or `vector` as they are using the event driven processing which will not allow such files to appear.

**Comment by ggalibert** [comment]
My hourly averaged product for current is created every hour and rsync'ed from WIP to OPENDAP. Hopefully there is no zero byte files left by this process in ```gridded_1h-avg-current-map_non-QC``` and ```gridded_1h-avg-current-map_QC```.

**Comment by danfruehauf** [comment]
I'm closing that because the solution is being implemented already and those stray files will not make it to S3.
