### ISSUE TITLE
Argo profile colour

### ISSUE THREAD

**Issue by dnahodil** [aodn/content#60]
When viewing the Argo profiles layer on a display with low colour fidelity it can be lost against the blue of the ocean. I've seen this on projectors as well as printed screenshots.

If there isn't a particular reason we choose the blue colour for the points then it might be worth changing it to be a more contrasting colour.

**Comment by pblain** [comment]
A darker shade of blue would probably do the trick

**Comment by lbesnard** [comment]
@pblain I'll do it. I have a argo geoserver PR, so I'll put it in the same commit. Just give me the Hex colour if you want

**Comment by pblain** [comment]
@pmbohm , could you please give Loz a nice high contrast blue colour?

**Comment by pmbohm** [comment]
What about FFEAA4 which is a complementary colour to the deep blue of the base layer. It is also close to the Argo color @lbesnard

**Comment by lbesnard** [comment]
done here https://github.com/aodn/geoserver-config/pull/251 . will be visible once merged
