### ISSUE TITLE
SRS data collection not displaying as expected

### ISSUE THREAD

**Issue by atkinsn** [aodn/content#61]
Looking at the "SRS Satellite Contributed Ocean Colour - SeaWIFS Chlorophyll Concentration in the Southern Ocean: Weekly, Johnson et al 2013" data collection on the 123 Portal is not displaying a full set of data encircling the globe. The date first displayed is 11/12/10 (the most recent date), and only displays data around Australia. This might lead the user to surmise that the collection has only a limited geographic range. 
This was seen in firefox.

**Comment by smancini** [comment]
seems to work fine now
