### ISSUE TITLE
Argo collection title

### ISSUE THREAD

**Issue by pblain** [aodn/content#70]
Why is the argo data collection entitled "IMOS - Argo Australia Profiles" when it contains many international argo profiles (e.g. China)?  Seems a bit misleading. 

![image](https://cloud.githubusercontent.com/assets/2802359/5368883/28f24cc2-8060-11e4-94c4-ae383b352f42.png)

**Comment by smancini** [comment]
The title has been changed to "IMOS - Argo Profiles" waiting for the short title feature to be implemented. Then it will be "Argo profiles"
