### ISSUE TITLE
srs altimetry - no download possible on 123

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#71]
No data is downloadable from the layer srs_altimetry_timeseries_data. It is visible in geoserver-123 and in  the getCapabilities :
http://geoserver-123.aodn.org.au/geoserver/ows?service=wfs&version=1.0.0&request=GetCapabilities

However, the layer is inactive in the portal config (https://imos.aodn.org.au/imos123/layer/edit/6460862), and the wms/wfs scanner remains true to itself. 

Will have to fix it next year

**Comment by lbesnard** [comment]
@jachope To reply to your email, no. Nothing has been done on this end. I just checked again, it's not working through the portal. However the data is definitely there and can be downloaded through wfs :

```bash
curl -L "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=srs_altimetry_timeseries_data&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=site_name%20LIKE%20'Bass%20Strait'%20AND%20instrument%20LIKE%20'SBE26-PressureGauge'" -o altimetry_noHeader.csv
```

and even with the metadata header :
```bash
curl -L "http://geoserver-123.aodn.org.au/geoserver/ows?typeName=srs_altimetry_timeseries_data&SERVICE=WFS&outputFormat=csv-with-metadata-header&REQUEST=GetFeature&VERSION=1.0.0&CQL_FILTER=site_name%20LIKE%20'Bass%20Strait'%20AND%20instrument%20LIKE%20'SBE26-PressureGauge'" -o altimetry_Header.csv
```

I don't think I can do anything myself. It seems to be more a developer's thing

**Comment by smancini** [comment]
I think I know why this is not working.
The WFS layer is missing from the portal admin interface.
So we need to run the WMS scanner so that the portal knows about that layer.

**Comment by lbesnard** [comment]
yeap, but the wms scanner never works. It always fails before reaching this layer

**Comment by smancini** [comment]
Fixed as described in https://github.com/aodn/content/issues/84
