### ISSUE TITLE
Missing parameter/platform terms

### ISSUE THREAD

**Issue by julian1** [aodn/content#73]
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. requestNotifier.js:63
window.controllers is deprecated. Do not use it for UA detection. OpenLayers.js:1171
"Could not find broader term for parameter 'Speed (over ground) of measurement platform'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Direction of motion (over ground) of measurement platform'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Orientation (pitch) of measurement platform'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Orientation (roll angle) of measurement platform'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Direction of motion (over ground) of measurement platform'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Height above sensor'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Depth below surface of the water body'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Correlation in magnitude of the particle distribution in the water body'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Percentage of good three beam solutions (one beam rejected) in ADCP bin'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Percentage of good transformations (error velocity threshold not exceeded) in ADCP bin'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Percentage of measurements where more than one beam was bad in ADCP bin'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Percentage of measurements with four beam solutions in ADCP bin'" FacetedSearchResultsDataView.js:73
"Could not find broader term for parameter 'Depth below surface of the water body'" FacetedSearchResultsDataView.js:73
"Could not find broader term for platform ''" FacetedSearchResultsDataView.js:172
"Could not find broader term for parameter 'Depth below surface of the water body'" FacetedSearchResultsDataView.js:73

**Comment by smancini** [comment]
These parameters do not have a broader term because we did not want them to be included in the faceted search in step 1 of the portal.
Why is it important to have a broader term to all parameter?

**Comment by smancini** [comment]
These terms are now included in another vocabulary called "sampling parameter".
Natalia will remove these parameters from any of the metadata records in catalogue-123
