### ISSUE TITLE
anmn_regridded_temperature_data geoserver WFS layer doesn't work

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#74]
Not sure what is the reason for that, but this stopped working at around 2015/01/21-17:00.

In addition, also the talend job fails (anmn_t_regridded).

**Comment by anguss00** [comment]
I deployed a new version of this harvester to prod that should fix the talend job. Not sure about the geoserver layer though

**Comment by danfruehauf** [comment]
It's all fixed I believe.
