### ISSUE TITLE
ANMN_TS erroneous timestamp, see screenshot.

### ISSUE THREAD

**Issue by xhoenner** [aodn/content#76]
![anmn_ts_timestampissue](https://cloud.githubusercontent.com/assets/3443821/6035065/6c397ef0-ac80-11e4-8cf2-ba19541be5f1.jpg)

**Comment by mhidas** [comment]
Thanks for picking this up @xhoenner . I've removed the offending file from opendap (and a couple of others with bad timestamps) and notified the data processors. 
I've re-run the harvester, so the db has also been updated.
