### ISSUE TITLE
talend harvesters use full path when indexing files

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#82]
I'll put it here in the content repository although the fix should be done by a joint dev/po force.

Currently the harvesters are using full path names when indexing files, such as:
```
/mnt/imos-t3/IMOS/opendap/OceanCurrent/GSLA/NRT00/2011/IMOS_OceanCurrent_HV_20111019T000000Z_GSLA_FV02_NRT00_C-20111104T012551Z.nc.gz
```
Ideally we'd use just a relative path:
```
1/IMOS/opendap/OceanCurrent/GSLA/NRT00/2011/IMOS_OceanCurrent_HV_20111019T000000Z_GSLA_FV02_NRT00_C-20111104T012551Z.nc.gz
```

The logic behind the path is:
```
SHARD_NUMBER/ORG/COLLECTION_NAME/rest_of_hierarchy
```

Sharding mostly gives me (the admin) a way of spreading data across filesystems since it is never guaranteed to have proper storage at the right time and the right place.

That would get reduce quite a bit of configuration pain when trying to access those files via thredds or data.aodn.org.au - meaning we don't need to strip arbitrary prefixes such as `/mnt/imos-t3`, or `/mnt/imos-t4`.

**Comment by mhidas** [comment]
Doesn't this belong more in the harvesters repo?

**Comment by danfruehauf** [comment]
Either. Can be moved if you're really fussy about it.

**Comment by danfruehauf** [comment]
Wuuuuuhuuuuuuuuuuuuuuuuu.
