### ISSUE TITLE
Empty csv File

### ISSUE THREAD

**Issue by kereid** [aodn/content#84]
Moving from aodn-portal (issue #1635)

Instance name: IMOS
App version: 3.42.1
Build date: Wed Mar 18 10:53:36 AEDT 2015
Build number: 374
Git ref: fd0444a

I'm only seeing this on one collection... @anguss00 is this possibly something related to your stuff...

Steps to reproduce:

Add IMOS - SRS Satellite Altimetry Calibration and Validation Sub-Facility to the map. Proceed to step 3 check download size, reads about 81.8 MB go back to step 2 and subset - either date or geo or check box and proceed to step 3 check download size, Click download as csv

What should happen:

Get a csv file with values

What does happen:

Get empty csv file

Think I found another one IMOS - SOOP-Sea Surface Temperature (SST) Sub-facility - Near real-time data I drew a bounding box and so on step 3 it indicated download size is 18.2 kb but only had metadata in the csv - hmm unless it's counting the metadata info as part of the size, then I guess I am incorrect, (which I don't agree with getting when i get no data anyway)

**Comment by dnahodil** [comment]
@lbesnard and I spoke about this one yesterday. Did you find where the problem was, Loz?

**Comment by lbesnard** [comment]
Yeap, I did the modification on the harvester back in November, but it never got deployed on Jenkins, and must have been forgotten. I spotted the error yesterday now that I do know about Jenkins, and build it on RC. Since TPAC is down, and buidling nsp14 can't be done atm (at least yesterday), the harvester can't be tested yet.

**Comment by dnahodil** [comment]
That's right, I forgot you told me that. Cool, we can test that harvester when TPAC is back.

**Comment by lbesnard** [comment]
@danfruehauf  remembered this chat about reloading geoserver ? well it fixed it on RC. didn to it on 123 though. And it seems like geoserver didn't reload in the last few days. So this is not working on prod yet.  Also filters aren't being shown properly for this layer, which I guess is related. Would it be possible to reload GS ?

**Comment by danfruehauf** [comment]
I'd actually like to get something more consolidated in place. Run the reload via chef or something...

**Comment by lbesnard** [comment]
fixed
