### ISSUE TITLE
Collections not visible on Portal 123 when using filters

### ISSUE THREAD

**Issue by ggalibert** [aodn/content#87]
@dnahodil suggested I lodge this in content :

-on portal 123, by default, on the first page of results you can see the collection "IMOS - Australian National Mooring Network (ANMN) Facility - WQM and CTD burst averaged data products" with attributes :

Chlorophyll, Oxygen, Salinity, Temperature, Turbidity, Water pressure
Integrated Marine Observing System (IMOS), CSIRO Oceans & Atmosphere Flagship - Hobart
Mooring
2008 - 2015

-however when applying a filter like Platform -> Moorings on the facets, we cannot find this collection anymore.

Other collections impacted (there might be more) are ANMN_NRS_RT_Meteo, ANMN_NRS_RT_Bio...

**Comment by smancini** [comment]
This issue is not relevant anymore.
The problem in Geonetwork which had an impact on the faceted search has been solved.
