### ISSUE TITLE
SRS OC layers return no results

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#88]
Aggregations don't work on some SRS OC layers, for example `srs_oc_chl_oc3_1d_aqua_url`

Run the following and you get no results:
```
curl -v "http://geoserver-123.aodn.org.au/geoserver/wfs?typeName=srs_oc_chl_oc3_1d_aqua_url&SERVICE=WFS&outputFormat=csv&REQUEST=GetFeature&VERSION=1.0.0"
```

@lbesnard

**Comment by lbesnard** [comment]
... feeling the worse ... 

```
-rw-rw-r-- 1 talend talend 1.2K Apr  7 19:32 console.2015-04-07-18-49-44.log
-rw-rw-r-- 1 talend talend 1.7K Apr  8 19:38 console.2015-04-08-18-54-29.log
-rw-rw-r-- 1 talend talend 1.2K Apr  9 19:04 console.2015-04-09-18-04-57.log
-rw-rw-r-- 1 talend talend 2.8K Apr 10 19:25 console.2015-04-10-18-40-51.log
-rw-rw-r-- 1 talend talend 3.2K Apr 11 23:17 console.2015-04-11-22-35-18.log
-rw-rw-r-- 1 talend talend 2.6K Apr 12 18:48 console.2015-04-12-18-00-03.log
-rw-rw-r-- 1 talend talend 6.3M Apr 14 00:00 console.2015-04-13-20-12-11.log
```

isn't it funny that suddenly the log file for yesterday is way bigger ? Investigating more, but I hope the folder structure hasn't changed

**Comment by lbesnard** [comment]
same thing is currently happening with srs-sst harvester

**Comment by lbesnard** [comment]
@danfruehauf Could it be because of the TPAC storage failing yesterday ? data missing, everything gets deleted ?

**Comment by lbesnard** [comment]
the modification time of opendap/2 is today at 10:04 . maybe this is why

**Comment by danfruehauf** [comment]
As I said before - still shouldn't remove all the files in the DB - should just abort the execution...

**Comment by lbesnard** [comment]
@jonescc how does the iharvestressources component work ? Does it check that the sourceDir is connected or exist ?

**Comment by jonescc** [comment]
If there's an error reading the source directory to list files, iIndexResources should abort and abort the harvest run - I say should - we should check this and it would depend on whether the harvester itself has has been configured to ignore errors.

If the source directory exists and there are just no files, then, no I don't think it would abort.   Sounds like a sanity check that should be added to the iIndexresources component.   The whole thing was designed to be a mirroring process so if files are deleted from the source they should be removed from the databse

**Comment by danfruehauf** [comment]
Saying that, I think sshfs will just return an empty directory listing when the remote end is not available.

Proper solution for that - allocate storage for SRS data.

**Comment by lbesnard** [comment]
@danfruehauf yeap but even if a directory doesn't exist, the iharvest component in its actual stage doesn't fail. I talked to @pblain , something will be done.

**Comment by danfruehauf** [comment]
@lbesnard Yep, good spotting. Needs to be fixed ASAP, no doubt about it.

**Comment by lbesnard** [comment]
fixed here : https://github.com/aodn/harvesters/commit/eb9994b1dfbd1f54c0465d79d62db128c1fc205a
