### ISSUE TITLE
geoserver - reload feature layer

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#89]
## Issue
If a new column is added through liquibase for a specific harvester, but none of the geoserver layer xml config files needs to be modified, Geoserver doesn't reload all the features by itselft. The button (bottom left of each layer) reload feature type has to be pressed.

This problem happened with a srs_altimetry harvester. The data layer lacked of the geom column making the use of bounding box impossible to download the data. However the geoserver layer didn't have to be modified.

## Solution

 * either via chef to trigger the reload feature type for every single layer when the node is build
``` LAYER_NAME=srs_altimetry_timeseries_map'
http://geoserver-rc.aodn.org.au/geoserver/web/?wicket:bookmarkablePage=:org.geoserver.web.data.resource.ResourceConfigurationPage&name=$LAYER_NAME&wsName=imos#
```
 * either a separate cron
 * something else

**Comment by lbesnard** [comment]
already talked with @dnahodil  about this
probably not the best place for this @pblain

**Comment by danfruehauf** [comment]
I think that's more of an infrastructure problem rather than content to be honest.

In terms of engineering, I'm not quite sure what we can offer. I'm not opposed to a global geoserver reload of resources after all the harvesters have run. It doesn't cause downtime and will happen somewhere early in the morning.

**Comment by pblain** [comment]
I agree with Loz and Dan that this isn't the best repo for this issue.  Please move this issue to a more appropriate one.  The content repo is for issues related to the data, layers, metadata, etc that the project officers have published through our various data access services (e.g. portal).  Issues related to the infrastructure belong elsewhere.

**Comment by smancini** [comment]
Has it been fixed or should it be added to the backlog repo?
