### ISSUE TITLE
Information tab missing on step 2 for GHRSST collection

### ISSUE THREAD

**Issue by kereid** [aodn/content#9]
Base URL:      http://portal-rc.aodn.org.au/imos123
    Build date:    18/03/2014 14:13
    Version:       3.19.0-rc2
    Instance name: IMOS
    Environment:   prerelease

The IMOS - SRS Satellite - L3P GHRSST-SSTsubskin-AVHRR MOSAIC 01km - sea surface temperature collection when added to the map does not have an info tab on rc it appears on Production, it should be configured to match.

**Comment by smancini** [comment]
All satellite collection seem to have information available in the info tab
