### ISSUE TITLE
geoserver wfs:imos:anmn_burst_avg_timeseries_data is slow

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#92]
That started roughly at 27/04/2015 00:00.

MUST BE ADDRESSED URGENTLY.

https://nagios.aodn.org.au/pnp4nagios/index.php/graph?host=1-aws-syd.emii.org.au&srv=geoserver%20wfs:imos:anmn_burst_avg_timeseries_data

**Comment by jonescc** [comment]
Looks like I accidentally an RC version of this harvester to Production when promoting the error on no files found changes made aftr they ran successfully in rc.

I don't think https://github.com/aodn/harvesters/commit/cb270bd86daeebc439b17e11cd5e8773382b2401#diff-45aba994e1a8b40f0aa526e1ad7128f5 or https://github.com/aodn/harvesters/commit/31d4123d25697d9633fc4876769b5fbfcf0a877a#diff-45aba994e1a8b40f0aa526e1ad7128f5  ever got promoted.

Suggest this change is reverted, backed out of rc and prod and re-thought.

**Comment by danfruehauf** [comment]
@jonescc Please link the fix that was introduced (the git commit or PR).

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/harvesters/commit/39fac914d04b68158edb55bfc23cab4c3d9aac12

**Comment by danfruehauf** [comment]
That can be closed.
