### ISSUE TITLE
Layer wfs:imos:wfs:imos:soop_tmv_nrt_trajectory_data is slow

### ISSUE THREAD

**Issue by danfruehauf** [aodn/content#93]
https://nagios.aodn.org.au/pnp4nagios/index.php/graph?host=12-nsp-mel.emii.org.au&srv=geoserver%20wfs:imos:soop_tmv_nrt_trajectory_data

Around the 5 seconds mark.

**Comment by xhoenner** [comment]
Noticed that a while ago, currently backing up the schema to play with indexes on my VM

**Comment by danfruehauf** [comment]
:+1: Let me know if you need any assistance - I'm more than happy to help.

**Comment by danfruehauf** [comment]
Deploying now to production.

**Comment by danfruehauf** [comment]
GJ guys (@lbesnard @xhoenner), difference can already be seen at:
https://nagios.aodn.org.au/pnp4nagios/index.php/graph?host=12-nsp-mel.emii.org.au&srv=geoserver%20wfs:imos:soop_tmv_nrt_trajectory_data
