### ISSUE TITLE
talend anmn_nrs_bgc - failing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#96]
the havester seemd to fail because of problems in the geoserver:

https://www.cmar.csiro.au/geoserver/wfs?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetFeature&TYPENAME=imos:NRS_STATION&PROPERTYNAME=STATE,STATION_DEPTH_M,NODE,LATITUDE,START_DATE,STATION_NAME,LONGITUDE,IMOS_SITE_CODE,STATION_PT&SRSNAME=EPSG:4326

I think @mhidas has mentioned this to us, isn't it right @smancini . Do you know who we need to contact at CMAR ?

**Comment by danfruehauf** [comment]
I think this is not failing anymore so I'm alright with closing it. Unless someone thinks there should be more investigations done here.
