### ISSUE TITLE
talend anmn_nrs_dar_yon

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#97]
Issue :

```
INFO 5/11/15 7:03 AM:liquibase: Waiting for changelog lock....
```

sounds like a database issue, maybe being jammed ? I remembered having some similar issues once developping on my machine.

What do you reckon  @julian1 ?

**Comment by danfruehauf** [comment]
It's possible that when 9-nsp-mel got jammed, also a lock stayed in the DB. We can clear that lock.

**Comment by danfruehauf** [comment]
I manually released the stuck liquibase lock (from 2015-04-28 15:00:10.953+00). Not sure why it got stuck and not it's also too late to troubleshoot it.

Generally speaking I think we should attend quicker to failing harvesters.

This is unrelated to https://github.com/aodn/internal_discussions/issues/132 - as this rebuild came almost a week after.
