### ISSUE TITLE
talend anmn_nrs_rt_* biogeochem, meteo and wave failing

### ISSUE THREAD

**Issue by lbesnard** [aodn/content#98]
Those 3 harvesters all failed for the same reason. Which is not really clear why :
```bash
SQL exception:
 Message: ERROR: duplicate key value violates unique constraint "timeseries_platform_depth_start_unique"
  Detail: Key (platform_code, instrument_nominal_depth, time_coverage_start)=(NRSNSI-SubSurface, 20, 2015-01-01 00:14:33+00) already exists.
 SQLSTATE: 23505
 Error code: 0
 Stacktrace:org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "timeseries_platform_depth_start_unique"
  Detail: Key (platform_code, instrument_nominal_depth, time_coverage_start)=(NRSNSI-SubSurface, 20, 2015-01-01 00:14:33+00) already exists.

```

Did a mod on the biogeochemistry harvester (https://github.com/aodn/harvesters/pull/222), however I think this won't fix it. I have the feeling there are too many boxes ticked as primary key in the tpostgresRow component. But since I write my harvesters differently from @mhidas , I don't want to change everything my way (which wouldn't necessarily fix things anyway).

The most likely reason is probably due to the reinstall of nsp9 on Friday. However, this also means something in the harvester is not handle the right way. 

A temporary fix will be to drop the objects on those 3 schemas on today at 5pm, and re-run the harvesters from scratch. Which should be really fast to do. @danfruehauf 

@smancini @mhidas FYI

**Comment by lbesnard** [comment]
@danfruehauf  to perform :
```
select drop_objects_in_schema('anmn_nrs_rt_bio');
select drop_objects_in_schema('anmn_nrs_rt_meteo');
select drop_objects_in_schema('anmn_nrs_rt_wave');
```

at @lbesnard to do :
```
talend_run anmn_nrs_rt_biogeochem_timeseries-anmn_nrs_rt_biogeochem_timeseries
talend_run anmn_nrs_rt_meteo_timeseries-anmn_nrs_rt_meteo_timeseries
talend_run anmn_nrs_rt_wave_timeseries-anmn_nrs_rt_wave_timeseries
```

**Comment by danfruehauf** [comment]
Done.

**Comment by lbesnard** [comment]
all fixed. no errors
